/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSManagedObjectID, NSEntityDescription;

@interface _CDSnapshot : NSObject <NSCopying, NSMutableCopying> {
    int _cd_rc;
    int _cd_version;
    NSManagedObjectID *_cd_objectID;
    struct _snapshotFlags_st { 
        unsigned int _readOnly : 1; 
        unsigned int _reservedFlags : 31; 
    } _cd_flags;
    unsigned int _cd_nullFlags_;
}

@property(readonly) NSEntityDescription * entity;
@property(readonly) NSManagedObjectID * objectID;

+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)alloc;
+ (unsigned int)newBatchAllocation:(id*)arg1 count:(unsigned int)arg2 withOwnedObjectIDs:(id*)arg3;
+ (Class)classForEntity:(id)arg1;
+ (void)_entityDeallocated;

- (id)initWithObjectID:(id)arg1;
- (id)entity;
- (id)objectID;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)retainCount;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)valueForKey:(id)arg1;
- (id)copy;
- (id)mutableCopy;
- (id)description;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)dealloc;
- (void)finalize;
- (id)retain;
- (oneway void)release;
- (id)_descriptionValues;
- (id)_snapshot_;

@end
