/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface _CLMainService : NSObject <CLIntersiloServiceProtocol> {
}

+ (id)getSilo;
+ (void)becameFatallyBlocked:(id)arg1;


@end
