/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

@class NSString, NSArray;

@interface _CPPowerAssertion : NSObject  {
    unsigned int _assertion;
    double _timeout;
    NSString *_identifier;
    NSArray *_stack;
}

@property double timeout;
@property(readonly) NSString * identifier;


- (double)timeout;
- (id)initWithIdentifier:(id)arg1 timeout:(double)arg2;
- (void)timedout;
- (id)identifier;
- (void)dealloc;
- (void)setTimeout:(double)arg1;

@end
