/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSURL, NSString;

@interface _GEORegionalResourceDownload : NSObject  {
    NSString *_name;
    int _type;
    NSURL *_url;
    NSString *_destinationPath;
    NSString *_expectedChecksum;
}

@property(copy) NSString * name;
@property int type;
@property(copy) NSURL * url;
@property(copy) NSString * destinationPath;
@property(copy) NSString * expectedChecksum;


- (id)destinationPath;
- (id)expectedChecksum;
- (void)setExpectedChecksum:(id)arg1;
- (void)setDestinationPath:(id)arg1;
- (void)setUrl:(id)arg1;
- (int)type;
- (void)setType:(int)arg1;
- (id)url;
- (id)name;
- (void)setName:(id)arg1;
- (void)dealloc;

@end
