/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@class _HKFactorization, _HKDimension;

@interface _HKCompoundUnit : HKUnit  {
    _HKFactorization *_baseUnits;
    _HKDimension *_dimension;
    int _dimensionLock;
}

+ (BOOL)supportsSecureCoding;
+ (id)unitWithBaseUnits:(id)arg1;

- (id)dimension;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_initWithBaseUnits:(id)arg1;
- (id)_computeBaseUnitReductionAndProportionalSize:(out double*)arg1 withCycleSet:(id)arg2;
- (id)_baseUnits;
- (id)unitString;

@end
