/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface _HKEntitlements : NSObject  {
}

+ (id)entitlementsWithApplicationIdentifier:(id)arg1;
+ (id)entitlementsWithConnection:(id)arg1;
+ (void)_setEntitlementsForCurrentTask:(id)arg1;
+ (id)entitlementsWithDictionary:(id)arg1;
+ (id)entitlementsForCurrentTask;

- (id)valueForEntitlement:(id)arg1;
- (BOOL)hasEntitlement:(id)arg1;
- (id)applicationIdentifier;
- (id)stringForEntitlement:(id)arg1;

@end
