/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@class NSDate;

@interface _HKTimePeriod : NSObject <NSSecureCoding> {
    NSDate *_startDate;
    NSDate *_endDate;
}

@property(readonly) NSDate * startDate;
@property(readonly) NSDate * endDate;

+ (BOOL)supportsSecureCoding;
+ (id)timePeriodWithStartDate:(id)arg1 endDate:(id)arg2;

- (id)endDate;
- (id)startDate;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (int)compareByEndDate:(id)arg1;
- (int)compareByStartDate:(id)arg1;
- (BOOL)overlapsTimePeriod:(id)arg1;
- (BOOL)containsTimePeriod:(id)arg1;
- (BOOL)startsAfterDate:(id)arg1;
- (BOOL)endsBeforeDate:(id)arg1;
- (id)_initWithStartDate:(id)arg1 endDate:(id)arg2;
- (BOOL)containsDate:(id)arg1;

@end
