/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@class NSString;

@interface _MKPlaceAction : NSObject  {
    NSString *_title;
    SEL _action;
}

@property(copy) NSString * title;
@property SEL action;


- (void).cxx_destruct;
- (void)setAction:(SEL)arg1;
- (SEL)action;
- (id)title;
- (void)setTitle:(id)arg1;

@end
