/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface _NSCoreManagedObjectID : NSManagedObjectID  {
}

+ (int)version;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)retain;
+ (void)release;
+ (id)alloc;
+ (void)_storeDeallocated;
+ (id)managedObjectIDFromURIRepresentation:(id)arg1;
+ (id)managedObjectIDFromUTF8String:(const char *)arg1 length:(unsigned int)arg2;
+ (Class)classWithStore:(id)arg1 andEntity:(id)arg2;
+ (void)setObjectStoreIdentifier:(id)arg1;
+ (void)_release_1;
+ (id)_retain_1;
+ (char *)generatedNameSuffix;
+ (BOOL)accessInstanceVariablesDirectly;
+ (void)_setStoreInfo1:(id)arg1;
+ (id)_storeInfo1;
+ (unsigned int)allocateBatch:(id*)arg1 count:(unsigned int)arg2;

- (id)URIRepresentation;
- (BOOL)isTemporaryID;
- (id)entity;
- (id)entityName;
- (unsigned int)retainCount;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)finalize;
- (id)retain;
- (oneway void)release;
- (BOOL)_isPersistentStoreAlive;
- (id)_storeIdentifier;
- (id)persistentStore;
- (id)_storeInfo1;

@end
