/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class RCCaptureInputDevice, NSMutableArray, RCCaptureSession;

@interface _RCCaptureInputDeviceSession : NSObject  {
    NSMutableArray *_sessionFinishedBlocks;
    BOOL _useStartSoundEffect;
    BOOL _captureSessionWasActivated;
    RCCaptureInputDevice *_captureInputDevice;
    RCCaptureSession *_captureSession;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _sessionPreparedBlock;

}

@property(readonly) RCCaptureInputDevice * captureInputDevice;
@property BOOL useStartSoundEffect;
@property(retain) RCCaptureSession * captureSession;
@property BOOL captureSessionWasActivated;
@property(copy) id sessionPreparedBlock;


- (id)captureInputDevice;
- (void)setCaptureSessionWasActivated:(BOOL)arg1;
- (BOOL)useStartSoundEffect;
- (void)setSessionPreparedBlock:(id)arg1;
- (void)setUseStartSoundEffect:(BOOL)arg1;
- (void)setCaptureSession:(id)arg1;
- (id)initWithCaptureInputDevice:(id)arg1;
- (void)invokeSessionFinishedBlocksWithError:(id)arg1;
- (BOOL)captureSessionWasActivated;
- (id)captureSession;
- (id)sessionPreparedBlock;
- (void)addSessionFinishedBlock:(id)arg1;
- (void).cxx_destruct;
- (id)description;
- (void)dealloc;

@end
