/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

@class AVAudioSession, NSString, NSArray;

@interface _RCMPRoutingController : MPAVRoutingController  {
    AVAudioSession *_audioSession;
    BOOL _isCategoryActive;
    BOOL _hasCategoryEverBeenActive;
    BOOL _disableRouteChangeNotificationHandling;
    BOOL _needsFetch;
    NSArray *_cachedRoutes;
    NSString *_AVAudioSessionCategory;
    NSString *_AVSystemControllerCategory;
}

@property(readonly) BOOL hasCategoryEverBeenActive;
@property(readonly) BOOL isAudioSessionAppropriateForQueryingRoutes;
@property(readonly) NSString * AVAudioSessionCategory;
@property(readonly) NSString * AVSystemControllerCategory;


- (id)AVSystemControllerCategory;
- (id)AVAudioSessionCategory;
- (BOOL)_determineIfAudioCategoryIsCurrent;
- (void)setIsCategoryActive:(BOOL)arg1;
- (BOOL)isCategoryConfiguredForVoiceMemos;
- (void)audioSessionRouteChangeNotification:(id)arg1;
- (void)audioSessionInterruptionNotification:(id)arg1;
- (void)makeAudioSessionCategoryActive:(BOOL)arg1;
- (BOOL)isAudioSessionAppropriateForQueryingRoutes;
- (BOOL)hasCategoryEverBeenActive;
- (id)initWithName:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)fetchAvailableRoutesWithCompletionHandler:(id)arg1;
- (BOOL)routeOtherThanHandsetAndSpeakerAvailable;

@end
