/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSTimer, _UIDocumentPickerDocumentTableViewController, SKUIItemOfferButton, NSURL;

@interface _UIDocumentPickerDocumentTableCell : UITableViewCell  {
    _UIDocumentPickerDocumentTableViewController *_weak_tableView;
    NSURL *_url;
    NSTimer *_progressTimer;
    SKUIItemOfferButton *_cloudButton;
    id _progressSubscriber;
}

@property(getter=URL,setter=setURL:,retain) NSURL * url;
@property(retain) NSTimer * progressTimer;
@property(retain) SKUIItemOfferButton * cloudButton;
@property(retain) id progressSubscriber;
@property _UIDocumentPickerDocumentTableViewController * tableView;


- (id)progressTimer;
- (void)startDownload:(id)arg1;
- (void)updateProgress:(id)arg1;
- (void)updateForDownloadStatus;
- (id)cloudButton;
- (void)setProgressSubscriber:(id)arg1;
- (void)setCloudButton:(id)arg1;
- (void)setProgressTimer:(id)arg1;
- (id)progressSubscriber;
- (void)setURL:(id)arg1;
- (id)tableView;
- (void)prepareForReuse;
- (void)setTableView:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)URL;
- (void)dealloc;

@end
