/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class <UITableViewDataSource>;

@interface _UIFilteredDataSource : NSObject <UITableViewDataSource> {
    BOOL _limitingWithSections;
    int _maxVisibleSection;
    int _numberOfVisibleItemsInLastSection;
    int _filterType;
    <UITableViewDataSource> *_tableDataSource;
}

@property int filterType;
@property <UITableViewDataSource> * tableDataSource;


- (int)_filteredNumberOfItemsGivenSection:(int)arg1 numberOfItems:(int)arg2;
- (id)tableDataSource;
- (void)setFilterType:(int)arg1;
- (void)setTableDataSource:(id)arg1;
- (int)filterType;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (BOOL)respondsToSelector:(SEL)arg1;

@end
