/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class _UIAsyncInvocation, <_UIViewServiceViewControllerOperatorDelegate>, _UIHostedTextServiceSession, NSMutableArray, UIActionSheet, _UIViewServiceDummyPopoverController, NSString, UIViewController, UIPopoverController, _UIHostedWindow;

@interface _UIViewServiceViewControllerOperator : UIViewController <_UIViewServiceViewControllerOperator_RemoteViewControllerInterface, _UIHostedTextServiceSessionDelegate, _UIViewServiceDummyPopoverControllerDelegate, _UIViewServiceDeputy, _UIViewServiceDeputyRotationSource> {
    int _hostPID;
    NSString *_hostBundleID;
    struct { 
        unsigned int val[8]; 
    } _hostAuditToken;
    id _remoteViewControllerProxyToOperator;
    id _remoteViewControllerProxyToViewController;
    UIViewController *_localViewController;
    NSString *_presentationControllerClassName;
    _UIHostedWindow *_hostedWindow;
    BOOL _isResigningFirstResponderFromHostNotification;
    BOOL _disableAutomaticKeyboardBehavior;
    UIActionSheet *_hostedActionSheet;
    BOOL _serviceInPopover;
    int _hostStatusBarOrientation;
    float _hostStatusBarHeight;
    NSMutableArray *_deputyRotationDelegates;
    unsigned int _hostAccessibilityServerPort;
    _UIHostedTextServiceSession *_textServiceSession;
    _UIAsyncInvocation *_prepareForDisconnectionInvocation;
    _UIAsyncInvocation *_invalidationInvocation;
    int __automatic_invalidation_retainCount;
    BOOL __automatic_invalidation_invalidated;
    UIPopoverController *_displayedPopoverController;
    _UIViewServiceDummyPopoverController *_dummyPopoverController;
    unsigned int _supportedOrientations;
    BOOL _canShowTextServices;
    <_UIViewServiceViewControllerOperatorDelegate> *_delegate;
}

@property <_UIViewServiceViewControllerOperatorDelegate> * delegate;

+ (id)operatorWithRemoteViewControllerProxy:(id)arg1 hostPID:(int)arg2 hostBundleID:(id)arg3 hostAuditToken:(struct { unsigned int x1[8]; })arg4;
+ (id)XPCInterface;

- (void)dismissHostedTextServiceSession:(id)arg1 animated:(BOOL)arg2;
- (id)_sessionForStateRestoration:(id)arg1;
- (BOOL)_validateSessionIdentifier:(id)arg1 restorationAnchor:(id)arg2 functionName:(const char *)arg3;
- (id)_supportedInterfaceOrientationsForViewController:(id)arg1;
- (void)_windowDidUnregisterScrollToTopView;
- (void)_windowDidRegisterScrollToTopView;
- (void)_windowDidUpdateCurrentTintView:(id)arg1;
- (void)_viewServiceIsDisplayingPopoverController:(id)arg1;
- (id)_inputViewsKey;
- (void)_popoverDidDismiss:(id)arg1;
- (void)_popoverWillPresent:(id)arg1;
- (void)_prepareForDisconnectionUnconditionallyThen:(id)arg1;
- (void)__createViewController:(id)arg1 withAppearanceSerializedRepresentations:(id)arg2 legacyAppearance:(BOOL)arg3 hostAccessibilityServerPort:(id)arg4 canShowTextServices:(BOOL)arg5 replyHandler:(id)arg6;
- (void)dummyPopoverController:(id)arg1 didChangeContentSize:(struct CGSize { float x1; float x2; })arg2 animated:(BOOL)arg3;
- (void)dummyPopoverController:(id)arg1 popoverViewDidSetUseToolbarShine:(BOOL)arg2;
- (void)__prepareForDisconnectionWithCompletionHandler:(id)arg1;
- (void)__restoreStateForSession:(id)arg1 restorationAnchor:(id)arg2;
- (void)__saveStateForSession:(id)arg1 restorationAnchor:(id)arg2 completionHandler:(id)arg3;
- (void)__textServiceDidDismiss;
- (void)__setHostTintColor:(id)arg1 tintAdjustmentMode:(int)arg2;
- (void)__hostDidUpdateAppearanceWithSerializedRepresentations:(id)arg1 originalSource:(id)arg2 legacyAppearance:(BOOL)arg3;
- (id)_appearanceSource;
- (void)__dimmingViewWasTapped;
- (void)__setServiceInPopover:(BOOL)arg1;
- (void)__hostDidRotateFromInterfaceOrientation:(int)arg1 skipSelf:(BOOL)arg2;
- (void)__hostWillRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2 skipSelf:(BOOL)arg3;
- (void)__hostWillAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2 skipSelf:(BOOL)arg3;
- (void)__hostDidSetPresentationControllerClassName:(id)arg1;
- (void)__hostViewDidDisappear:(BOOL)arg1;
- (void)__hostViewWillDisappear:(BOOL)arg1;
- (void)__hostViewDidAppear:(BOOL)arg1;
- (void)__hostViewDidMoveToScreenWithIntegerDisplayID:(unsigned int)arg1 newHostingHandleReplyHandler:(id)arg2;
- (void)__hostViewWillAppear:(BOOL)arg1 inInterfaceOrientation:(int)arg2 statusBarHeight:(float)arg3 completionHandler:(id)arg4;
- (void)__hostDisablesAutomaticKeyboardBehavior:(BOOL)arg1;
- (void)__hostedActionSheetClickedButtonAtIndex:(int)arg1;
- (void)__hostedActionSheetDidDismissWithClickedButtonIndex:(int)arg1;
- (void)__hostedActionSheetDidPresent;
- (void)__hostDidPromoteFirstResponder;
- (void)__scrollToTopFromTouchAtViewLocation:(struct CGPoint { float x1; float x2; })arg1 resultHandler:(id)arg2;
- (void)__hostDidSetContentOverlayInsets:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (void)__hostDidEnterBackground;
- (void)__hostWillEnterForeground;
- (void)__hostDidChangeStatusBarHeight:(float)arg1;
- (void)__hostDidChangeStatusBarOrientationToInterfaceOrientation:(int)arg1;
- (void)_firstResponderDidChange:(id)arg1;
- (void)__hostReadyToReceiveMessagesFromServiceViewController;
- (void)__createViewController:(id)arg1 withContextToken:(id)arg2 appearanceSerializedRepresentations:(id)arg3 legacyAppearance:(BOOL)arg4 hostAccessibilityServerPort:(id)arg5 canShowTextServices:(BOOL)arg6 replyHandler:(id)arg7;
- (void)__setContentSize:(struct CGSize { float x1; float x2; })arg1;
- (id)_queue;
- (void)establishViewControllerDeputyWithProxy:(id)arg1 completionHandler:(id)arg2;
- (void)addDeputyRotationDelegate:(id)arg1;
- (void)_invalidateUnconditionallyThen:(id)arg1;
- (int)__automatic_invalidation_logic;
- (BOOL)_presentActionSheet:(id)arg1 asPopoverFromBarButtonItem:(id)arg2 orFromRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg3 inView:(id)arg4 withPreferredArrowDirections:(unsigned int)arg5 passthroughViews:(id)arg6 backgroundStyle:(int)arg7 animated:(BOOL)arg8;
- (void)_dismissActionSheet:(id)arg1 withClickedButtonIndex:(int)arg2 animated:(BOOL)arg3;
- (BOOL)_presentActionSheet:(id)arg1 inView:(id)arg2 fromYCoordinate:(float)arg3;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_frameForContainerViewInSheetForBounds:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (BOOL)_isHostedRootViewController;
- (void)_didResignContentViewControllerOfPopover:(id)arg1;
- (void)_willResignContentViewControllerOfPopover:(id)arg1;
- (void)_didBecomeContentViewControllerOfPopover:(id)arg1;
- (void)_willBecomeContentViewControllerOfPopover:(id)arg1;
- (id)_presentationControllerClassName;
- (void)_updateSupportedInterfaceOrientationsIfNecessary;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_frameForContainerViewInSheetForBounds:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 displayingTopView:(BOOL)arg2 andBottomView:(BOOL)arg3;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (void)viewDidLoad;
- (struct CGSize { float x1; float x2; })contentSizeForViewInPopover;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)loadView;
- (struct CGSize { float x1; float x2; })preferredContentSize;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (BOOL)_disableAutomaticKeyboardBehavior;
- (id)_viewControllersForRotationCallbacks;
- (void)setNeedsStatusBarAppearanceUpdate;
- (id)_showServiceForText:(id)arg1 type:(int)arg2 fromRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg3 inView:(id)arg4;
- (BOOL)_canShowTextServices;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)becomeFirstResponder;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)delegate;
- (unsigned int)retainCount;
- (id)invalidate;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (id)retain;
- (oneway void)release;

@end
