/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebUI.framework/WebUI
 */

@class <WebPolicyDecisionListener>, WebFrame, NSDictionary;

@interface _WBUPolicyDecisionListener : NSObject <WebPolicyDecisionListener> {
    WebFrame *_frame;
    int _navigationType;
    NSDictionary *_formMetadata;
    <WebPolicyDecisionListener> *_originalListener;
}


- (id)initWithFrame:(id)arg1 navigationType:(int)arg2 formMetadata:(id)arg3 originalListener:(id)arg4;
- (void).cxx_destruct;
- (void)use;
- (void)ignore;
- (void)download;

@end
