/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@class NSString, NSArray;

@interface AAFamilyDetailsResponse : AAResponse  {
    NSArray *_members;
    BOOL _canAddMembers;
    BOOL _canAddChildMembers;
    NSArray *_invites;
    NSArray *_pendingMembers;
    NSString *_childAccountPrompt;
    NSString *_childAccountButtonTitle;
}

@property(readonly) NSArray * members;
@property(readonly) NSArray * invites;
@property(readonly) NSArray * pendingMembers;
@property(readonly) int memberCount;
@property(readonly) int pendingMemberCount;
@property(readonly) int pendingInviteCount;
@property(readonly) BOOL canAddMembers;
@property(readonly) BOOL canAddChildMembers;
@property(readonly) NSString * childAccountPrompt;
@property(readonly) NSString * childAccountButtonTitle;
@property(readonly) NSArray * firstNames;


- (id)members;
- (id)childAccountButtonTitle;
- (id)childAccountPrompt;
- (BOOL)canAddChildMembers;
- (BOOL)canAddMembers;
- (id)pendingMembers;
- (id)firstNames;
- (int)pendingInviteCount;
- (int)pendingMemberCount;
- (int)memberCount;
- (id)initWithHTTPResponse:(id)arg1 data:(id)arg2;
- (void).cxx_destruct;
- (id)invites;

@end
