/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@class NSNumber, NSString, NSDate;

@interface AAFamilyMember : NSObject  {
    BOOL _isMe;
    BOOL _isChild;
    BOOL _isSharingPurchases;
    BOOL _areParentalControlsEnabled;
    BOOL _isAskToBuyEnabled;
    NSString *_firstName;
    NSString *_lastName;
    NSString *_appleID;
    NSNumber *_personID;
    NSString *_title;
    NSDate *_joinDate;
    NSString *_linkediTunesAppleID;
    NSNumber *_linkediTunesDSID;
}

@property(copy) NSString * firstName;
@property(copy) NSString * lastName;
@property(copy) NSString * appleID;
@property(copy) NSNumber * personID;
@property(copy) NSString * title;
@property(copy) NSDate * joinDate;
@property BOOL isMe;
@property BOOL isChild;
@property BOOL isSharingPurchases;
@property NSString * linkediTunesAppleID;
@property NSNumber * linkediTunesDSID;
@property BOOL areParentalControlsEnabled;
@property BOOL isAskToBuyEnabled;


- (BOOL)isMe;
- (void)setAppleID:(id)arg1;
- (void)setLastName:(id)arg1;
- (void)setFirstName:(id)arg1;
- (id)lastName;
- (id)firstName;
- (void)setPersonID:(id)arg1;
- (id)personID;
- (id)appleID;
- (void)setIsAskToBuyEnabled:(BOOL)arg1;
- (BOOL)isAskToBuyEnabled;
- (void)setAreParentalControlsEnabled:(BOOL)arg1;
- (BOOL)areParentalControlsEnabled;
- (void)setLinkediTunesDSID:(id)arg1;
- (id)linkediTunesDSID;
- (void)setLinkediTunesAppleID:(id)arg1;
- (id)linkediTunesAppleID;
- (void)setIsSharingPurchases:(BOOL)arg1;
- (BOOL)isSharingPurchases;
- (void)setIsChild:(BOOL)arg1;
- (BOOL)isChild;
- (void)setIsMe:(BOOL)arg1;
- (void)setJoinDate:(id)arg1;
- (id)joinDate;
- (void).cxx_destruct;
- (id)title;
- (void)setTitle:(id)arg1;

@end
