/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppleAccountUI.framework/AppleAccountUI
 */

@class <AAUIChildAccountCreationDelegate>, RUILoader, NSMutableArray, AASetupAssistantService, UINavigationController, AAGrandSlamSigner, NSURL;

@interface AAUIChildAccountCreationController : NSObject <RUIObjectModelDelegate> {
    AASetupAssistantService *_setupService;
    AAGrandSlamSigner *_grandSlamSigner;
    NSURL *_launchingURL;
    NSMutableArray *_objectModels;
    RUILoader *_loader;
    <AAUIChildAccountCreationDelegate> *_delegate;
    UINavigationController *_navigationController;
}

@property <AAUIChildAccountCreationDelegate> * delegate;
@property UINavigationController * navigationController;


- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3;
- (void)objectModelPressedBack:(id)arg1;
- (unsigned int)supportedInterfaceOrientationsForObjectModel:(id)arg1 page:(id)arg2;
- (id)parentViewControllerForObjectModel:(id)arg1;
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 actionSignal:(int)arg3;
- (void)loader:(id)arg1 didFailWithError:(id)arg2;
- (void)objectModelDidChange:(id)arg1;
- (void)_popObjectModelAnimated:(BOOL)arg1;
- (void)loadRemoteUI;
- (void)_createChildAccount;
- (void)_cleanupRemoteUILoader;
- (void)_displayConnectionErrorAndCancel;
- (void)_startRemoteUILoaderWithRequest:(id)arg1;
- (void)_addHeadersToRequest:(id)arg1;
- (id)initWithGrandSlamSigner:(id)arg1;
- (void)setNavigationController:(id)arg1;
- (void)_cancel;
- (void).cxx_destruct;
- (id)navigationController;
- (id)delegate;
- (void)setDelegate:(id)arg1;

@end
