/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppleAccountUI.framework/AppleAccountUI
 */

@class RUILoader, UIAlertView, NSMutableArray, ACAccountStore, <AAUIAccountRepairRemoteUIDelegate>, ACAccount, UIViewController, UINavigationController, NSString;

@interface AAUIAccountRepairRemoteUI : NSObject <RUIObjectModelDelegate> {
    UINavigationController *_parentNavController;
    UIViewController *_originatingViewController;
    UINavigationController *_accountRepairUIViewController;
    RUILoader *_loader;
    NSMutableArray *_objectModels;
    ACAccount *_account;
    ACAccountStore *_accountStore;
    BOOL _isModal;
    UIAlertView *_tcConfirmationAlert;
    NSString *_agreeURL;
    <AAUIAccountRepairRemoteUIDelegate> *_delegate;
}

@property <AAUIAccountRepairRemoteUIDelegate> * delegate;


- (void)objectModel:(id)arg1 pressedButton:(id)arg2 attributes:(id)arg3;
- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3;
- (void)objectModelPressedBack:(id)arg1;
- (unsigned int)supportedInterfaceOrientationsForObjectModel:(id)arg1 page:(id)arg2;
- (id)parentViewControllerForObjectModel:(id)arg1;
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 actionSignal:(int)arg3;
- (void)loader:(id)arg1 didFailWithError:(id)arg2;
- (void)_popObjectModelAnimated:(BOOL)arg1;
- (void)presentFromViewController:(id)arg1 modal:(BOOL)arg2;
- (id)initWithAccount:(id)arg1 inStore:(id)arg2;
- (void)_cleanupRUILoader;
- (void)_cleanUpAndDismissWithSuccess:(BOOL)arg1;
- (void)_displayConnectionErrorAndDismiss;
- (void)_addHeadersToRequest:(id)arg1;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (id)delegate;
- (void)_cancelButtonTapped:(id)arg1;
- (void)setDelegate:(id)arg1;

@end
