/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class NSURL, NSString;

@interface ABContactPhotoPreviewItem : NSObject <QLPreviewItem> {
    NSURL *_previewItemURL;
    NSString *_previewItemTitle;
}

@property(retain) NSURL * previewItemURL;
@property(retain) NSString * previewItemTitle;


- (void)setPreviewItemTitle:(id)arg1;
- (id)previewItemTitle;
- (void)setPreviewItemURL:(id)arg1;
- (id)previewItemURL;

@end
