/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class NSArray, ABUIPerson;

@interface ABPropertyPickerViewController : ABPickerViewController <ABCardPropertyPickerDelegate> {
    void *_addressBook;
    ABUIPerson *_person;
    struct __CFArray { } *_properties;
    NSArray *_policies;
}

@property void* addressBook;
@property(retain) ABUIPerson * person;
@property struct __CFArray { }* properties;
@property(retain) NSArray * policies;


- (void*)addressBook;
- (id)policies;
- (void)setPerson:(id)arg1;
- (id)person;
- (void)setProperties:(struct __CFArray { }*)arg1;
- (struct __CFArray { }*)properties;
- (void)_getRotationContentSettings:(struct { BOOL x1; BOOL x2; BOOL x3; BOOL x4; float x5; int x6; }*)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setAddressBook:(void*)arg1;
- (void)dealloc;
- (id)propertyPicker;
- (void)setPolicies:(id)arg1;
- (float)ab_heightToFitForViewInPopoverView;
- (void)propertyPicker:(id)arg1 selectedProperty:(int)arg2 withDefaultValue:(id)arg3;
- (void)propertyPicker:(id)arg1 selectedProperty:(int)arg2;

@end
