/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@class NSObject<OS_dispatch_queue>;

@interface AFPreferences : NSObject  {
    BOOL _registeredForInternalPrefs;
    BOOL _registeredForLanguageCode;
    BOOL _registeredForOutputVoice;
    NSObject<OS_dispatch_queue> *_navTokenQueue;
    BOOL _navTokenIsValid;
    int _navToken;
}

+ (id)sharedPreferences;

- (void)setFileLoggingIsEnabled:(BOOL)arg1;
- (BOOL)fileLoggingIsEnabled;
- (BOOL)assistantIsEnabled;
- (BOOL)streamingDictationEnabled;
- (void)synchronizeVoiceServicesLanguageCode;
- (void)setOutputVoice:(id)arg1;
- (id)outputVoice;
- (BOOL)debugButtonIsEnabled;
- (id)languagesMissingBirthCertificates;
- (void)setValue:(id)arg1 forSessionContextKey:(id)arg2;
- (id)valueForSessionContextPreferenceKey:(id)arg1;
- (void)setShouldShowReadyForLanguageCode:(id)arg1;
- (void)didShowReadyForLanguageCode:(id)arg1;
- (BOOL)shouldShowReadyForLanguageCode:(id)arg1;
- (void)setDisableAssistantWhilePasscodeLocked:(BOOL)arg1;
- (BOOL)disableAssistantWhilePasscodeLocked;
- (void)setStreamingDictationEnabled:(BOOL)arg1;
- (void)setManualEndpointingThreshold:(id)arg1;
- (void)setIgnoreServerManualEndpointingThreshold:(BOOL)arg1;
- (void)setHandsFreeMode:(int)arg1;
- (int)handsFreeMode;
- (void)setDebugButtonIsEnabled:(BOOL)arg1;
- (void)setBugReportingMode:(int)arg1;
- (int)bugReportingMode;
- (void)setDictationIsEnabled:(BOOL)arg1;
- (void)setAssistantIsEnabled:(BOOL)arg1;
- (void)_setDictationIsEnabledLocal:(BOOL)arg1;
- (void)_setAssistantIsEnabledLocal:(BOOL)arg1;
- (void)_ouputVoiceDidChangeExternally;
- (void)_languageCodeDidChangeExternally;
- (void)_internalPreferencesDidChangeExternally;
- (void)_preferencesDidChangeExternally;
- (void)_setLoggingDefaultValue:(id)arg1 forKey:(id)arg2;
- (id)whitelistedLanguages;
- (void)setBirthCertificateData:(id)arg1 forLanguageCode:(id)arg2;
- (void)_registerForNavStatusIfNeeded;
- (void)_registerForOutputVoice;
- (void)_registerForLanguageCode;
- (void)_registerForInteralPrefs;
- (id)birthCertificateDataForLanguageCode:(id)arg1;
- (id)languageCode;
- (BOOL)dictationIsEnabled;
- (id)manualEndpointingThreshold;
- (BOOL)ignoreServerManualEndpointingThreshold;
- (void).cxx_destruct;
- (void)synchronize;
- (void)dealloc;
- (id)init;
- (void)setLanguageCode:(id)arg1;

@end
