/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AOSNotification.framework/AOSNotification
 */

@class CPDistributedNotificationCenter, NSXPCConnection;

@interface AOSNotifySession : NSObject  {
    NSXPCConnection *_xpcConnection;
    CPDistributedNotificationCenter *_center;
}

@property(retain) NSXPCConnection * xpcConnection;
@property(retain) CPDistributedNotificationCenter * center;

+ (id)copyStoreAccount;
+ (id)sharedInstance;

- (id)storeAccount;
- (void)setXpcConnection:(id)arg1;
- (id)xpcConnection;
- (id)enableLostModeWithInfo:(id)arg1;
- (id)serverProxy;
- (void)isActivationLockStateChangeInProgressWithCompletion:(id)arg1;
- (id)fmipAccount;
- (id)fmipDeviceId;
- (void)isFMIPStateChangeInProgressWithCompletion:(id)arg1;
- (BOOL)lockdownShouldDisableDevicePairing;
- (BOOL)lockdownShouldDisableDeviceRestore;
- (void)deviceActivationDidSucceed;
- (void)disableLostMode;
- (id)lostModeInfo;
- (id)newErrorForCode:(int)arg1 message:(id)arg2;
- (id)currentXPCConnection;
- (void)_destroyXPCConnection;
- (id)disableActivationLockUsingToken:(id)arg1;
- (id)enableActivationLock;
- (void)activationLockStateWithCompletion:(id)arg1;
- (id)disableFMIPUsingToken:(id)arg1 inContext:(unsigned int)arg2;
- (id)enableFMIPInContext:(unsigned int)arg1;
- (void)fmipStateWithCompletion:(id)arg1;
- (id)retrieveAllAccounts:(id*)arg1;
- (void)dumpDebugInfo:(id)arg1;
- (void)stopListeningOnTopic:(id)arg1;
- (void)startListeningOnTopic:(id)arg1;
- (id)retrieveFMFAccount:(id*)arg1;
- (id)removeFMFAccountWithUsername:(id)arg1;
- (id)addFMFAccount:(id)arg1;
- (void)didExitFMFRegion:(id)arg1 atLocation:(id)arg2;
- (void)didEnterFMFRegion:(id)arg1 atLocation:(id)arg2;
- (id)iCloudAccount;
- (id)fmfDeviceId;
- (id)lostModeParams;
- (void)renewFMFAccountCredentialsUsingCallback:(id)arg1;
- (void)retrieveFMFAccountUsingCallback:(id)arg1;
- (void)removeLegacyFMFAccountUsingCallback:(id)arg1;
- (void)retrieveLegacyFMFAccountUsingCallback:(id)arg1;
- (void).cxx_destruct;
- (void)setCenter:(id)arg1;
- (id)center;
- (void)dealloc;
- (id)init;
- (BOOL)lostModeIsActive;
- (BOOL)performMigration;

@end
