/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ATFoundation.framework/ATFoundation
 */

@class NSXPCListener;

@interface ATStatusObserverListener : NSObject <NSXPCListenerDelegate> {
    NSXPCListener *_listener;
}


- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void).cxx_destruct;
- (void)start;
- (void)stop;

@end
