/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSArray, AVAssetInternal;

@interface AVAsset : NSObject <NSCopying, AVAsynchronousKeyValueLoading> {
    AVAssetInternal *_asset;
}

@property(readonly) struct CGSize { float x1; float x2; } naturalSizeWithPreferredTransforms;
@property(getter=MP_canAffectNetworkPlayability,setter=MP_setCanAffectNetworkPlayability:) BOOL MP_canAffectNetworkPlayability;
@property(readonly) NSArray * availableChapterLocales;
@property(readonly) id propertyListForProxy;
@property(readonly) BOOL isProxy;
@property(readonly) struct { long long x1; int x2; unsigned int x3; long long x4; } duration;
@property(readonly) float preferredRate;
@property(readonly) float preferredVolume;
@property(readonly) struct CGAffineTransform { float x1; float x2; float x3; float x4; float x5; float x6; } preferredTransform;
@property(readonly) struct CGSize { float x1; float x2; } naturalSize;

+ (id)assetWithURL:(id)arg1;
+ (id)assetProxyWithPropertyList:(id)arg1;
+ (id)assetWithURL:(id)arg1 figPlaybackItem:(struct OpaqueFigPlaybackItem { }*)arg2 trackIDs:(id)arg3 dynamicBehavior:(BOOL)arg4;
+ (id)keyPathsForValuesAffectingNaturalSizeWithPreferredTransforms;

- (id)tracks;
- (id)tracksWithMediaType:(id)arg1;
- (id)mediaSelectionGroupForMediaCharacteristic:(id)arg1;
- (id)tracksWithMediaCharacteristic:(id)arg1;
- (int)statusOfValueForKey:(id)arg1 error:(id*)arg2;
- (void)loadValuesAsynchronouslyForKeys:(id)arg1 completionHandler:(id)arg2;
- (void)cancelLoading;
- (id)commonMetadata;
- (struct CGAffineTransform { float x1; float x2; float x3; float x4; float x5; float x6; })preferredTransform;
- (BOOL)isCompatibleWithSavedPhotosAlbum;
- (id)creationDate;
- (id)chapterMetadataGroupsWithTitleLocale:(id)arg1 containingItemsWithCommonKeys:(id)arg2;
- (id)availableChapterLocales;
- (BOOL)hasProtectedContent;
- (id)lyrics;
- (id)metadata;
- (struct CGSize { float x1; float x2; })naturalSize;
- (id)valueForUndefinedKey:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)isProxy;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (struct { long long x1; int x2; unsigned int x3; long long x4; })duration;
- (void)dealloc;
- (id)init;
- (id)_exportURL;
- (BOOL)_containsAtLeastOnePlayableVideoTrack;
- (BOOL)_containsAtLeastOnePlayableAudioTrack;
- (id)_chapterTracks;
- (id)propertyListForProxy;
- (int)unusedTrackID;
- (id)chapterMetadataGroupsBestMatchingPreferredLanguages:(id)arg1;
- (id)_chapterMetadataGroupsWithFigChapterGroups:(id)arg1 titleLocale:(id)arg2 containingItemsWithCommonKeys:(id)arg3;
- (unsigned int)_addChapterMetadataItem:(id)arg1 timeRange:(struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })arg2 toChapters:(id)arg3 fromIndex:(unsigned int)arg4;
- (id)_chapterDataTypeForMediaSubType:(long)arg1;
- (void)_loadChapterInfo;
- (BOOL)_hasResourceLoaderDelegate;
- (id)compatibleTrackForCompositionTrack:(id)arg1;
- (void)_tracksDidChange;
- (id)_ID3Metadata;
- (id)mediaSelectionGroupForPropertyList:(id)arg1 mediaSelectionOption:(id*)arg2;
- (id)availableMediaCharacteristicsWithMediaSelectionOptions;
- (id)subtitleAlternatesTrackGroup;
- (id)audioAlternatesTrackGroup;
- (unsigned int)referenceRestrictions;
- (struct OpaqueFigMutableComposition { }*)_mutableComposition;
- (id)_absoluteURL;
- (Class)_classForTrackInspectors;
- (struct OpaqueFigFormatReader { }*)_formatReader;
- (int)statusOfValueForKey:(id)arg1;
- (id)_comparisonToken;
- (id)_weakReference;
- (BOOL)canContainMovieFragments;
- (BOOL)isComposable;
- (BOOL)isReadable;
- (BOOL)isExportable;
- (BOOL)isPlayable;
- (void)_serverHasDied;
- (id)tracksWithMediaCharacteristics:(id)arg1;
- (id)metadataForFormat:(id)arg1;
- (id)availableMetadataFormats;
- (id)trackReferences;
- (id)mediaSelectionGroups;
- (id)_firstTrackGroupWithMediaType:(id)arg1;
- (id)trackWithTrackID:(int)arg1;
- (id)trackGroups;
- (id)alternateTrackGroups;
- (BOOL)providesPreciseDurationAndTiming;
- (int)naturalTimeScale;
- (float)preferredSoundCheckVolumeNormalization;
- (float)preferredVolume;
- (float)preferredRate;
- (struct OpaqueFigPlaybackItem { }*)_playbackItem;
- (void)loadValuesAsynchronouslyForKeys:(id)arg1 keysForCollectionKeys:(id)arg2 completionHandler:(id)arg3;
- (BOOL)_isStreaming;
- (id)_assetInspector;
- (id)_assetInspectorLoader;
- (struct OpaqueFigAsset { }*)_figAsset;
- (void)mpLoadValuesAsynchronouslyForKeys:(id)arg1 completionQueue:(id)arg2 completionHandler:(id)arg3;
- (void)MP_setCanAffectNetworkPlayability:(BOOL)arg1;
- (BOOL)MP_canAffectNetworkPlayability;
- (struct CGSize { float x1; float x2; })naturalSizeWithPreferredTransforms;

@end
