/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVAssetCache, NSArray, AVAssetInspectorLoader, NSObject<OS_dispatch_queue>, AVAssetResourceLoader, NSURL;

@interface AVURLAssetInternal : NSObject  {
    AVAssetInspectorLoader *loader;
    NSURL *URL;
    NSArray *tracks;
    AVAssetResourceLoader *resourceLoader;
    long makeOneResourceLoaderOnly;
    NSObject<OS_dispatch_queue> *tracksAccessQueue;
    AVAssetCache *assetCache;
    BOOL shouldMatchDataInCacheByURLPathComponentOnly;
    BOOL shouldMatchDataInCacheByURLWithoutQueryComponent;
    BOOL shouldOptimizeAccessForLinearMoviePlayback;
    NSURL *downloadDestinationURL;
    unsigned int referenceRestrictions;
}



@end
