/* Generated by RuntimeBrowser.
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@class NSString;

@interface AWDAirPlaySlideshowSessionStartedOnClient : PBCodable <NSCopying> {
    unsigned long long _timestamp;
    unsigned int _repeat;
    NSString *_sessionUUID;
    unsigned int _slideMs;
    int _status;
    NSString *_theme;
    NSString *_transition;
    struct { 
        unsigned int timestamp : 1; 
        unsigned int repeat : 1; 
        unsigned int slideMs : 1; 
        unsigned int status : 1; 
    } _has;
}

@property(readonly) BOOL hasSessionUUID;
@property(retain) NSString * sessionUUID;
@property BOOL hasTimestamp;
@property unsigned long long timestamp;
@property BOOL hasStatus;
@property int status;
@property(readonly) BOOL hasTheme;
@property(retain) NSString * theme;
@property(readonly) BOOL hasTransition;
@property(retain) NSString * transition;
@property BOOL hasRepeat;
@property unsigned int repeat;
@property BOOL hasSlideMs;
@property unsigned int slideMs;


- (unsigned int)slideMs;
- (unsigned int)repeat;
- (BOOL)hasSlideMs;
- (void)setHasSlideMs:(BOOL)arg1;
- (void)setSlideMs:(unsigned int)arg1;
- (BOOL)hasRepeat;
- (void)setHasRepeat:(BOOL)arg1;
- (void)setRepeat:(unsigned int)arg1;
- (BOOL)hasTransition;
- (BOOL)hasTheme;
- (id)sessionUUID;
- (BOOL)hasSessionUUID;
- (void)setSessionUUID:(id)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)setTheme:(id)arg1;
- (id)theme;
- (void)setHasTimestamp:(BOOL)arg1;
- (BOOL)hasStatus;
- (void)setHasStatus:(BOOL)arg1;
- (BOOL)hasTimestamp;
- (void)setStatus:(int)arg1;
- (int)status;
- (id)dictionaryRepresentation;
- (id)transition;
- (void)setTransition:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned long long)timestamp;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;

@end
