/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@class NSCharacterSet, NSArray, NSLocale, AXDialectMap, NSString;

@interface AXLanguageManager : NSObject  {
    AXDialectMap *_dialectForSystemLanguage;
    AXDialectMap *_dialectForCurrentLocale;
    NSArray *_langMaps;
    NSCharacterSet *_commonCharacters;
    NSLocale *_userLocale;
}

@property(retain) NSArray * langMaps;
@property(readonly) NSString * systemLanguageID;
@property(copy) NSLocale * userLocale;
@property(retain) NSCharacterSet * commonCharacters;
@property AXDialectMap * dialectForSystemLanguage;
@property AXDialectMap * dialectForCurrentLocale;

+ (id)dialectForAlternativeVoiceIdentifier:(id)arg1;
+ (id)nameForAlternativeVoiceIdentifier:(id)arg1;
+ (BOOL)isDialectIdentifierAlternativeVoice:(id)arg1;
+ (id)commonPunctuationCharacters;
+ (id)nonlocalizedNameForLanguage:(id)arg1;
+ (id)stringByReplacingFatWidthCharactersWithBasicCharacters:(id)arg1;
+ (id)sharedInstance;
+ (id)stringByReplacingEmojiCharactersWithEmojiDescriptions:(id)arg1;

- (id)ambiguousDialectsFromUserKeyboardPreferences;
- (id)dialectThatCanSpeakCharacter:(unsigned short)arg1;
- (id)characterSetForRanges:(id)arg1;
- (id)systemLanguageID;
- (id)commonCharacters;
- (id)_preferredLanguageIDsFromUserSelectedKeyboards;
- (id)dialectsThatCanSpeakCharacter:(unsigned short)arg1;
- (void)updateCachedDialects;
- (id)dialectForCurrentLocale;
- (id)langMaps;
- (void)setDialectForCurrentLocale:(id)arg1;
- (void)setDialectForSystemLanguage:(id)arg1;
- (void)setLangMaps:(id)arg1;
- (id)_loadLangMaps;
- (void)setCommonCharacters:(id)arg1;
- (void)_handleUserLocaleDidChange:(id)arg1;
- (void)setUserLocale:(id)arg1;
- (BOOL)isCharacterCommon:(unsigned short)arg1;
- (id)userLocale;
- (id)basicDescription;
- (id)dialectForLanguageID:(id)arg1;
- (id)dialectForSystemLanguage;
- (id)debugDescription;
- (id)description;
- (void)dealloc;
- (id)init;
- (id)descriptionOfWord:(id)arg1 forLanguage:(id)arg2;

@end
