/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@class BKSSystemApplicationClient, <BKSSystemApplicationDelegate>, NSObject<OS_dispatch_queue>;

@interface BKSSystemApplication : NSObject <BKSSystemApplicationClientDelegate> {
    NSObject<OS_dispatch_queue> *_queue;
    BKSSystemApplicationClient *_client;
    <BKSSystemApplicationDelegate> *_delegate;
}

@property <BKSSystemApplicationDelegate> * delegate;


- (BOOL)clientIsAliveForWatchdog:(id)arg1;
- (id)initWithQueue:(id)arg1;
- (id)delegate;
- (void)restart;
- (void)start;
- (void)dealloc;
- (void)setDelegate:(id)arg1;

@end
