/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSDictionary;

@interface BRCCloudDocsAppsMonitor : NSObject  {
    NSDictionary *_cloudDocsContainersByAppID;
    NSDictionary *_appIDsByContainerID;
    NSMutableSet *_observers;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_callbackQueue;
}

+ (id)cloudDocsAppsMonitor;

- (void)_refetchApps;
- (id)applicationIdentifiersForContainerID:(id)arg1;
- (void)addObserver:(id)arg1;
- (void).cxx_destruct;
- (void)_start;
- (void)removeObserver:(id)arg1;
- (id)init;

@end
