/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@class BRCDatabaseManager;

@interface BRCClientRanksPersistedState : NSObject <NSSecureCoding> {
    BRCDatabaseManager *_dbManager;
    unsigned long long _nextItemRowID;
    unsigned long long _nextSyncDownRank;
    unsigned long long _nextNotifRank;
    unsigned long long _nextPackageItemRank;
}

@property(readonly) unsigned long long nextItemRowID;
@property unsigned long long nextNotifRank;
@property unsigned long long nextSyncDownRank;
@property unsigned long long nextPackageItemRank;

+ (id)loadFromClientStateInDBManager:(id)arg1;
+ (BOOL)supportsSecureCoding;

- (void)setNextPackageItemRank:(unsigned long long)arg1;
- (unsigned long long)allocatePackageItemRank;
- (unsigned long long)nextPackageItemRank;
- (void)setNextNotifRank:(unsigned long long)arg1;
- (unsigned long long)nextItemRowID;
- (void)setNextSyncDownRank:(unsigned long long)arg1;
- (unsigned long long)nextSyncDownRank;
- (unsigned long long)allocateNotifRank;
- (unsigned long long)allocateItemRowID;
- (unsigned long long)nextNotifRank;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)init;

@end
