/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@class NSMutableArray;

@interface BRFieldXattrBlob : PBCodable <NSCopying> {
    NSMutableArray *_xattrs;
}

@property(retain) NSMutableArray * xattrs;

+ (BOOL)removeXattrsOnFD:(int)arg1 includingContentRelated:(BOOL)arg2 error:(id*)arg3;
+ (BOOL)loadXattrsFromFD:(int)arg1 structuralBlob:(id*)arg2 contentBlob:(id*)arg3 withMaximumSize:(unsigned int)arg4 error:(id*)arg5;

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)xattrs;
- (id)xattrsAtIndex:(unsigned int)arg1;
- (void)clearXattrs;
- (unsigned int)xattrsCount;
- (void)addXattrs:(id)arg1;
- (void)setXattrs:(id)arg1;
- (BOOL)applyToFileDescriptor:(int)arg1 error:(id*)arg2;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;

@end
