/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
 */

@class CAKeyframeAnimation;

@interface CAMFocusLockView : CAMFocusView  {
    CAKeyframeAnimation *_lockBoundsAnimation;
}


- (void)animateScaleDownWithCompletion:(id)arg1;
- (void)animateLock;
- (id)_createLockBoundsAnimation;
- (id)_createBoundsAnimation;
- (void)startAnimatingContents:(BOOL)arg1 bounds:(BOOL)arg2 fadeIn:(BOOL)arg3;
- (double)fadeInDuration;
- (void).cxx_destruct;

@end
