/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class CHDAxesCollection, OADGraphicProperties, CHDChartTypesCollection;

@interface CHDPlotArea : NSObject  {
    CHDChartTypesCollection *mChartTypes;
    CHDAxesCollection *mAxes;
    OADGraphicProperties *mGraphicProperties;
    boolmCategoryAxesReversed;
    boolmCategoryAxesReversedOverridden;
    boolmContainsVolumeStockType;
}


- (void)setContainsVolumeStockType:(bool)arg1;
- (bool)isCategoryAxesReversed:(bool)arg1;
- (bool)containsVolumeStockType;
- (void)markSecondaryAxes;
- (bool)hasSecondaryYAxisDeleted;
- (bool)hasSecondaryAxis;
- (id)chartTypes;
- (void)setGraphicProperties:(id)arg1;
- (id)initWithChart:(id)arg1;
- (id)axes;
- (id)graphicProperties;
- (void)dealloc;

@end
