/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDPieSeries : CHDSeries  {
    int mExplosion;
}


- (void)setExplosion:(int)arg1;
- (id)shallowCopy;
- (int)explosion;
- (id)init;

@end
