/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@class CHDrawing;

@interface CHPointStrokeFIFO : CHPointFIFO  {
    CHDrawing *_strokes;
}

@property(retain) CHDrawing * strokes;


- (void)setStrokes:(id)arg1;
- (id)strokes;
- (id)initWithFIFO:(id)arg1;
- (void)addPoint:(struct CGPoint { float x1; float x2; })arg1;
- (void)clear;
- (void)flush;
- (void)dealloc;

@end
