/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@class CKSharedItemID, CKShareID, NSString;

@interface CKCommentNotification : CKNotification <NSSecureCoding> {
    CKShareID *_shareID;
    NSString *_commentID;
    CKSharedItemID *_commentedItemID;
    NSString *_commenterID;
    NSString *_message;
}

@property(copy) CKShareID * shareID;
@property(copy) NSString * commentID;
@property(copy) CKSharedItemID * commentedItemID;
@property(copy) NSString * commenterID;
@property(copy) NSString * message;

+ (BOOL)supportsSecureCoding;

- (id)commenterID;
- (id)commentID;
- (void)setCommentedItemID:(id)arg1;
- (void)setCommenterID:(id)arg1;
- (void)setCommentID:(id)arg1;
- (id)commentedItemID;
- (void)setShareID:(id)arg1;
- (id)shareID;
- (id)CKPropertiesDescription;
- (void).cxx_destruct;
- (void)setMessage:(id)arg1;
- (id)message;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)initWithRemoteNotificationDictionary:(id)arg1;

@end
