/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@class NSOperationQueue, CKContainer;

@interface CKDatabase : NSObject  {
    CKContainer *_container;
    int _scope;
    NSOperationQueue *_operationQueue;
    int _statusReportToken;
}

@property(retain) CKContainer * container;
@property int scope;
@property(readonly) NSOperationQueue * operationQueue;
@property int statusReportToken;


- (void)setScope:(int)arg1;
- (int)scope;
- (id)CKPropertiesDescription;
- (void)clearRecordCache;
- (void)getPCSDiagnosticsForZonesWithCompletionHandler:(id)arg1;
- (void)deallocateAssetHandleWithUUID:(id)arg1;
- (void)allocateSaveAssetHandleWithUUID:(id)arg1 fileURL:(id)arg2 removeWhenDone:(BOOL)arg3;
- (id)statusReport;
- (id)operationQueue;
- (void).cxx_destruct;
- (void)addOperation:(id)arg1;
- (id)container;
- (void)setContainer:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)init;
- (void)fetchAllSubscriptionsWithCompletionHandler:(id)arg1;
- (void)fetchSubscriptionWithID:(id)arg1 completionHandler:(id)arg2;
- (void)deleteSubscriptionWithID:(id)arg1 completionHandler:(id)arg2;
- (void)saveSubscription:(id)arg1 completionHandler:(id)arg2;
- (void)deleteRecordZoneWithID:(id)arg1 completionHandler:(id)arg2;
- (void)saveRecordZone:(id)arg1 completionHandler:(id)arg2;
- (void)fetchRecordZoneWithID:(id)arg1 completionHandler:(id)arg2;
- (void)fetchAllRecordZonesWithCompletionHandler:(id)arg1;
- (void)performQuery:(id)arg1 inZoneWithID:(id)arg2 completionHandler:(id)arg3;
- (void)deleteRecordWithID:(id)arg1 completionHandler:(id)arg2;
- (void)saveRecord:(id)arg1 completionHandler:(id)arg2;
- (void)fetchRecordWithID:(id)arg1 completionHandler:(id)arg2;
- (void)_scheduleOperation:(id)arg1;
- (void)clearAuthTokensForRecordWithID:(id)arg1;
- (void)clearAssetCache;
- (void)setStatusReportToken:(int)arg1;
- (int)statusReportToken;
- (id)daemonWithErrorHandler:(id)arg1;
- (id)_initWithContainer:(id)arg1 scope:(int)arg2;

@end
