/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@class NSData;

@interface CKDMescalSessionURLRequest : CKDURLRequest  {
    NSData *_mescalData;
    NSData *_sessionData;
}

@property(retain) NSData * mescalData;
@property(retain) NSData * sessionData;


- (void)setSessionData:(id)arg1;
- (void)setMescalData:(id)arg1;
- (id)sessionData;
- (void)_handleParsedObject:(id)arg1;
- (id)requestBodyStream;
- (id)responseBodyParser;
- (BOOL)requiresDeviceID;
- (BOOL)requiresSignature;
- (int)partitionType;
- (int)serverType;
- (id)mescalData;
- (id)initWithSessionData:(id)arg1;
- (void).cxx_destruct;
- (id)url;

@end
