/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@class CKDPLikeInfo, NSString, CKDPIdentifier, CKDPDate, CKDPCommentContent;

@interface CKDPComment : PBCodable <NSCopying> {
    CKDPCommentContent *_commentContent;
    CKDPIdentifier *_commentId;
    CKDPDate *_createdAt;
    CKDPIdentifier *_from;
    CKDPLikeInfo *_likeInfo;
    NSString *_path;
}

@property(readonly) BOOL hasCommentId;
@property(retain) CKDPIdentifier * commentId;
@property(readonly) BOOL hasPath;
@property(retain) NSString * path;
@property(readonly) BOOL hasCreatedAt;
@property(retain) CKDPDate * createdAt;
@property(readonly) BOOL hasFrom;
@property(retain) CKDPIdentifier * from;
@property(readonly) BOOL hasCommentContent;
@property(retain) CKDPCommentContent * commentContent;
@property(readonly) BOOL hasLikeInfo;
@property(retain) CKDPLikeInfo * likeInfo;


- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (BOOL)hasFrom;
- (id)likeInfo;
- (BOOL)hasLikeInfo;
- (void)setLikeInfo:(id)arg1;
- (void)setFrom:(id)arg1;
- (id)from;
- (id)createdAt;
- (BOOL)hasCreatedAt;
- (void)setCreatedAt:(id)arg1;
- (id)commentContent;
- (BOOL)hasCommentContent;
- (void)setCommentContent:(id)arg1;
- (id)commentId;
- (BOOL)hasCommentId;
- (void)setCommentId:(id)arg1;
- (BOOL)hasPath;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)setPath:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)path;
- (id)description;

@end
