/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@class NSString, NSData, CKDPProtectionInfo, CKDPRecordIdentifier;

@interface CKDPAsset : PBCodable <NSCopying> {
    long long _downloadURLExpiration;
    long long _size;
    NSString *_contentBaseURL;
    NSData *_data;
    NSString *_derivedContentType;
    NSString *_downloadBaseURL;
    NSData *_downloadRequest;
    NSString *_downloadToken;
    NSData *_header;
    NSString *_owner;
    CKDPProtectionInfo *_protectionInfo;
    CKDPRecordIdentifier *_recordId;
    NSString *_referenceIdentifier;
    NSData *_referenceSignature;
    NSString *_requestor;
    NSData *_signature;
    NSString *_uploadReceipt;
    struct { 
        unsigned int downloadURLExpiration : 1; 
        unsigned int size : 1; 
    } _has;
}

@property(readonly) BOOL hasOwner;
@property(retain) NSString * owner;
@property(readonly) BOOL hasSignature;
@property(retain) NSData * signature;
@property(readonly) BOOL hasHeader;
@property(retain) NSData * header;
@property BOOL hasSize;
@property long long size;
@property(readonly) BOOL hasDownloadToken;
@property(retain) NSString * downloadToken;
@property(readonly) BOOL hasDownloadRequest;
@property(retain) NSData * downloadRequest;
@property(readonly) BOOL hasDerivedContentType;
@property(retain) NSString * derivedContentType;
@property(readonly) BOOL hasContentBaseURL;
@property(retain) NSString * contentBaseURL;
@property(readonly) BOOL hasRequestor;
@property(retain) NSString * requestor;
@property(readonly) BOOL hasRecordId;
@property(retain) CKDPRecordIdentifier * recordId;
@property(readonly) BOOL hasUploadReceipt;
@property(retain) NSString * uploadReceipt;
@property(readonly) BOOL hasData;
@property(retain) NSData * data;
@property(readonly) BOOL hasDownloadBaseURL;
@property(retain) NSString * downloadBaseURL;
@property BOOL hasDownloadURLExpiration;
@property long long downloadURLExpiration;
@property(readonly) BOOL hasProtectionInfo;
@property(retain) CKDPProtectionInfo * protectionInfo;
@property(readonly) BOOL hasReferenceIdentifier;
@property(retain) NSString * referenceIdentifier;
@property(readonly) BOOL hasReferenceSignature;
@property(retain) NSData * referenceSignature;


- (void)setOwner:(id)arg1;
- (BOOL)hasSize;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)setHeader:(id)arg1;
- (id)header;
- (id)referenceIdentifier;
- (id)recordId;
- (id)derivedContentType;
- (id)downloadRequest;
- (BOOL)hasReferenceSignature;
- (BOOL)hasReferenceIdentifier;
- (BOOL)hasDownloadURLExpiration;
- (void)setHasDownloadURLExpiration:(BOOL)arg1;
- (void)setDownloadURLExpiration:(long long)arg1;
- (BOOL)hasDownloadBaseURL;
- (BOOL)hasData;
- (BOOL)hasUploadReceipt;
- (BOOL)hasRecordId;
- (BOOL)hasRequestor;
- (BOOL)hasContentBaseURL;
- (BOOL)hasDerivedContentType;
- (BOOL)hasDownloadRequest;
- (BOOL)hasDownloadToken;
- (void)setDownloadBaseURL:(id)arg1;
- (void)setDerivedContentType:(id)arg1;
- (void)setDownloadRequest:(id)arg1;
- (void)setDownloadToken:(id)arg1;
- (BOOL)hasOwner;
- (void)setReferenceIdentifier:(id)arg1;
- (void)setRecordId:(id)arg1;
- (void)setReferenceSignature:(id)arg1;
- (void)setRequestor:(id)arg1;
- (void)setContentBaseURL:(id)arg1;
- (id)requestor;
- (id)contentBaseURL;
- (id)referenceSignature;
- (BOOL)hasHeader;
- (id)downloadBaseURL;
- (void)setUploadReceipt:(id)arg1;
- (id)uploadReceipt;
- (id)protectionInfo;
- (BOOL)hasProtectionInfo;
- (void)setProtectionInfo:(id)arg1;
- (long long)downloadURLExpiration;
- (void)setHasSize:(BOOL)arg1;
- (id)signature;
- (BOOL)hasSignature;
- (void)setSignature:(id)arg1;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)setSize:(long long)arg1;
- (void)setData:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (long long)size;
- (id)owner;
- (id)data;
- (id)description;
- (id)downloadToken;

@end
