/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@class NSArray, CKQuery, NSData, NSMutableArray, CKRecordZoneID;

@interface CKDQueryURLRequest : CKDURLRequest  {
    NSMutableArray *_queryResponses;
    CKQuery *_query;
    NSData *_cursor;
    unsigned int _limit;
    CKRecordZoneID *_zoneID;
    NSArray *_requestedFields;
    NSData *_resultsCursor;
}

@property(retain) CKQuery * query;
@property(retain) NSData * cursor;
@property unsigned int limit;
@property(retain) CKRecordZoneID * zoneID;
@property(retain) NSArray * requestedFields;
@property(retain) NSArray * queryResponses;
@property(retain) NSData * resultsCursor;


- (int)operationType;
- (void)setQueryResponses:(id)arg1;
- (unsigned int)limit;
- (void)setLimit:(unsigned int)arg1;
- (BOOL)allowsAnonymousAccount;
- (id)requestOperationClasses;
- (int)partitionType;
- (int)serverType;
- (void)requestDidParseNodeFailure:(id)arg1;
- (void)requestDidParseProtobufObject:(id)arg1;
- (id)requestOperations;
- (void)setZoneID:(id)arg1;
- (id)initWithQuery:(id)arg1 cursor:(id)arg2 limit:(unsigned int)arg3 requestedFields:(id)arg4 zoneID:(id)arg5;
- (void)setResultsCursor:(id)arg1;
- (id)resultsCursor;
- (id)queryResponses;
- (id)requestedFields;
- (void)setRequestedFields:(id)arg1;
- (id)zoneID;
- (void).cxx_destruct;
- (void)setCursor:(id)arg1;
- (id)cursor;
- (void)setQuery:(id)arg1;
- (id)query;

@end
