/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@class NSArray, NSString, NSDate, CKIMComposeRecipient;

@interface CKIMGroupComposeRecipient : MFComposeRecipient  {
    NSString *_conversationGUID;
    NSArray *_composeRecipients;
    NSArray *_handles;
    NSDate *_lastMessageDate;
    CKIMComposeRecipient *_matchingRecipient;
    NSString *_displayString;
    NSString *_detailsString;
}

@property(retain) NSString * conversationGUID;
@property(retain) NSArray * composeRecipients;
@property(retain) NSArray * handles;
@property(retain) NSDate * lastMessageDate;
@property(retain) CKIMComposeRecipient * matchingRecipient;
@property(retain) NSString * displayString;
@property(retain) NSString * detailsString;

+ (id)composeRecipientWithConversation:(id)arg1 searchTerm:(id)arg2 matchingRecipient:(id)arg3;

- (id)address;
- (id)matchingRecipient;
- (void)setComposeRecipients:(id)arg1;
- (id)detailsString;
- (void)setMatchingRecipient:(id)arg1;
- (void)setLastMessageDate:(id)arg1;
- (void)setHandles:(id)arg1;
- (void)setDetailsString:(id)arg1;
- (void)setConversationGUID:(id)arg1;
- (id)initWithGUID:(id)arg1 displayString:(id)arg2 detailsString:(id)arg3 handles:(id)arg4 lastMessageDate:(id)arg5 searchTerm:(id)arg6 matchingRecipient:(id)arg7;
- (id)conversationGUID;
- (id)lastMessageDate;
- (id)compositeName;
- (id)composeRecipients;
- (BOOL)isRemovableFromSearchResults;
- (id)handles;
- (void)setDisplayString:(id)arg1;
- (id)displayString;
- (void)dealloc;

@end
