/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@class NSString, NSData, NSDictionary, <CKFileTransfer>, NSURL;

@interface CKMediaObject : NSObject <QLPreviewItem> {
    <CKFileTransfer> *_transfer;
}

@property(copy,readonly) NSURL * fileURL;
@property(retain) <CKFileTransfer> * transfer;
@property(copy,readonly) NSString * transferGUID;
@property(copy,readonly) NSData * data;
@property(copy,readonly) NSString * filename;
@property(copy,readonly) NSDictionary * transcoderUserInfo;
@property(copy,readonly) NSString * mimeType;
@property(copy,readonly) NSString * UTIType;
@property(readonly) int mediaType;
@property(readonly) NSURL * previewItemURL;
@property(readonly) NSString * previewItemTitle;

+ (Class)__ck_attachmentItemClass;
+ (BOOL)isPreviewable;
+ (id)attachmentSummary:(unsigned int)arg1;
+ (id)fallbackFilenamePrefix;
+ (id)UTITypes;
+ (id)iconCache;

- (id)fileManager;
- (id)filename;
- (id)JPEGDataFromImage:(id)arg1;
- (void)_sampleImageEdges:(id)arg1 usingRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg2 forMostlyWhitePixels:(unsigned int*)arg3 otherPixels:(unsigned int*)arg4;
- (BOOL)shouldShowDisclosure;
- (id)bbPreviewFillToSize:(struct CGSize { float x1; float x2; })arg1;
- (id)downloadProgressString;
- (id)downloadProgressImage;
- (id)fileSizeString;
- (Class)previewBalloonViewClass;
- (void)savePreview:(id)arg1 toURL:(id)arg2 forOrientation:(BOOL)arg3;
- (id)generatePreviewFromThumbnail:(id)arg1 width:(float)arg2 orientation:(BOOL)arg3;
- (id)savedPreviewFromURL:(id)arg1 forOrientation:(BOOL)arg2;
- (id)previewDispatchCache;
- (Class)coloredBalloonViewClass;
- (BOOL)canBeAttachmentContiguous;
- (id)generateThumbnailForWidth:(float)arg1 orientation:(BOOL)arg2;
- (struct CGSize { float x1; float x2; })bbSize;
- (BOOL)isPreviewable;
- (id)generateThumbnailFillToSize:(struct CGSize { float x1; float x2; })arg1 contentAlignmentInsets:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg2;
- (id)initWithTransfer:(id)arg1;
- (id)transcoderUserInfo;
- (void)setTransfer:(id)arg1;
- (BOOL)shouldBeQuickLooked;
- (BOOL)canExport;
- (BOOL)shouldShowViewer;
- (id)transfer;
- (id)composeImages;
- (Class)balloonViewClassForWidth:(float)arg1 orientation:(BOOL)arg2;
- (id)previewForWidth:(float)arg1 orientation:(BOOL)arg2;
- (void)export:(id)arg1;
- (id)pasteboardItem;
- (id)UTIType;
- (id)transferGUID;
- (int)mediaType;
- (id)fileURL;
- (id)previewItemURL;
- (id)mimeType;
- (id)location;
- (id)subtitle;
- (id)title;
- (id)data;
- (id)description;
- (void)dealloc;
- (id)icon;

@end
