/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSArray, NSDictionary;

@interface CKPublishAssetsOperation : CKDatabaseOperation  {
    NSDictionary *_fileNamesByAssetFieldNames;
    unsigned int _requestedTTL;
    unsigned int _URLOptions;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _assetPublishedBlock;


  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _publishAssetCompletionBlock;

    NSArray *_recordIDs;
}

@property(retain) NSDictionary * fileNamesByAssetFieldNames;
@property unsigned int requestedTTL;
@property unsigned int URLOptions;
@property(copy) id assetPublishedBlock;
@property(copy) id publishAssetCompletionBlock;
@property(retain) NSArray * recordIDs;


- (void)setURLOptions:(unsigned int)arg1;
- (id)assetPublishedBlock;
- (unsigned int)URLOptions;
- (unsigned int)requestedTTL;
- (id)fileNamesByAssetFieldNames;
- (id)recordIDs;
- (void)setRecordIDs:(id)arg1;
- (void)setAssetPublishedBlock:(id)arg1;
- (void)setPublishAssetCompletionBlock:(id)arg1;
- (void)setRequestedTTL:(unsigned int)arg1;
- (void)setFileNamesByAssetFieldNames:(id)arg1;
- (id)initWithRecordIDs:(id)arg1;
- (void).cxx_destruct;
- (id)publishAssetCompletionBlock;
- (void)_handleProgressCallback:(id)arg1;
- (void)performCKOperation;
- (BOOL)CKOperationShouldRun:(id*)arg1;
- (void)_finishOnCallbackQueueWithError:(id)arg1;
- (void)fillOutOperationInfo:(id)arg1;

@end
