/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreLocation.framework/CoreLocation
 */

@class NSDate;

@interface CLVehicleSpeed : NSObject <NSCopying, NSSecureCoding> {
    id _internal;
}

@property(readonly) double speed;
@property(readonly) NSDate * timestamp;

+ (BOOL)supportsSecureCoding;

- (id)shortDescription;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)timestamp;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (double)speed;
- (void)dealloc;
- (id)initWithClientVehicleSpeed:(struct { double x1; double x2; })arg1;

@end
