/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@class NSDate, NSNumber;

@interface CMOdometerData : NSObject <NSSecureCoding, NSCopying> {
    NSDate *_startDate;
    NSDate *_endDate;
    NSNumber *_distance;
}

@property(readonly) NSDate * startDate;
@property(readonly) NSDate * endDate;
@property(readonly) NSNumber * distance;

+ (BOOL)supportsSecureCoding;

- (id)endDate;
- (id)startDate;
- (id)distance;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithDistance:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;

@end
