/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

@interface ContactFolderItemsSyncContext : NSObject  {
    int _abPersonChangeId;
    int _abGroupChangeId;
}

@property int abPersonChangeId;
@property int abGroupChangeId;


- (void)setAbGroupChangeId:(int)arg1;
- (int)abGroupChangeId;
- (void)setAbPersonChangeId:(int)arg1;
- (int)abPersonChangeId;

@end
