/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

@class NSMutableSet;

@interface CoreDAVCalendarServerPushTransportsItem : CoreDAVItem  {
    NSMutableSet *_transports;
}

@property(retain) NSMutableSet * transports;

+ (id)copyParseRules;

- (void)setTransports:(id)arg1;
- (void)addTransport:(id)arg1;
- (id)transports;
- (id)description;
- (void)dealloc;
- (id)init;

@end
