/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

@class NSString, NSCache;

@interface CPBitmapStore : NSObject  {
    NSString *_path;
    NSString *_imagePath;
    NSCache *_cache;
    int _version;
    NSString *_versionPath;
    BOOL _lockOnRead;
}

@property(readonly) int version;
@property BOOL lockOnRead;
@property unsigned int cacheItemLimit;


- (id)imagePath;
- (void)removeImagesInGroups:(id)arg1;
- (void)commitTxn;
- (struct CGImage { }*)copyImageForKey:(id)arg1;
- (unsigned int)cacheItemLimit;
- (id)_versionPath;
- (struct CGImage { }*)_copyAndStoreImageForKey:(id)arg1 inGroup:(id)arg2 withSize:(struct CGSize { float x1; float x2; })arg3 format:(int)arg4 scale:(float)arg5 fillMem:(id)arg6 alternateCompletion:(id)arg7;
- (BOOL)saveImageWithKey:(id)arg1 inGroup:(id)arg2 andInfo:(struct _img { id x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned char x6; }*)arg3;
- (unsigned int)memContentOffset;
- (BOOL)lockOnRead;
- (void*)openAndMmap:(id)arg1 withInfo:(struct _img { id x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned char x6; }*)arg2;
- (BOOL)findImageWithKey:(id)arg1 inGroup:(id)arg2 andInfo:(struct _img { id x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned char x6; }*)arg3;
- (id)cacheNumberForKey:(id)arg1;
- (id)imageNameForKey:(id)arg1 inGroup:(id)arg2;
- (unsigned int)imageCount;
- (void)storeGrayscaleImageDataForKey:(id)arg1 inGroup:(id)arg2 withSize:(struct CGSize { float x1; float x2; })arg3 opaque:(BOOL)arg4 scale:(float)arg5 data:(id)arg6;
- (struct CGImage { }*)copyAndStoreImageForKey:(id)arg1 inGroup:(id)arg2 withSize:(struct CGSize { float x1; float x2; })arg3 opaque:(BOOL)arg4 scale:(float)arg5 draw:(id)arg6;
- (void)storeImageDataForKey:(id)arg1 inGroup:(id)arg2 withSize:(struct CGSize { float x1; float x2; })arg3 opaque:(BOOL)arg4 scale:(float)arg5 data:(id)arg6;
- (void)setCacheItemLimit:(unsigned int)arg1;
- (void)setLockOnRead:(BOOL)arg1;
- (void)removeImagesInGroups:(id)arg1 completion:(id)arg2;
- (void)storeImageForKey:(id)arg1 inGroup:(id)arg2 opaque:(BOOL)arg3 image:(struct CGImage { }*)arg4;
- (struct CGImage { }*)copyImageForKey:(id)arg1 inGroup:(id)arg2;
- (void)purge;
- (id)initWithPath:(id)arg1 version:(int)arg2;
- (int)version;
- (int)setVersion:(int)arg1;
- (void)commitTransaction;
- (void)dealloc;
- (id)allGroups;
- (int)setVersion:(int)arg1 withOptions:(unsigned int)arg2;

@end
