/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUINamedImageDescription : NSObject  {
    float _scale;
    int _idiom;
    int _subtype;
    int _sizeClassHorizontal;
    int _sizeClassVertical;
    int _blendMode;
    int _templateRenderingMode;
    int _imageType;
    struct { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _edgeInsets;
    struct { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _alignmentEdgeInsets;
    int _resizingMode;
}

@property float scale;
@property int idiom;
@property int subtype;
@property int sizeClassHorizontal;
@property int sizeClassVertical;
@property int blendMode;
@property BOOL isTemplate;
@property int templateRenderingMode;
@property int imageType;
@property struct { float x1; float x2; float x3; float x4; } edgeInsets;
@property struct { float x1; float x2; float x3; float x4; } alignmentEdgeInsets;
@property int resizingMode;


- (int)imageType;
- (BOOL)isTemplate;
- (void)setIsTemplate:(BOOL)arg1;
- (int)sizeClassVertical;
- (int)sizeClassHorizontal;
- (void)setImageType:(int)arg1;
- (void)setResizingMode:(int)arg1;
- (void)setAlignmentEdgeInsets:(struct { float x1; float x2; float x3; float x4; })arg1;
- (void)setTemplateRenderingMode:(int)arg1;
- (void)setSizeClassVertical:(int)arg1;
- (void)setSizeClassHorizontal:(int)arg1;
- (void)setEdgeInsets:(struct { float x1; float x2; float x3; float x4; })arg1;
- (void)setIdiom:(int)arg1;
- (int)idiom;
- (void)setScale:(float)arg1;
- (void)setSubtype:(int)arg1;
- (int)templateRenderingMode;
- (struct { float x1; float x2; float x3; float x4; })alignmentEdgeInsets;
- (int)resizingMode;
- (struct { float x1; float x2; float x3; float x4; })edgeInsets;
- (int)subtype;
- (float)scale;
- (void)setBlendMode:(int)arg1;
- (int)blendMode;
- (id)description;

@end
