/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@class NSString;

@interface CUIPSDLayer : NSObject  {
    float _opacity;
    int _blendMode;
    NSString *_name;
}

@property float opacity;
@property int blendMode;
@property(retain) NSString * name;


- (void)setOpacity:(float)arg1;
- (float)opacity;
- (void)setBlendMode:(int)arg1;
- (int)blendMode;
- (id)name;
- (void)setName:(id)arg1;
- (void)dealloc;
- (id)init;

@end
