/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

@class NSObject<OS_dispatch_queue>, NSHashTable;

@interface DAAccountMonitor : NSObject  {
    NSHashTable *_accounts;
    NSObject<OS_dispatch_queue> *_accountsQueue;
}

@property(retain) NSHashTable * accounts;
@property(retain) NSObject<OS_dispatch_queue> * accountsQueue;

+ (id)sharedMonitor;

- (void)setAccounts:(id)arg1;
- (id)monitoredAccounts;
- (id)accountsQueue;
- (void)setAccountsQueue:(id)arg1;
- (void)monitorAccount:(id)arg1;
- (void)unmonitorAccount:(id)arg1;
- (id)accounts;
- (void).cxx_destruct;
- (id)init;

@end
