/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataAccessUI.framework/DataAccessUI
 */

@class DAAccount;

@interface DASettingsAccountsUIController : ACUIViewController <DAValidityCheckConsumer, UIActionSheetDelegate, UIAlertViewDelegate> {
    DAAccount *_account;
    BOOL _didSetFullHostURL;
    BOOL _needsSave;
    BOOL _attemptedValidation;
    BOOL _isSettingUpNewAccount;
    BOOL _accountNeedsAdd;
    BOOL _validatedSuccessfully;
    BOOL _confirmedUnvalidatedAccount;
    BOOL _haveRegisteredForAccountsChanged;
    BOOL _transitioningToFinishedAccountSetup;
}

@property BOOL didSetFullHostURL;
@property BOOL needsSave;
@property BOOL attemptedValidation;
@property(retain) DAAccount * account;
@property BOOL isSettingUpNewAccount;
@property BOOL accountNeedsAdd;
@property BOOL validatedSuccessfully;
@property BOOL confirmedUnvalidatedAccount;
@property BOOL haveRegisteredForAccountsChanged;
@property BOOL transitioningToFinishedAccountSetup;


- (id)specifiers;
- (void)_accountsChanged:(id)arg1;
- (void)deleteAccountButtonTapped;
- (void)showSSLFailureView;
- (id)daAccountWithBackingAccountInfo:(id)arg1;
- (void)_deleteAccount;
- (BOOL)isRunningFromMobileMailApp;
- (void)_finishSaveAccountDismissWhenDone:(BOOL)arg1;
- (void)_dismissAndUpdateParent;
- (void)setHostString:(id)arg1;
- (BOOL)didSetFullHostURL;
- (void)setDidSetFullHostURL:(BOOL)arg1;
- (BOOL)transitioningToFinishedAccountSetup;
- (void)_saveAccountDismissWhenDone:(BOOL)arg1;
- (void)_confirmSaveUnvalidatedAccount;
- (BOOL)attemptedValidation;
- (void)setTransitioningToFinishedAccountSetup:(BOOL)arg1;
- (BOOL)dismissesAfterInitialSetup;
- (BOOL)confirmedUnvalidatedAccount;
- (BOOL)validatedSuccessfully;
- (void)didConfirmSaveUnvalidatedAccount:(BOOL)arg1;
- (void)setConfirmedUnvalidatedAccount:(BOOL)arg1;
- (void)_beginAccountValidation;
- (void)didConfirmTryWithoutSSL:(BOOL)arg1;
- (void)setHaveRegisteredForAccountsChanged:(BOOL)arg1;
- (BOOL)haveRegisteredForAccountsChanged;
- (void)setIsSettingUpNewAccount:(BOOL)arg1;
- (id)accountFromSpecifier;
- (void)account:(id)arg1 isValid:(BOOL)arg2 validationError:(id)arg3;
- (id)accountSpecifiers;
- (void)setAccount:(id)arg1;
- (void)reloadAccount;
- (id)account;
- (void)setNeedsSave:(BOOL)arg1;
- (BOOL)needsSave;
- (void)doneButtonTapped:(id)arg1;
- (void)finishedAccountSetup;
- (void)operationsHelper:(id)arg1 didRemoveAccount:(id)arg2 withSuccess:(BOOL)arg3 error:(id)arg4;
- (void)operationsHelper:(id)arg1 didSaveAccount:(id)arg2 withSuccess:(BOOL)arg3 error:(id)arg4;
- (BOOL)haveEnoughValues;
- (BOOL)validateAccount;
- (void)propertyValueChanged:(id)arg1;
- (id)accountPropertyWithSpecifier:(id)arg1;
- (void)setAccountProperty:(id)arg1 withSpecifier:(id)arg2;
- (id)localizedAccountSetupTitleString;
- (id)localizedConfirmSaveUnvalidatedAccountMessageString;
- (id)localizedConfirmSaveUnvalidatedAccountTitleString;
- (id)_defaultAccountDescription;
- (BOOL)transitionsAfterInitialSetup;
- (id)newDefaultAccount;
- (id)localizedValidationFailureTitleString;
- (id)currentlyEditingCell;
- (int)indexOfCurrentlyEditingCell;
- (void)hideProgressWithPrompt:(id)arg1;
- (void)setValidatedSuccessfully:(BOOL)arg1;
- (void)setAccountNeedsAdd:(BOOL)arg1;
- (void)setAttemptedValidation:(BOOL)arg1;
- (void)showIdenticalAccountFailureView;
- (BOOL)accountNeedsAdd;
- (id)localizedAccountTitleString;
- (BOOL)isSettingUpNewAccount;
- (void)setNeedsSaveAndValidation:(BOOL)arg1;
- (id)accountBooleanPropertyWithSpecifier:(id)arg1;
- (void)setAccountBooleanProperty:(id)arg1 withSpecifier:(id)arg2;
- (id)lastGroupSpecifierInSpecifiers:(id)arg1;
- (void).cxx_destruct;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)cancelButtonTapped:(id)arg1;
- (void)dealloc;
- (void)updateDoneButton;

@end
