/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/ExternalAccessory.framework/ExternalAccessory
 */

@class <EABluetoothAccessoryPickerDelegate>, BTDevicePicker;

@interface EABluetoothAccessoryPicker : NSObject <BTDevicePickerDelegate> {
    BTDevicePicker *_picker;
    <EABluetoothAccessoryPickerDelegate> *_delegate;
}

@property <EABluetoothAccessoryPickerDelegate> * delegate;

+ (void)wakeSelectedBluetoothAccessories:(id)arg1;

- (id)initWithPredicate:(id)arg1;
- (id)delegate;
- (void)show;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (void)dismissPicker;
- (void)devicePicker:(id)arg1 didDismissWithResult:(int)arg2 device:(id)arg3;

@end
