/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString;

@interface EDPivotPageField : NSObject  {
    unsigned long mFieldId;
    NSString *mCap;
    NSString *mName;
}

+ (id)pivotPageField;

- (void)setFieldId:(unsigned long)arg1;
- (unsigned long)fieldId;
- (id)cap;
- (void)setCap:(id)arg1;
- (id)name;
- (void)setName:(id)arg1;
- (void)dealloc;
- (id)init;

@end
