/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/EventKit.framework/EventKit
 */

@class EKCalendarItem, EKAlarm, EKObjectToOneRelation, NSString, EKStructuredLocation, NSDate, NSArray;

@interface EKAlarm : EKObject <NSCopying> {
    EKObjectToOneRelation *_locationRelation;
}

@property double relativeOffset;
@property(copy) NSDate * absoluteDate;
@property(copy) EKStructuredLocation * structuredLocation;
@property int proximity;
@property(readonly) BOOL isAbsolute;
@property(readonly) NSString * UUID;
@property(retain) EKCalendarItem * owner;
@property(copy) NSDate * acknowledgedDate;
@property(readonly) NSString * externalID;
@property(getter=isDefaultAlarm) BOOL defaultAlarm;
@property(retain) EKAlarm * originalAlarm;
@property(copy) NSArray * snoozedAlarms;
@property(readonly) BOOL isSnoozedAlarm;
@property(retain) EKObjectToOneRelation * locationRelation;

+ (double)defaultGeofencedReminderRadius;
+ (BOOL)areLocationsCurrentlyEnabled;
+ (BOOL)areLocationsAllowed;
+ (id)alarmWithAbsoluteDate:(id)arg1;
+ (BOOL)areLocationsAvailable;
+ (BOOL)areLocationsAllowedWithAuthorizationStatus:(int)arg1;
+ (int)_currentAuthorizationStatus;
+ (id)alarmWithRelativeOffset:(double)arg1;

- (BOOL)validate:(id*)arg1;
- (id)UUID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)owner;
- (id)description;
- (void)dealloc;
- (id)init;
- (void)setLocationRelation:(id)arg1;
- (id)locationRelation;
- (BOOL)isSnoozedAlarm;
- (void)removeSnoozedAlarm:(id)arg1;
- (void)addSnoozedAlarm:(id)arg1;
- (void)setSnoozedAlarms:(id)arg1;
- (id)snoozedAlarms;
- (void)setDefaultAlarm:(BOOL)arg1;
- (BOOL)isDefaultAlarm;
- (id)ownerUUID;
- (id)acknowledgedDate;
- (void)setProximity:(int)arg1;
- (void)setStructuredLocation:(id)arg1;
- (id)originalAlarm;
- (id)_snoozedAlarmsRelation;
- (id)_originalAlarmRelation;
- (id)_locationRelation;
- (int)proximity;
- (id)absoluteDate;
- (void)setAbsoluteDate:(id)arg1;
- (id)initWithRelativeOffset:(double)arg1;
- (id)initWithAbsoluteDate:(id)arg1;
- (BOOL)rebase;
- (double)relativeOffset;
- (BOOL)isAbsolute;
- (void)setOriginalAlarm:(id)arg1;
- (void)setRelativeOffset:(double)arg1;
- (void)setAcknowledgedDate:(id)arg1;
- (id)structuredLocation;
- (id)lazyLoadRelationForKey:(id)arg1;
- (id)externalID;
- (id)localizedDescription;
- (id)localizedDescriptionForReminder;
- (id)_localizedDescription:(BOOL)arg1 forEvent:(BOOL)arg2 isAllDay:(BOOL)arg3;
- (id)longLocalizedDescription;
- (id)longLocalizedAllDayDescription;
- (id)localizedAllDayDescription;

@end
