/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/EventKit.framework/EventKit
 */

@class NSDate, NSString, NSArray;

@interface EKCalendarEventInvitationNotification : EKCalendarNotification  {
    BOOL _allDay;
    BOOL _hasRecurrenceRules;
    BOOL _timeChanged;
    BOOL _dateChanged;
    BOOL _locationChanged;
    BOOL _attendeeReplyChanged;
    NSString *_location;
    NSDate *_startDate;
    NSDate *_startDateForNextOccurrence;
    NSDate *_endDate;
    NSDate *_participationStatusModifiedDate;
    int _participationStatus;
    int _status;
    NSArray *_attendees;
}

@property(retain) NSString * location;
@property(retain) NSDate * startDate;
@property(retain) NSDate * startDateForNextOccurrence;
@property(retain) NSDate * endDate;
@property(retain) NSDate * participationStatusModifiedDate;
@property int participationStatus;
@property int status;
@property(getter=isAllDay) BOOL allDay;
@property BOOL hasRecurrenceRules;
@property BOOL timeChanged;
@property BOOL dateChanged;
@property BOOL locationChanged;
@property BOOL attendeeReplyChanged;
@property(retain) NSArray * attendees;


- (void)setLocation:(id)arg1;
- (id)endDate;
- (id)startDate;
- (void)setEndDate:(id)arg1;
- (void)setStartDate:(id)arg1;
- (void)setStatus:(int)arg1;
- (int)status;
- (id)location;
- (void)dealloc;
- (id)startDateForNextOccurrence;
- (void)setAttendeeReplyChanged:(BOOL)arg1;
- (void)setHasRecurrenceRules:(BOOL)arg1;
- (void)setStartDateForNextOccurrence:(id)arg1;
- (void)setLocationChanged:(BOOL)arg1;
- (void)setTimeChanged:(BOOL)arg1;
- (void)setDateChanged:(BOOL)arg1;
- (id)initWithEvent:(id)arg1;
- (void)setParticipationStatusModifiedDate:(id)arg1;
- (void)setAttendees:(id)arg1;
- (BOOL)attendeeReplyChanged;
- (BOOL)locationChanged;
- (BOOL)timeChanged;
- (BOOL)dateChanged;
- (void)setParticipationStatus:(int)arg1;
- (id)attendees;
- (id)participationStatusModifiedDate;
- (BOOL)hasRecurrenceRules;
- (int)participationStatus;
- (void)setAllDay:(BOOL)arg1;
- (id)eventFromEventStore:(id)arg1;
- (BOOL)isAllDay;

@end
