/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/EventKit.framework/EventKit
 */

@class NSSet;

@interface EKDirectorySearchResultSet : NSObject  {
    NSSet *_locations;
    NSSet *_groups;
    NSSet *_resources;
    NSSet *_people;
}

@property(retain) NSSet * locations;
@property(retain) NSSet * groups;
@property(retain) NSSet * resources;
@property(retain) NSSet * people;


- (id)locations;
- (void)setResources:(id)arg1;
- (id)resources;
- (void)setLocations:(id)arg1;
- (id)people;
- (id)groups;
- (void)setPeople:(id)arg1;
- (void)setGroups:(id)arg1;

@end
