/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@class EKEvent;

@interface EKEventDetailCell : UITableViewCell  {
    EKEvent *_event;
    BOOL _editable;
    float _lastLaidOutWidth;
    int _lastLaidOutPosition;
}

@property(readonly) BOOL isEditable;

+ (float)detailsPostLabelSpace;
+ (float)detailsBottomVerticalInset;
+ (float)detailsTopVerticalInset;
+ (float)_scaledDistanceCalculatedFromBottomToBaseline:(float)arg1;
+ (float)_scaledDistanceCalculatedFromTopFromBaseline:(float)arg1;
+ (id)_bodyFontAtDefaultSize;
+ (float)detailsCellDefaultHeight;

- (void).cxx_destruct;
- (void)setEvent:(id)arg1;
- (BOOL)update;
- (void)sizeToFit;
- (BOOL)isEditable;
- (BOOL)needsLayoutForWidth:(float)arg1 position:(int)arg2;
- (void)layoutForWidth:(float)arg1 position:(int)arg2;
- (id)initWithEvent:(id)arg1 editable:(BOOL)arg2;
- (id)initWithEvent:(id)arg1 editable:(BOOL)arg2 style:(int)arg3;

@end
