/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@class UISwitch, UITableView, NSIndexPath, EKCalendarItem, EKEventStore, EKStructuredLocation, EKTravelRouteEstimationController, NSDate;

@interface EKEventTravelTimeEditViewController : EKEditItemViewController <UITableViewDataSource, UITableViewDelegate, EKTravelRouteEstimationControllerDelegate, EKEditItemViewControllerDelegate> {
    struct CGRect { 
        struct CGPoint { 
            float x; 
            float y; 
        } origin; 
        struct CGSize { 
            float width; 
            float height; 
        } size; 
    } _initFrame;
    EKCalendarItem *_calendarItem;
    EKEventStore *_eventStore;
    UITableView *_table;
    NSIndexPath *_checkedItem;
    UISwitch *_switchControl;
    int _travelTimeSelectedChoice;
    double _customTravelTimeDuration;
    BOOL _estimationGroupIsShowing;
    BOOL _customTimesGroupIsShowing;
    BOOL _externallySetValueGroupIsShowing;
    BOOL _isAnimatingTableSections;
    BOOL _pendingReloadData;
    BOOL _estimatedRowIsChecked;
    EKTravelRouteEstimationController *_routeEstimationControler;
    int _selectedRoutingMode;
    int _originalSelectedRoutingMode;
    double _originalSelectedTravelTime;
    NSDate *_arrivalDate;
    EKStructuredLocation *_originStructuredLocation;
    EKStructuredLocation *_destinationStructuredLocation;
    double _selectedTravelTime;
}

@property double selectedTravelTime;
@property int selectedRoutingMode;
@property(retain) NSDate * arrivalDate;
@property(retain) EKStructuredLocation * originStructuredLocation;
@property(retain) EKStructuredLocation * destinationStructuredLocation;


- (void).cxx_destruct;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)description;
- (int)travelTimeSelectedChoice;
- (void)routeEstimationControllerDidFinishOriginLocationLookup:(id)arg1;
- (void)routeEstimationControllerDidBeginOriginLocationLookup:(id)arg1;
- (void)routeEstimationControllerDidFinishTravelTimeLookup:(id)arg1;
- (void)routeEstimationControllerDidBeginTravelTimeLookup:(id)arg1;
- (void)_originLocationButtonWasTapped;
- (id)_stringForOriginLocation;
- (int)_numberOfEstimationGroupRows;
- (unsigned int)_toggleSwitchSection;
- (unsigned int)_customTravelTimeSection;
- (unsigned int)_externallySetValueTravelTimeSection;
- (BOOL)setTravelTimeSelectedChoiceEstimatedRowAtIndex:(unsigned int)arg1;
- (void)setTravelTimeSelectedChoiceToFirstValidEstimatedRow;
- (BOOL)_shouldAutoSelectEstimatedTravelTimeOnLookupCompletion;
- (void)_updateTableView;
- (void)_setEstimationActive:(BOOL)arg1;
- (void)setTravelTimeSelectedChoice:(int)arg1;
- (unsigned int)_estimatedTravelTimeSection;
- (id)_indexPathForSelectedTravelTime;
- (void)_locationsChanged;
- (BOOL)_showingOptions;
- (void)_hasFinishedRowAnimations;
- (void)_autoselectFromAvailableChoices;
- (void)_updateVisibleSections;
- (BOOL)_showingOptionsInitialState;
- (void)_travelTimeActivationSwitchChanged:(id)arg1;
- (id)destinationStructuredLocation;
- (id)_routeEstimationControler;
- (id)originStructuredLocation;
- (int)selectedRoutingMode;
- (double)selectedTravelTime;
- (void)setDestinationStructuredLocation:(id)arg1;
- (void)setOriginStructuredLocation:(id)arg1;
- (void)setSelectedRoutingMode:(int)arg1;
- (void)setSelectedTravelTime:(double)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 styleProvider:(id)arg2 calendarItem:(id)arg3 eventStore:(id)arg4;
- (void)_checkItemAtIndexPath:(id)arg1;
- (BOOL)editItemViewControllerCommit:(id)arg1;
- (BOOL)editItemViewControllerShouldShowDetachAlert;
- (void)editItemViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (id)arrivalDate;
- (void)setArrivalDate:(id)arg1;

@end
