/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FamilyCircle.framework/FamilyCircle
 */

@class NSNumber;

@interface FARemoveFamilyMemberRequest : FAFamilyCircleRequest  {
    NSNumber *_memberDSID;
}

@property(copy,readonly) NSNumber * memberDSID;


- (void)startRequestWithCompletionHandler:(id)arg1;
- (id)initWithFamilyMemberDSID:(id)arg1;
- (id)memberDSID;
- (void).cxx_destruct;

@end
