/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@class NSSet;

@interface FBSMutableSceneClientSettings : FBSSceneClientSettings  {
}

@property int preferredInterfaceOrientation;
@property(copy) NSSet * occlusions;

+ (BOOL)_isMutable;

- (void)setPreferredInterfaceOrientation:(int)arg1;
- (void)setOcclusions:(id)arg1;
- (id)otherSettings;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
