/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/VUSocialUpload.framework/VUSocialUpload
 */

@class NSString;

@interface FlickrPhotoSet : NSObject  {
    NSString *_secret;
    NSString *_title;
    NSString *_photoSetDescription;
    long long _identifier;
    long long _primaryPhotoID;
    long long _farmID;
    long long _serverID;
}

@property long long identifier;
@property long long primaryPhotoID;
@property long long farmID;
@property long long serverID;
@property(copy) NSString * secret;
@property(copy) NSString * title;
@property(copy) NSString * photoSetDescription;


- (void)setPhotoSetDescription:(id)arg1;
- (id)photoSetDescription;
- (void)setSecret:(id)arg1;
- (id)secret;
- (void)setFarmID:(long long)arg1;
- (long long)farmID;
- (void)setPrimaryPhotoID:(long long)arg1;
- (long long)primaryPhotoID;
- (long long)serverID;
- (void)setServerID:(long long)arg1;
- (void).cxx_destruct;
- (void)setIdentifier:(long long)arg1;
- (id)title;
- (long long)identifier;
- (void)setTitle:(id)arg1;
- (id)description;

@end
