/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CallHistory.framework/CallHistory
 */

@class NSObject<OS_dispatch_queue>;

@interface GateKeeper : CHLogger  {
    BOOL _hasDeviceBeenUnlockedSinceBoot;
    NSObject<OS_dispatch_queue> *_queue;
}


- (BOOL)hasDeviceBeenUnlockedSinceBoot;
- (void)setupMobileKeyBag;
- (void).cxx_destruct;
- (id)initWithQueue:(id)arg1;

@end
