/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class GEOMapRequestManager;

@interface GEOMapRequest : NSObject  {
    GEOMapRequestManager *_requestManager;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _completionHandler;

    BOOL _isFinished;
}

@property(copy) id completionHandler;
@property(readonly) BOOL isFinished;


- (id)initWithManager:(id)arg1;
- (BOOL)isFinished;
- (void)complete;
- (void)setCompletionHandler:(id)arg1;
- (id)completionHandler;
- (void)cancel;
- (void)dealloc;

@end
