/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSMutableArray, NSString;

@interface GEOPDEntity : PBCodable <NSCopying> {
    NSMutableArray *_altFaxs;
    NSMutableArray *_altTelephones;
    NSMutableArray *_altUrls;
    NSString *_fax;
    NSMutableArray *_localizedCategorys;
    NSMutableArray *_names;
    NSMutableArray *_spokenNames;
    NSString *_telephone;
    int _type;
    NSString *_url;
    BOOL _isDisputed;
    BOOL _isPermanentlyClosed;
    struct { 
        unsigned int type : 1; 
        unsigned int isDisputed : 1; 
        unsigned int isPermanentlyClosed : 1; 
    } _has;
}

@property BOOL hasType;
@property int type;
@property(readonly) BOOL hasTelephone;
@property(retain) NSString * telephone;
@property(retain) NSMutableArray * altTelephones;
@property(readonly) BOOL hasFax;
@property(retain) NSString * fax;
@property(retain) NSMutableArray * altFaxs;
@property(readonly) BOOL hasUrl;
@property(retain) NSString * url;
@property(retain) NSMutableArray * altUrls;
@property BOOL hasIsPermanentlyClosed;
@property BOOL isPermanentlyClosed;
@property BOOL hasIsDisputed;
@property BOOL isDisputed;
@property(retain) NSMutableArray * names;
@property(retain) NSMutableArray * spokenNames;
@property(retain) NSMutableArray * localizedCategorys;


- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)names;
- (BOOL)hasType;
- (void)setHasType:(BOOL)arg1;
- (id)spokenNames;
- (id)altUrls;
- (id)altFaxs;
- (id)fax;
- (void)setHasIsPermanentlyClosed:(BOOL)arg1;
- (void)setIsPermanentlyClosed:(BOOL)arg1;
- (BOOL)hasFax;
- (id)localizedCategoryAtIndex:(unsigned int)arg1;
- (void)clearLocalizedCategorys;
- (unsigned int)localizedCategorysCount;
- (id)spokenNameAtIndex:(unsigned int)arg1;
- (void)clearSpokenNames;
- (unsigned int)spokenNamesCount;
- (id)nameAtIndex:(unsigned int)arg1;
- (void)clearNames;
- (id)altUrlAtIndex:(unsigned int)arg1;
- (void)clearAltUrls;
- (unsigned int)altUrlsCount;
- (id)altFaxAtIndex:(unsigned int)arg1;
- (void)clearAltFaxs;
- (unsigned int)altFaxsCount;
- (id)altTelephoneAtIndex:(unsigned int)arg1;
- (void)clearAltTelephones;
- (unsigned int)altTelephonesCount;
- (void)addLocalizedCategory:(id)arg1;
- (void)addSpokenName:(id)arg1;
- (void)addName:(id)arg1;
- (void)addAltUrl:(id)arg1;
- (void)addAltFax:(id)arg1;
- (void)addAltTelephone:(id)arg1;
- (void)setLocalizedCategorys:(id)arg1;
- (void)setSpokenNames:(id)arg1;
- (void)setNames:(id)arg1;
- (void)setAltUrls:(id)arg1;
- (void)setAltFaxs:(id)arg1;
- (void)setFax:(id)arg1;
- (void)setAltTelephones:(id)arg1;
- (id)altTelephones;
- (id)bestLocalizedName;
- (unsigned int)namesCount;
- (id)localizedCategorys;
- (BOOL)isPermanentlyClosed;
- (BOOL)hasIsPermanentlyClosed;
- (BOOL)hasIsDisputed;
- (void)setHasIsDisputed:(BOOL)arg1;
- (void)setIsDisputed:(BOOL)arg1;
- (BOOL)isDisputed;
- (id)telephone;
- (BOOL)hasTelephone;
- (void)setTelephone:(id)arg1;
- (BOOL)hasUrl;
- (id)dictionaryRepresentation;
- (void)setUrl:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (int)type;
- (void)setType:(int)arg1;
- (id)url;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;

@end
