/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEORPPlaceProblem : PBCodable <NSCopying> {
    unsigned int _componentIndex;
    unsigned int _componentValueIndex;
    struct { 
        unsigned int componentIndex : 1; 
        unsigned int componentValueIndex : 1; 
    } _has;
}

@property BOOL hasComponentIndex;
@property unsigned int componentIndex;
@property BOOL hasComponentValueIndex;
@property unsigned int componentValueIndex;


- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (unsigned int)componentValueIndex;
- (unsigned int)componentIndex;
- (BOOL)hasComponentValueIndex;
- (void)setHasComponentValueIndex:(BOOL)arg1;
- (void)setComponentValueIndex:(unsigned int)arg1;
- (BOOL)hasComponentIndex;
- (void)setHasComponentIndex:(BOOL)arg1;
- (void)setComponentIndex:(unsigned int)arg1;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end
