/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class GEOLatLng;

@interface GEORoadAccessPoint : PBCodable <NSCopying> {
    int _drivingDirection;
    GEOLatLng *_location;
    int _walkingDirection;
    BOOL _isApproximate;
    struct { 
        unsigned int drivingDirection : 1; 
        unsigned int walkingDirection : 1; 
        unsigned int isApproximate : 1; 
    } _has;
}

@property(readonly) BOOL hasLocation;
@property(retain) GEOLatLng * location;
@property BOOL hasIsApproximate;
@property BOOL isApproximate;
@property BOOL hasWalkingDirection;
@property int walkingDirection;
@property BOOL hasDrivingDirection;
@property int drivingDirection;


- (void)setLocation:(id)arg1;
- (BOOL)hasLocation;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (int)drivingDirection;
- (int)walkingDirection;
- (BOOL)isApproximate;
- (BOOL)hasDrivingDirection;
- (void)setHasDrivingDirection:(BOOL)arg1;
- (BOOL)hasWalkingDirection;
- (void)setHasWalkingDirection:(BOOL)arg1;
- (BOOL)hasIsApproximate;
- (void)setHasIsApproximate:(BOOL)arg1;
- (void)setIsApproximate:(BOOL)arg1;
- (void)setDrivingDirection:(int)arg1;
- (id)dictionaryRepresentation;
- (id)location;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)setWalkingDirection:(int)arg1;
- (id)description;
- (void)dealloc;

@end
