/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOURLCamera : PBCodable <NSCopying> {
    double _altitude;
    double _heading;
    double _latitude;
    double _longitude;
    double _pitch;
    struct { 
        unsigned int altitude : 1; 
        unsigned int heading : 1; 
        unsigned int latitude : 1; 
        unsigned int longitude : 1; 
        unsigned int pitch : 1; 
    } _has;
}

@property BOOL hasLatitude;
@property double latitude;
@property BOOL hasLongitude;
@property double longitude;
@property BOOL hasHeading;
@property double heading;
@property BOOL hasPitch;
@property double pitch;
@property BOOL hasAltitude;
@property double altitude;


- (double)heading;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)setPitch:(double)arg1;
- (double)altitude;
- (double)pitch;
- (BOOL)hasPitch;
- (void)setHasPitch:(BOOL)arg1;
- (BOOL)hasHeading;
- (void)setHasHeading:(BOOL)arg1;
- (void)setHeading:(double)arg1;
- (BOOL)hasAltitude;
- (void)setHasAltitude:(BOOL)arg1;
- (BOOL)hasLongitude;
- (void)setHasLongitude:(BOOL)arg1;
- (BOOL)hasLatitude;
- (void)setHasLatitude:(BOOL)arg1;
- (double)longitude;
- (double)latitude;
- (void)setAltitude:(double)arg1;
- (void)setLongitude:(double)arg1;
- (void)setLatitude:(double)arg1;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end
