/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class GEOWaypointLocation, GEOWaypointPlace, GEOWaypointID;

@interface GEOWaypointTyped : PBCodable <NSCopying> {
    GEOWaypointID *_waypointId;
    GEOWaypointLocation *_waypointLocation;
    GEOWaypointPlace *_waypointPlace;
    int _waypointType;
    BOOL _isCurrentLocation;
    struct { 
        unsigned int waypointType : 1; 
        unsigned int isCurrentLocation : 1; 
    } _has;
}

@property BOOL hasWaypointType;
@property int waypointType;
@property(readonly) BOOL hasWaypointId;
@property(retain) GEOWaypointID * waypointId;
@property(readonly) BOOL hasWaypointPlace;
@property(retain) GEOWaypointPlace * waypointPlace;
@property(readonly) BOOL hasWaypointLocation;
@property(retain) GEOWaypointLocation * waypointLocation;
@property BOOL hasIsCurrentLocation;
@property BOOL isCurrentLocation;


- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)waypointLocation;
- (id)waypointPlace;
- (id)waypointId;
- (int)waypointType;
- (BOOL)hasWaypointLocation;
- (BOOL)hasWaypointPlace;
- (BOOL)hasWaypointId;
- (BOOL)hasWaypointType;
- (void)setHasWaypointType:(BOOL)arg1;
- (void)setWaypointType:(int)arg1;
- (void)setWaypointLocation:(id)arg1;
- (void)setWaypointPlace:(id)arg1;
- (void)setWaypointId:(id)arg1;
- (BOOL)hasIsCurrentLocation;
- (void)setHasIsCurrentLocation:(BOOL)arg1;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;
- (void)setIsCurrentLocation:(BOOL)arg1;
- (BOOL)isCurrentLocation;

@end
