/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@class NSURL, NSString;

@interface GKAuthenticateResponse : GKInternalRepresentation  {
    BOOL _loginDisabled;
    BOOL _passwordChangeRequired;
    BOOL _shouldShowLinkAccountsUI;
    NSString *_accountName;
    NSString *_playerID;
    NSString *_authToken;
    int _environment;
    NSURL *_passwordChangeURL;
}

@property(retain) NSString * accountName;
@property(retain) NSString * playerID;
@property(retain) NSString * authToken;
@property BOOL loginDisabled;
@property int environment;
@property BOOL passwordChangeRequired;
@property(retain) NSURL * passwordChangeURL;
@property BOOL shouldShowLinkAccountsUI;

+ (id)secureCodedPropertyKeys;

- (BOOL)loginDisabled;
- (void)setPlayerID:(id)arg1;
- (id)playerID;
- (void)setShouldShowLinkAccountsUI:(BOOL)arg1;
- (BOOL)shouldShowLinkAccountsUI;
- (void)setPasswordChangeURL:(id)arg1;
- (id)passwordChangeURL;
- (void)setPasswordChangeRequired:(BOOL)arg1;
- (BOOL)passwordChangeRequired;
- (void)setLoginDisabled:(BOOL)arg1;
- (void)setEnvironment:(int)arg1;
- (id)authToken;
- (void)setAuthToken:(id)arg1;
- (id)accountName;
- (void)setAccountName:(id)arg1;
- (int)environment;
- (void)dealloc;

@end
