/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@class CADisplayLink, NSMutableSet;

@interface GKBubbleMeshAnimator : NSObject  {
    NSMutableSet *_animatingViews;
    CADisplayLink *_displayLink;
    double _lastUpdateTime;
}

@property(retain) NSMutableSet * animatingViews;
@property CADisplayLink * displayLink;
@property double lastUpdateTime;

+ (id)sharedAnimator;

- (void)setLastUpdateTime:(double)arg1;
- (double)lastUpdateTime;
- (void)setAnimatingViews:(id)arg1;
- (id)animatingViews;
- (void)removeAnimatingBubbleView:(id)arg1;
- (void)addAnimatingBubbleView:(id)arg1;
- (void)update:(id)arg1;
- (id)displayLink;
- (void)setDisplayLink:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)dealloc;
- (id)init;

@end
