/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@class NSSet, NSString;

@interface GKCompatibilityEntryInternal : GKInternalRepresentation  {
    NSString *_bundleID;
    NSSet *_versions;
}

@property(retain) NSString * bundleID;
@property(retain) NSSet * versions;

+ (id)secureCodedPropertyKeys;

- (void)setVersions:(id)arg1;
- (void)setBundleID:(id)arg1;
- (id)bundleID;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)versions;

@end
