/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@class GKPlayer, GKGame, NSDate, GKRecentMatchInternal;

@interface GKGameMatch : NSObject  {
    GKRecentMatchInternal *_internal;
    GKGame *_game;
    GKPlayer *_player;
}

@property(readonly) GKPlayer * player;
@property(readonly) GKGame * game;
@property(retain) NSDate * date;
@property(retain) GKRecentMatchInternal * internal;

+ (id)instanceMethodSignatureForSelector:(SEL)arg1;
+ (BOOL)instancesRespondToSelector:(SEL)arg1;

- (id)player;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)game;
- (id)internal;
- (id)initWithInternalRepresentation:(id)arg1 game:(id)arg2;
- (void)setInternal:(id)arg1;
- (id)valueForUndefinedKey:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)description;
- (void)dealloc;
- (id)init;

@end
