/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@class NSError, NSString;

@interface GKHostReachability : GKReachability  {
    NSString *_hostName;
    NSError *_error;
}

@property(retain) NSString * hostName;
@property(retain) NSError * error;

+ (id)_gkReachabilityWithHostName:(id)arg1;

- (id)error;
- (void)setError:(id)arg1;
- (void)setHostName:(id)arg1;
- (void)dealloc;
- (id)hostName;

@end
