/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/GameCenterPrivateUI.framework/GameCenterPrivateUI
 */

@class NSArray, GKLoadableContentStateMachine, UIActivityIndicatorView, NSString;

@interface GKLoadableContentViewController : GKViewController <GKStateMachineDelegate> {
    UIActivityIndicatorView *_activityIndicator;
    NSArray *_viewsToHideWhileLoading;
    GKLoadableContentStateMachine *_loadingMachine;
}

@property(retain) NSString * loadingState;
@property(retain) UIActivityIndicatorView * activityIndicator;
@property(retain) NSArray * viewsToHideWhileLoading;
@property(retain) GKLoadableContentStateMachine * loadingMachine;


- (id)viewsToHideWhileLoading;
- (void)setLoadingState:(id)arg1;
- (void)setViewsToHideWhileLoading:(id)arg1;
- (void)setLoadingMachine:(id)arg1;
- (id)loadingMachine;
- (void)didExitLoadedState;
- (void)didEnterLoadedState;
- (void)didExitLoadingState;
- (void)didEnterLoadingState;
- (id)loadingState;
- (id)activityIndicator;
- (void)setActivityIndicator:(id)arg1;
- (void)dealloc;
- (id)init;

@end
