/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class GQDTTable;

@interface GQHTableState : NSObject  {
    int mPrevRowIndex;
    int mPrevColumnIndex;
    GQDTTable *mTable;
    struct vector<unsigned short, std::__1::allocator<unsigned short> > { unsigned short *x1; unsigned short *x2; struct __compressed_pair<unsigned short *, std::__1::allocator<unsigned short> > { unsigned short *x_3_1_1; } x3; } *mCellCountInColumns;
    int mGroupLevel;
    boolmSplitTable;
    double mCurrentTablePosition;
    double mLastAttachmentPosition;
    long mSplitTableIndex;
    double mOriginalTableHeight;
}


- (void)setTable:(id)arg1;
- (id)table;
- (void)dealloc;
- (id)init;
- (double)originalTableHeight;
- (long)nextSplitTableIndex;
- (double)lastAttachmentPosition;
- (int)groupLevel;
- (void)setGroupLevel:(int)arg1;
- (void)setPrevRowIndex:(int)arg1 columnIndex:(int)arg2;
- (void)setLastAttachmentPosition:(double)arg1;
- (void)setOriginalTableHeight:(double)arg1;
- (void)setSplitTableIndex:(long)arg1;
- (void)setSplitTable:(bool)arg1;
- (int)prevColumnIndex;
- (int)prevRowIndex;
- (struct vector<unsigned short, std::__1::allocator<unsigned short> > { unsigned short *x1; unsigned short *x2; struct __compressed_pair<unsigned short *, std::__1::allocator<unsigned short> > { unsigned short *x_3_1_1; } x3; }*)cellCountInColumns;
- (void)addRowHeight:(float)arg1;
- (double)currentTablePosition;
- (bool)splitTable;

@end
