/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/HealthKitUI.framework/HealthKitUI
 */

@class NSMutableArray, NSMutableDictionary;

@interface HKDataCategoryController : NSObject  {
    NSMutableArray *_dataCategories;
    NSMutableDictionary *_dataCategoriesByCategoryID;
}

+ (id)sharedInstance;

- (id)categoryWithID:(unsigned int)arg1;
- (id)allDataCategories;
- (id)initWithDataFromURL:(id)arg1;
- (void).cxx_destruct;

@end
