/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/HealthKitUI.framework/HealthKitUI
 */

@interface HKEmergencyCardMedicalNotesTableItem : HKEmergencyCardMultilineTextTableItem  {
}


- (void)_updateMultilineStringValueWithValue:(id)arg1;
- (id)_multilineStringValue;
- (id)_placeholderText;
- (BOOL)hasPresentableData;
- (id)title;

@end
