/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@class HKQuantityType, HKQuantity;

@interface HKQuantitySample : HKSample  {
    HKQuantity *_quantity;
}

@property(readonly) HKQuantityType * quantityType;
@property(readonly) HKQuantity * quantity;

+ (BOOL)supportsSecureCoding;
+ (id)quantitySampleWithType:(id)arg1 quantity:(id)arg2 startDate:(id)arg3 endDate:(id)arg4;
+ (id)quantitySampleWithType:(id)arg1 quantity:(id)arg2 startDate:(id)arg3 endDate:(id)arg4 metadata:(id)arg5;

- (void).cxx_destruct;
- (void)validate;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)_setQuantity:(id)arg1;
- (id)quantity;
- (id)quantityType;
- (id)_valueDescription;

@end
