/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class ML3MusicLibrary, NSData, ML3DatabaseConnection;

@interface HomeSharingPlaylistImporter : NSData  {
    NSData *_playlistData;
    ML3MusicLibrary *_library;
    ML3DatabaseConnection *_connection;
    unsigned int _basePlaylistContainerId;
}


- (BOOL)importPlaylistData;
- (id)initWithData:(id)arg1 basePlaylistContainerId:(unsigned int)arg2 library:(id)arg3 connection:(id)arg4;
- (BOOL)executeUpdateSQL:(id)arg1;
- (void).cxx_destruct;

@end
