/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class NSData, NSString;

@interface HSNowPlayingArtworkResponse : HSResponse  {
    NSData *_artworkData;
    NSString *_artworkMIMEType;
}

@property(retain) NSData * artworkData;
@property(retain) NSString * artworkMIMEType;


- (void)setArtworkData:(id)arg1;
- (id)artworkData;
- (id)artworkMIMEType;
- (void)setArtworkMIMEType:(id)arg1;
- (void).cxx_destruct;

@end
