/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iAdDeveloper.framework/iAdDeveloper
 */

@class HTSHTTPMessageRequest, NSString, NSMutableData;

@interface HTSHTTPMessageResponse : HTSHTTPMessage  {
    int _statusCode;
    NSString *_statusDescription;
    NSString *_trackingDescription;
    HTSHTTPMessageRequest *_request;
    NSMutableData *_serializedData;
    double _sendTime;
    unsigned long long _written;
}

@property int statusCode;
@property(copy) NSString * statusDescription;
@property(copy) NSString * trackingDescription;
@property(retain) HTSHTTPMessageRequest * request;
@property(retain) NSMutableData * serializedData;
@property unsigned long long written;
@property double sendTime;


- (id)statusDescription;
- (void)setWritten:(unsigned long long)arg1;
- (unsigned long long)written;
- (void)setSendTime:(double)arg1;
- (double)sendTime;
- (void)setSerializedData:(id)arg1;
- (void)setTrackingDescription:(id)arg1;
- (id)trackingDescription;
- (struct __CFHTTPMessage { }*)copyMessage;
- (void)setRequest:(id)arg1;
- (id)serializedData;
- (void)setStatusCode:(int)arg1;
- (int)statusCode;
- (id)request;
- (void)dealloc;
- (void)setStatusDescription:(id)arg1;

@end
