/* Generated by RuntimeBrowser.
   Image: /private/var/mobile/Containers/Bundle/Application/DDE3370B-7D9E-43B6-9A8A-C891DDE1C4A0/OCRuntime.app/OCRuntime
 */

@class NSData;

@interface HTTPDataResponse : NSObject <HTTPResponse> {
    unsigned int offset;
    NSData *data;
}


- (BOOL)isDone;
- (id)readDataOfLength:(unsigned int)arg1;
- (unsigned long long)offset;
- (void)setOffset:(unsigned long long)arg1;
- (id)initWithData:(id)arg1;
- (void)dealloc;
- (unsigned long long)contentLength;

@end
