/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKPreference : NSObject  {
}

+ (BOOL)jsContextInspectable;
+ (BOOL)logDocumentXML;
+ (BOOL)ignoreHTTPCache;
+ (unsigned int)logLevel;


@end
