/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@class ISOpenURLRequest;

@interface ISOpenURLOperation : ISOperation  {
    ISOpenURLRequest *_request;
}

@property(readonly) ISOpenURLRequest * openURLRequest;


- (id)openURLRequest;
- (id)_newSortedTargetsArray;
- (BOOL)_openURL:(id)arg1;
- (id)initWithOpenURLRequest:(id)arg1;
- (void)run;
- (void)dealloc;
- (id)init;

@end
