/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSString, NSDictionary;

@interface KNAnimationAttributes : NSObject <NSCopying> {
    NSString *mEffect;
    NSDictionary *mAttributes;
}

@property(readonly) NSString * effect;
@property(readonly) NSDictionary * attributes;

+ (BOOL)customAttributeKeyIsValid:(id)arg1;
+ (id)attributesWithEffect:(id)arg1 attributes:(id)arg2;
+ (id)supportedCustomAttributes;

- (id)valueForAttributeKey:(id)arg1;
- (id)attributes;
- (id)effect;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)dealloc;
- (id)attributesByRemovingAttributeForKey:(id)arg1;
- (id)attributesByAddingMissingAttributesFromDictionary:(id)arg1;
- (id)attributesByChangingEffectToEffect:(id)arg1;
- (BOOL)containsAttributeForKey:(id)arg1;
- (id)attributesBySettingValue:(id)arg1 forAttributeKey:(id)arg2;
- (id)initWithEffect:(id)arg1 attributes:(id)arg2;
- (id)attributesByAddingAttributesFromDictionary:(id)arg1;

@end
