/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class TSDGLVoronoiTriangleData;

@interface KNBuildCrumbleSystem : TSDGLParticleSystem  {
    TSDGLVoronoiTriangleData *_voronoiTriangleData;
    struct { struct { float x_1_1_1; float x_1_1_2; } x1; struct { float x_2_1_1; float x_2_1_2; float x_2_1_3; } x2; struct { float x_3_1_1; float x_3_1_2; float x_3_1_3; } x3; struct { float x_4_1_1; float x_4_1_2; } x4; } *_cellParameters;
    float _speedMaxLimiter;
    float _speedMax;
    float _rotationMax;
    float _lifeSpanRandomness;
    float _lifeSpanDelay;
}

@property float speedMaxLimiter;
@property float speedMax;
@property float rotationMax;
@property float lifeSpanRandomness;
@property float lifeSpanDelay;

+ (BOOL)willOverrideGeometry;
+ (unsigned int)numberOfVerticesPerParticle;

- (void)dealloc;
- (void)p_setupParameters;
- (float)lifeSpanRandomness;
- (float)lifeSpanDelay;
- (float)speedMaxLimiter;
- (void)setSpeedMaxLimiter:(float)arg1;
- (void)setLifeSpanRandomness:(float)arg1;
- (id)initWithNumberOfParticles:(unsigned int)arg1 objectSize:(struct CGSize { float x1; float x2; })arg2 slideSize:(struct CGSize { float x1; float x2; })arg3 duration:(float)arg4 direction:(unsigned int)arg5 shader:(id)arg6 percentOfCellsToSplit:(float)arg7;
- (void)setSpeedMax:(float)arg1;
- (void)setLifeSpanDelay:(float)arg1;
- (void)setRotationMax:(float)arg1;
- (struct { float x1; float x2; })lifeSpanAtIndexPoint:(struct CGPoint { float x1; float x2; })arg1;
- (struct { float x1; float x2; float x3; })rotationAtIndexPoint:(struct CGPoint { float x1; float x2; })arg1;
- (struct { float x1; float x2; float x3; })speedAtIndexPoint:(struct CGPoint { float x1; float x2; })arg1;
- (struct { float x1; float x2; })centerAtIndexPoint:(struct CGPoint { float x1; float x2; })arg1;
- (struct { float x1; float x2; })vertexPositionAtVertexIndex:(unsigned int)arg1 particleIndexPoint:(struct CGPoint { float x1; float x2; })arg2;
- (float)rotationMax;
- (float)speedMax;

@end
