/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface KNMacMutableUILayout : KNMacUILayout  {
}

@property(getter=isShowingSidebar) BOOL showingSidebar;
@property int sidebarViewMode;
@property(getter=isShowingLightTable) BOOL showingLightTable;
@property(getter=isShowingPresenterNotes) BOOL showingPresenterNotes;
@property(getter=isShowingInspectorPane) BOOL showingInspectorPane;
@property int inspectorPaneViewMode;
@property(getter=isShowingMasterSlides) BOOL showingMasterSlides;


- (void)setShowingMasterSlides:(BOOL)arg1;
- (void)setInspectorPaneViewMode:(int)arg1;
- (void)setShowingInspectorPane:(BOOL)arg1;
- (void)setShowingLightTable:(BOOL)arg1;
- (void)setShowingPresenterNotes:(BOOL)arg1;
- (void)setSidebarViewMode:(int)arg1;
- (void)setShowingSidebar:(BOOL)arg1;

@end
