/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MapsSupport.framework/MapsSupport
 */

@class MSPSearchRequestStorage, NSData, <GEOMapItemPrivate>, <RAPUserDirectionRequest>;

@interface MapsDirectionsSearch : NSObject <MapsHistoryPersisting> {
    MSPSearchRequestStorage *_storage;
    <GEOMapItemPrivate> *_start;
    <GEOMapItemPrivate> *_destination;
}

@property(readonly) <GEOMapItemPrivate> * start;
@property(readonly) <GEOMapItemPrivate> * destination;
@property(readonly) BOOL startsAtCurrentLocation;
@property(readonly) int transportType;
@property(readonly) <RAPUserDirectionRequest> * rapUserDirectionRequest;
@property(readonly) NSData * data;


- (int)transportType;
- (id)rapUserDirectionRequest;
- (BOOL)startsAtCurrentLocation;
- (id)initWithSearchRequestStorage:(id)arg1;
- (void).cxx_destruct;
- (id)destination;
- (id)data;
- (id)start;

@end
