/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@class NSString, NSData;

@interface MCPlainCertificatePayload : MCCertificatePayload  {
    NSString *_certificateFileName;
    NSData *_certificateData;
    NSString *_password;
    int _dataEncoding;
}

@property(retain,readonly) NSString * certificateFileName;
@property(retain,readonly) NSData * certificateData;
@property(readonly) int dataEncoding;
@property(retain,readonly) NSString * password;

+ (id)localizedPluralForm;
+ (id)localizedSingularForm;
+ (id)typeStrings;

- (BOOL)isSigned;
- (id)certificateData;
- (int)dataEncoding;
- (id)certificateFileName;
- (id)persistentResourceID;
- (BOOL)isIdentity;
- (struct __SecCertificate { }*)copyCertificate;
- (id)installationWarnings;
- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id*)arg3;
- (void).cxx_destruct;
- (id)description;
- (id)password;

@end
