/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OITSDBezierPath;

@interface MFPPath : NSObject  {
    OITSDBezierPath *mPath;
}


- (id)initWithPath:(id)arg1;
- (id)path;
- (void)dealloc;

@end
