/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class <MKLocationProviderDelegate>, NSString, CLLocationManager, NSLock, NSBundle;

@interface MKCoreLocationProvider : NSObject <CLLocationManagerDelegate, CLLocationManagerVehicleDelegate, MKLocationProvider> {
    CLLocationManager *_clLocationManager;
    <MKLocationProviderDelegate> *_delegate;
    BOOL _locationServicesPreferencesDialogEnabled;
    int _authorizationStatus;
    NSBundle *_effectiveBundle;
    NSString *_effectiveBundleIdentifier;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _authorizationRequestBlock;

    BOOL _waitingForAuthorization;
    BOOL _hasQueriedAuthorization;
    NSLock *_authorizationLock;
}

@property(readonly) CLLocationManager * _clLocationManager;
@property <MKLocationProviderDelegate> * delegate;
@property(retain) NSBundle * effectiveBundle;
@property(copy) NSString * effectiveBundleIdentifier;
@property double desiredAccuracy;
@property(getter=isLocationServicesPreferencesDialogEnabled) BOOL locationServicesPreferencesDialogEnabled;
@property double distanceFilter;
@property BOOL matchInfoEnabled;
@property int headingOrientation;
@property(copy) id authorizationRequestBlock;
@property(readonly) double expectedGpsUpdateInterval;
@property(readonly) int authorizationStatus;
@property(readonly) BOOL airplaneModeBlocksLocation;
@property int activityType;
@property(readonly) BOOL usesCLMapCorrection;
@property(readonly) BOOL isSimulation;


- (void)setActivityType:(int)arg1;
- (void)startUpdatingHeading;
- (void)stopUpdatingHeading;
- (void)locationManagerDidResumeLocationUpdates:(id)arg1;
- (void)locationManagerDidPauseLocationUpdates:(id)arg1;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (BOOL)locationManagerShouldDisplayHeadingCalibration:(id)arg1;
- (void)locationManager:(id)arg1 didUpdateHeading:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)setHeadingOrientation:(int)arg1;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation;
- (void)setDesiredAccuracy:(double)arg1;
- (void)setDistanceFilter:(double)arg1;
- (int)authorizationStatus;
- (void).cxx_destruct;
- (int)activityType;
- (id)effectiveBundle;
- (id)delegate;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (id)init;
- (BOOL)isSimulation;
- (BOOL)usesCLMapCorrection;
- (BOOL)airplaneModeBlocksLocation;
- (void)setAuthorizationRequestBlock:(id)arg1;
- (id)authorizationRequestBlock;
- (BOOL)matchInfoEnabled;
- (void)setEffectiveBundleIdentifier:(id)arg1;
- (id)effectiveBundleIdentifier;
- (void)setEffectiveBundle:(id)arg1;
- (void)locationManager:(id)arg1 didUpdateVehicleHeading:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateVehicleSpeed:(id)arg2;
- (void)dismissHeadingCalibrationDisplay;
- (int)headingOrientation;
- (void)setMatchInfoEnabled:(BOOL)arg1;
- (BOOL)isLocationServicesPreferencesDialogEnabled;
- (void)_resetForNewEffectiveBundle;
- (double)desiredAccuracy;
- (void)stopUpdatingVehicleHeading;
- (void)startUpdatingVehicleHeading;
- (void)stopUpdatingVehicleSpeed;
- (void)startUpdatingVehicleSpeed;
- (id)_clLocationManager;
- (void)_updateAuthorizationStatus;
- (void)_createCLLocationManager;
- (void)setLocationServicesPreferencesDialogEnabled:(BOOL)arg1;
- (double)expectedGpsUpdateInterval;
- (double)distanceFilter;

@end
