/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@class MKMapItem, <MKMapServiceTicket>, <MKReverseGeocoderDelegate>;

@interface MKReverseGeocoderInternal : NSObject  {
    struct { 
        double latitude; 
        double longitude; 
    } coordinate;
    <MKReverseGeocoderDelegate> *delegate;
    MKMapItem *mapItem;
    <MKMapServiceTicket> *ticket;
    BOOL querying;
}


- (void).cxx_destruct;

@end
