/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@class _MKUserTrackingButton, UIToolbar, _MKUserTrackingButtonController, UINavigationBar, MKMapView, UIButton, UIView, UIImage, <MKUserTrackingView>;

@interface MKUserTrackingBarButtonItem : UIBarButtonItem <MKUserTrackingButtonTarget> {
    BOOL _hasCustomAssociatedView;
    UIButton *_customButton;
    _MKUserTrackingButtonController *_controller;
    _MKUserTrackingButton *_userTrackingButton;
    BOOL _isLegacy;
    UIImage *_trackingEmptyImage;
    UIImage *_trackingNoneImage;
    UIImage *_trackingFollowImage;
    UIImage *_trackingFollowWithHeadingImage;
    UIToolbar *_toolbar;
    UINavigationBar *_navigationBar;
    UIView *_associatedView;
}

@property(retain) MKMapView * mapView;
@property(getter=_selectsWhenTracking,setter=_setSelectsWhenTracking:) BOOL selectsWhenTracking;
@property(setter=_setState:) int _state;
@property(retain) UIToolbar * _toolbar;
@property(retain) UINavigationBar * _navigationBar;
@property(retain) UIView * _associatedView;
@property(setter=_setUserTrackingView:,retain) <MKUserTrackingView> * _userTrackingView;

+ (Class)_activityIndicatorClass;

- (void).cxx_destruct;
- (int)_activityIndicatorStyle;
- (void)_setState:(int)arg1;
- (id)createViewForToolbar:(id)arg1;
- (BOOL)_isInMiniBar;
- (int)_state;
- (id)createViewForNavigationItem:(id)arg1;
- (void)setEnabled:(BOOL)arg1;
- (id)mapView;
- (void)setMapView:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)dealloc;
- (id)init;
- (id)_navigationBar;
- (id)_toolbar;
- (void)_setLandscapeImagePhone:(id)arg1 forUserTrackingMode:(int)arg2;
- (id)_landscapeImagePhoneForUserTrackingMode:(int)arg1;
- (void)_setImage:(id)arg1 forUserTrackingMode:(int)arg2;
- (id)_imageForUserTrackingMode:(int)arg1;
- (BOOL)_isHighlightedForState:(int)arg1;
- (void)_updateForState:(int)arg1;
- (int)_styleForState:(int)arg1;
- (void)set_navigationBar:(id)arg1;
- (void)_repositionViews;
- (void)set_toolbar:(id)arg1;
- (void)_setUserTrackingView:(id)arg1;
- (id)_userTrackingView;
- (id)_associatedView;
- (id)_trackingFollowWithHeadingImage;
- (id)_trackingFollowImage;
- (id)_trackingEmptyImage;
- (id)_imageForState:(int)arg1 controlState:(unsigned int)arg2;
- (void)_setSelectsWhenTracking:(BOOL)arg1;
- (BOOL)_selectsWhenTracking;
- (id)initWithMapView:(id)arg1;
- (void)set_associatedView:(id)arg1;
- (id)_trackingNoneImage;
- (void)_goToNextMode:(id)arg1;

@end
