/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@class NSMutableDictionary, MLContentRating, MLMovieProperties, NSDictionary, NSString, NSData, NSArray;

@interface MLTrackImport : NSObject <NSCopying> {
    NSData *_artworkData;
    NSString *_assetFilePath;
    NSArray *_chapters;
    NSMutableDictionary *_properties;
    BOOL _shouldAddToPurchasedPlaylist;
    BOOL _assignArtworkCacheIDFromAlbum;
}

@property(copy) NSData * artworkData;
@property(copy) NSString * assetFilePath;
@property(copy) NSArray * chapters;
@property(copy) MLContentRating * contentRating;
@property unsigned long mediaType;
@property(copy) MLMovieProperties * movieProperties;
@property BOOL shouldAddToPurchasedPlaylist;
@property BOOL assignArtworkCacheIDFromAlbum;
@property(copy,readonly) NSDictionary * entityProperties;

+ (void)initialize;

- (void)setShouldAddToPurchasedPlaylist:(BOOL)arg1;
- (BOOL)shouldAddToPurchasedPlaylist;
- (void)setChapters:(id)arg1;
- (id)chapters;
- (void)setAssignArtworkCacheIDFromAlbum:(BOOL)arg1;
- (BOOL)assignArtworkCacheIDFromAlbum;
- (void)setAssetFilePath:(id)arg1;
- (id)assetFilePath;
- (void)setArtworkData:(id)arg1;
- (id)artworkData;
- (void)normalizeEntityProperties;
- (id)copyEntityProperties;
- (void)setMovieProperties:(id)arg1;
- (void)setContentRating:(id)arg1;
- (id)movieProperties;
- (id)entityProperties;
- (id)contentRating;
- (id)valueForEntityProperty:(id)arg1;
- (void)_addSortStrings;
- (void)setValue:(id)arg1 forEntityProperty:(id)arg2;
- (void)setMediaType:(unsigned long)arg1;
- (unsigned long)mediaType;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;

@end
