/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
 */

@class UITapGestureRecognizer, UIPanGestureRecognizer, <MPURatingControlDelegate>, NSMutableArray;

@interface MPURatingControl : UIControl  {
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIPanGestureRecognizer *_panGestureRecognizer;
    NSMutableArray *_imageViews;
    <MPURatingControlDelegate> *_delegate;
    float _rating;
    struct UIEdgeInsets { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _hitTestEdgeInsets;
}

@property <MPURatingControlDelegate> * delegate;
@property struct UIEdgeInsets { float x1; float x2; float x3; float x4; } hitTestEdgeInsets;
@property float rating;

+ (id)ratingDotImage;
+ (id)ratingStarImage;

- (void)setRating:(float)arg1 animated:(BOOL)arg2;
- (float)ratingValueForLocationInView:(struct CGPoint { float x1; float x2; })arg1;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })hitTestEdgeInsets;
- (void)_updateImageViewsForRatingAnimated:(BOOL)arg1;
- (void)setHitTestEdgeInsets:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (void)_handleTapGesture:(id)arg1;
- (void)_handlePanGesture:(id)arg1;
- (void).cxx_destruct;
- (id)delegate;
- (void)layoutSubviews;
- (BOOL)pointInside:(struct CGPoint { float x1; float x2; })arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setDelegate:(id)arg1;
- (float)rating;
- (void)setRating:(float)arg1;

@end
