/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSArray, NSData, NSDictionary, NSMutableDictionary;

@interface MRMediaRemoteOriginClient : NSObject  {
    BOOL _canBeNowPlayingApp;
    BOOL _isOverrideApp;
    BOOL _keepAlive;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _commandHandlerBlock;

    NSMutableDictionary *_commandHandlerBlocks;
    int _notifyRestoreClientStateForLaunch;
    int _notifyDidLaunchToken;
    NSData *_nowPlayingArtworkData;
    NSDictionary *_nowPlayingInfo;
    struct _MROrigin { } *_origin;
    unsigned int _routeDiscoveryMode;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _playbackStateRequestHandler;

}

@property(readonly) struct _MROrigin { }* origin;
@property BOOL canBeNowPlayingApp;
@property BOOL isOverrideApp;
@property BOOL keepAlive;
@property(retain) NSData * nowPlayingArtworkData;
@property(retain) NSDictionary * nowPlayingInfo;
@property unsigned int routeDiscoveryMode;
@property(copy,readonly) NSArray * commandHandlerBlocks;
@property(copy) id playbackStateRequestHandler;


- (id)initWithOrigin:(struct _MROrigin { }*)arg1;
- (void)setNowPlayingInfo:(id)arg1;
- (BOOL)keepAlive;
- (BOOL)canBeNowPlayingApp;
- (void)_avSystemControllerServerConnectionDiedNotification:(id)arg1;
- (id)commandHandlerBlocks;
- (id)playbackStateRequestHandler;
- (void)addCommandHandlerBlock:(id)arg1 forKey:(id)arg2;
- (void)removeCommandHandlerBlockForKey:(id)arg1;
- (void)setPlaybackStateRequestHandler:(id)arg1;
- (void)setNowPlayingArtworkData:(id)arg1;
- (id)nowPlayingArtworkData;
- (void)setKeepAlive:(BOOL)arg1;
- (void)setIsOverrideApp:(BOOL)arg1;
- (BOOL)isOverrideApp;
- (void)setCanBeNowPlayingApp:(BOOL)arg1;
- (struct _MROrigin { }*)origin;
- (void)dealloc;
- (id)nowPlayingInfo;
- (void)setRouteDiscoveryMode:(unsigned int)arg1;
- (unsigned int)routeDiscoveryMode;

@end
