/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MapsSupport.framework/MapsSupport
 */

@class GEOMapItemStorage, PBUnknownFields;

@interface MSPPlaceBookmark : PBCodable <NSCopying> {
    PBUnknownFields *_unknownFields;
    GEOMapItemStorage *_mapItem;
}

@property(readonly) BOOL hasMapItem;
@property(retain) GEOMapItemStorage * mapItem;
@property(readonly) PBUnknownFields * unknownFields;


- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (BOOL)hasMapItem;
- (id)unknownFields;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)setMapItem:(id)arg1;
- (id)mapItem;
- (id)description;

@end
