/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
 */

@interface MSTimerGate : NSObject  {
    BOOL _enabled;
}

@property BOOL enabled;


- (void)disable;
- (void)enable;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)enabled;
- (id)init;

@end
