/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
 */

@class NSObject<OS_dispatch_source>, NSMapTable, NSObject<OS_dispatch_queue>;

@interface MSVXPCTransactionController : NSObject  {
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSMapTable *_openTransactions;
    BOOL _inTransaction;
    NSObject<OS_dispatch_source> *_signalUSR2DispatchSource;
}

@property(getter=isInTransaction,readonly) BOOL inTransaction;

+ (id)sharedInstance;

- (void)_saveActiveTransactionsToFile;
- (void)_onQueueCleanupEndedTransactions;
- (void)_onQueueUpdateInternalTransactionState;
- (void)_tearDownSignalHandler;
- (void)_setupSignalHandler;
- (void)removeActiveTransaction:(id)arg1;
- (void)addActiveTransaction:(id)arg1;
- (id)activeTransactions;
- (BOOL)isTransactionActive:(id)arg1;
- (BOOL)isInTransaction;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end
