/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class MTLTextureDescriptor;

@interface MTLDebugTexture : MTLToolsTexture  {
    BOOL _purgeableStateHasBeenSet;
    MTLTextureDescriptor *_descriptor;
    unsigned int _offset;
    unsigned int _bytesPerRow;
    unsigned int _plane;
    unsigned int _purgeableState;
}

@property(copy,readonly) MTLTextureDescriptor * descriptor;
@property(readonly) unsigned int offset;
@property(readonly) unsigned int bytesPerRow;
@property(readonly) unsigned int plane;
@property(readonly) unsigned int purgeableState;
@property(readonly) BOOL purgeableStateHasBeenSet;


- (void).cxx_destruct;
- (unsigned int)offset;
- (unsigned int)bytesPerRow;
- (unsigned int)plane;
- (id)initWithBaseTexture:(id)arg1 texture:(id)arg2 pixelFormat:(unsigned int)arg3;
- (id)initWithBaseTexture:(id)arg1 texture:(id)arg2 descriptor:(id)arg3;
- (id)initWithBaseTexture:(id)arg1 device:(id)arg2 descriptor:(id)arg3 plane:(unsigned int)arg4;
- (id)initWithBaseTexture:(id)arg1 device:(id)arg2 descriptor:(id)arg3;
- (BOOL)purgeableStateHasBeenSet;
- (unsigned int)purgeableState;
- (id)initWithBaseTexture:(id)arg1 buffer:(id)arg2 descriptor:(id)arg3 offset:(unsigned int)arg4 bytesPerRow:(unsigned int)arg5;
- (id)newTextureViewWithPixelFormat:(unsigned int)arg1;
- (unsigned int)setPurgeableState:(unsigned int)arg1;
- (id)descriptor;

@end
