/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class <MTLDevice>, NSString;

@interface MTLDepthStencilState : NSObject <MTLDepthStencilState> {
    <MTLDevice> *_device;
    NSString *_label;
}

@property(readonly) <MTLDevice> * device;
@property(readonly) NSString * label;


- (id)device;
- (id)label;
- (id)initWithDevice:(id)arg1 depthStencilDescriptor:(id)arg2;
- (void)dealloc;

@end
