/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class <MTLDevice>, NSString;

@interface MTLFramebuffer : NSObject  {
    <MTLDevice> *_device;
    NSString *_label;
    unsigned int _width;
    unsigned int _height;
}

@property(readonly) <MTLDevice> * device;
@property(copy) NSString * label;
@property(readonly) unsigned int width;
@property(readonly) unsigned int height;


- (id)device;
- (void)setLabel:(id)arg1;
- (unsigned int)height;
- (id)label;
- (unsigned int)width;
- (id)initWithDevice:(id)arg1 descriptor:(id)arg2;
- (void)dealloc;

@end
