/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class NSArray, NSString, MTLLibraryShared, <MTLDevice>;

@interface MTLFunction : NSObject <MTLFunctionSPI> {
    struct MTLFunctionOffsets { 
        unsigned long long publicArguments; 
        unsigned long long privateArguments; 
    } _offsets;
    unsigned char _functionArgumentsInitialized;
    unsigned char _stageInArgumentsInitialized;
    <MTLDevice> *_device;
    unsigned int _functionType;
    NSArray *_functionArguments;
    NSString *_name;
    id _vendorPrivate;
    NSArray *_stageInArguments;
    int _lineNumber;
    NSString *_filePath;
    MTLLibraryShared *_libraryData;
    int _bitCodeOffset;
    struct { 
        unsigned char key[32]; 
    } _bitcodeHash;
}

@property(readonly) <MTLDevice> * device;
@property(readonly) unsigned int functionType;
@property(readonly) NSArray * functionArguments;
@property(readonly) NSArray * stageInArguments;
@property(readonly) NSString * name;
@property(readonly) MTLLibraryShared * libraryData;
@property(copy) NSString * filePath;
@property int lineNumber;
@property int bitCodeOffset;
@property(readonly) struct { unsigned char x1[32]; } bitcodeHash;
@property(readonly) id vendorPrivate;


- (id)device;
- (id)filePath;
- (void)setFilePath:(id)arg1;
- (id).cxx_construct;
- (struct { unsigned char x1[32]; })bitcodeHash;
- (int)bitCodeOffset;
- (id)vendorPrivate;
- (void)setVendorPrivate:(id)arg1;
- (void)initializePrivateMetadata;
- (id)libraryData;
- (void)setLineNumber:(int)arg1;
- (void)setBitCodeOffset:(int)arg1;
- (id)initWithName:(id)arg1 bitcodeHash:(const struct { unsigned char x1[32]; }*)arg2 type:(unsigned int)arg3 libraryData:(id)arg4 offsets:(struct MTLFunctionOffsets { unsigned long long x1; unsigned long long x2; }*)arg5 device:(id)arg6;
- (unsigned int)functionType;
- (id)stageInArguments;
- (id)functionArguments;
- (id)name;
- (void)dealloc;
- (int)lineNumber;

@end
