/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLIOAccelRenderCommandEncoder : MTLIOAccelCommandEncoder  {
}


- (id)initWithCommandBuffer:(id)arg1 framebuffer:(id)arg2;

@end
