/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Notes.framework/Notes
 */

@class NoteObject, NSString;

@interface NoteAttachmentObject : NSManagedObject  {
}

@property(retain) NSString * contentID;
@property(retain) NSString * filename;
@property(retain) NSString * mimeType;
@property(retain) NoteObject * note;

+ (BOOL)migrateAttachmentRelatedFilesInContext:(id)arg1 error:(id*)arg2;
+ (BOOL)applyFileAttributesForAttachment:(id)arg1 error:(id*)arg2;
+ (BOOL)migrateFileForAttachment:(id)arg1 toCurrentAttachmentPathWithError:(id*)arg2;

- (void)prepareForDeletion;
- (id)attachmentDataWithError:(id*)arg1;
- (id)attachmentDataFileURLWithError:(id*)arg1;
- (BOOL)persistAttachmentData:(id)arg1 error:(id*)arg2;

@end
