/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSEncodingDetector : NSObject  {
    unsigned long _encoding;
    unsigned long _givenNumBytes;
    unsigned long _numChars;
    unsigned long _numMultiByteChars;
    unsigned long _numSingleBytechars;
    unsigned long _skipBytes;
    unsigned long _numZeroBytes;
    unsigned long _mostFrqChars;
    unsigned long _numBigrams;
    unsigned long _numRep;
    unsigned long _numDirect;
    unsigned long _numBase64;
    unsigned long _numSeq;
    unsigned long _numTrigram;
    unsigned long _numLower;
    unsigned long _numHigher;
    double _weight;
    BOOL _hasBase64;
    BOOL _isBigEndian;
    BOOL _hasBOM;
    unsigned int _tag;
}

+ (id)encodingDetectorWithEncoding:(unsigned int)arg1;

- (void)reset;
- (id)init;
- (double)multiBytesRatio;
- (double)confidenceWith2Chars;
- (double)confidence;
- (unsigned long)maxSkipBytes;
- (double)bytesRatio;
- (void)softReset;
- (unsigned long)recognizeString:(const char *)arg1 withDataLength:(unsigned long)arg2 withReplacement:(const char *)arg3 withReplacementLength:(unsigned long)arg4 inNewData:(char *)arg5 maxBufferLength:(unsigned long)arg6 actualBufferLength:(unsigned int*)arg7;

@end
