/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSKnownKeysMappingStrategy2 : NSKnownKeysMappingStrategy1  {
}


- (id)initForKeys:(id)arg1;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (unsigned int)retainCount;
- (void)dealloc;
- (id)retain;
- (oneway void)release;
- (id)init;
- (id)initForKeys:(id*)arg1 count:(unsigned int)arg2;
- (id)_setupForKeys:(id*)arg1 count:(unsigned int)arg2 table:(void*)arg3 inData:(id)arg4;

@end
