/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSString;

@interface NSLock : NSObject <NSLocking> {
    void *_priv;
}

@property(copy) NSString * name;

+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (void)unlock;
- (void)lock;
- (id)name;
- (void)setName:(id)arg1;
- (id)description;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (BOOL)lockBeforeDate:(id)arg1;
- (BOOL)tryLock;
- (void)mf_waitForLock;

@end
