/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@interface NSSet : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration, PQLBindable> {
}

@property(readonly) unsigned int count;

+ (id)setWithObjects:(const id*)arg1 count:(unsigned int)arg2;
+ (id)setWithArray:(id)arg1;
+ (id)setWithObjects:(id)arg1;
+ (BOOL)supportsSecureCoding;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)setWithObject:(id)arg1;
+ (id)setWithSet:(id)arg1;
+ (id)set;
+ (id)setWithSet:(id)arg1 copyItems:(BOOL)arg2;
+ (id)setWithOrderedSet:(id)arg1;
+ (id)setWithOrderedSet:(id)arg1 copyItems:(BOOL)arg2;
+ (id)setWithOrderedSet:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
+ (id)setWithOrderedSet:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2 copyItems:(BOOL)arg3;
+ (id)setWithArray:(id)arg1 copyItems:(BOOL)arg2;
+ (id)setWithArray:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
+ (id)newSetWithObjects:(const id*)arg1 count:(unsigned int)arg2;
+ (id)setWithArray:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2 copyItems:(BOOL)arg3;
+ (BOOL)supportsSecureCoding;
+ (id)intersectionOfSets:(id)arg1;
+ (BOOL)set:(id)arg1 isEqualToSet:(id)arg2;
+ (id)intersectionOfSets:(id)arg1;
+ (BOOL)set:(id)arg1 isEqualToSet:(id)arg2;
+ (id)intersectionOfSets:(id)arg1;
+ (BOOL)set:(id)arg1 isEqualToSet:(id)arg2;

- (id)initWithOrderedSet:(id)arg1;
- (BOOL)isSubsetOfOrderedSet:(id)arg1;
- (id)descriptionWithLocale:(id)arg1;
- (unsigned int)countForObject:(id)arg1;
- (id)setByAddingObject:(id)arg1;
- (id)initWithSet:(id)arg1;
- (id)initWithObject:(id)arg1;
- (id)sortedArrayWithOptions:(unsigned int)arg1 usingComparator:(id)arg2;
- (id)setByAddingObjectsFromArray:(id)arg1;
- (id)sortedArrayUsingComparator:(id)arg1;
- (id)member:(id)arg1;
- (id)initWithArray:(id)arg1 copyItems:(BOOL)arg2;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)intersectsSet:(id)arg1;
- (BOOL)isSubsetOfSet:(id)arg1;
- (BOOL)isEqualToSet:(id)arg1;
- (id)initWithObjects:(const id*)arg1 count:(unsigned int)arg2;
- (void)getObjects:(id*)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (id)setByAddingObjectsFromSet:(id)arg1;
- (void)enumerateObjectsWithOptions:(unsigned int)arg1 usingBlock:(id)arg2;
- (id)initWithArray:(id)arg1;
- (id)objectsPassingTest:(id)arg1;
- (id)objectEnumerator;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)makeObjectsPerformSelector:(SEL)arg1 withObject:(id)arg2;
- (id)anyObject;
- (id)initWithObjects:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)enumerateObjectsUsingBlock:(id)arg1;
- (void)makeObjectsPerformSelector:(SEL)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)containsObject:(id)arg1;
- (unsigned int)countByEnumeratingWithState:(struct { unsigned long x1; id *x2; unsigned long *x3; unsigned long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned int)arg3;
- (id)allObjects;
- (id)description;
- (unsigned int)count;
- (id)members:(id)arg1 notFoundMarker:(id)arg2;
- (id)initWithOrderedSet:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (id)initWithArray:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (id)objectPassingTest:(id)arg1;
- (void)getObjects:(id*)arg1 count:(unsigned int)arg2;
- (id)initWithOrderedSet:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2 copyItems:(BOOL)arg3;
- (id)objectWithOptions:(unsigned int)arg1 passingTest:(id)arg2;
- (void)__applyValues:(int (*)())arg1 context:(void*)arg2;
- (BOOL)__getValue:(id*)arg1 forObj:(id)arg2;
- (unsigned long)_cfTypeID;
- (BOOL)intersectsOrderedSet:(id)arg1;
- (id)initWithOrderedSet:(id)arg1 copyItems:(BOOL)arg2;
- (id)initWithArray:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2 copyItems:(BOOL)arg3;
- (id)initWithSet:(id)arg1 copyItems:(BOOL)arg2;
- (id)objectsWithOptions:(unsigned int)arg1 passingTest:(id)arg2;
- (void)getObjects:(id*)arg1;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned int)arg2;
- (BOOL)isNSSet__;
- (id)valueForKeyPath:(id)arg1;
- (id)valueForKey:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)_distinctUnionOfSetsForKeyPath:(id)arg1;
- (id)_distinctUnionOfObjectsForKeyPath:(id)arg1;
- (id)_distinctUnionOfArraysForKeyPath:(id)arg1;
- (id)_minForKeyPath:(id)arg1;
- (id)_maxForKeyPath:(id)arg1;
- (id)_countForKeyPath:(id)arg1;
- (id)_avgForKeyPath:(id)arg1;
- (id)_sumForKeyPath:(id)arg1;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2 context:(void*)arg3;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned int)arg3 context:(void*)arg4;
- (Class)classForCoder;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)sortedArrayUsingDescriptors:(id)arg1;
- (id)filteredSetUsingPredicate:(id)arg1;
- (id)replacementObjectForPortCoder:(id)arg1;
- (id)__imSetByApplyingBlock:(id)arg1;
- (void)__imForEach:(id)arg1;
- (id)CAMLType;
- (void)encodeWithCAMLWriter:(id)arg1;
- (void)CKAssignToContainerWithID:(id)arg1;
- (id)setByIntersectingWithSet:(id)arg1;
- (id)CalMutableRecursiveCopy;
- (id)allObjectsWithClass:(Class)arg1;
- (id)DACompactDescription;
- (id)mf_getAllObjectsAsArray;
- (unsigned int)pl_countOfObjectsPassingTest:(id)arg1;
- (id)_gkValuesForKeyPath:(id)arg1;
- (id)_gkMapWithBlock:(id)arg1;
- (id)_gkSetByRemovingObject:(id)arg1;
- (id)_gkDistinctValuesForKeyPath:(id)arg1;
- (id)_gkMapDictionaryWithKeyPath:(id)arg1;
- (id)_gkMapDictionaryWithKeyPath:(id)arg1 valueKeyPath:(id)arg2;
- (id)allObjectsWithClass:(Class)arg1;
- (void)sqliteBind:(struct sqlite3_stmt { }*)arg1 index:(int)arg2;
- (BOOL)containsObjectIdenticalTo:(id)arg1;
- (id)safari_arrayByMappingObjectsUsingBlock:(id)arg1;
- (BOOL)containsObjectIdenticalTo:(id)arg1;
- (BOOL)containsObjectIdenticalTo:(id)arg1;
- (BOOL)containsStyleOrVariationOfStyle:(id)arg1;
- (BOOL)hasVariations;

@end
