/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OADColor, OADLineJoin, OADLineEnd, OADDash, OADFill;

@interface OADStroke : OADProperties <NSCopying> {
    OADColor *mColor;
    OADFill *mFill;
    OADDash *mDash;
    OADLineJoin *mJoin;
    OADLineEnd *mHead;
    OADLineEnd *mTail;
    float mWidth;
    unsigned char mCap;
    unsigned char mCompoundType;
    unsigned char mPenAlignment;
    unsigned int mIsColorOverridden : 1;
    unsigned int mIsCompoundTypeOverridden : 1;
    unsigned int mIsCapOverridden : 1;
    unsigned int mIsWidthOverridden : 1;
    unsigned int mIsJoinOverridden : 1;
    unsigned int mIsDashOverridden : 1;
    unsigned int mIsFillOverridden : 1;
    unsigned int mIsPenAlignmentOverridden : 1;
}

@property(retain) OADLineEnd * head;
@property(retain) OADLineEnd * tail;

+ (id)nullStroke;
+ (id)blackStroke;
+ (id)defaultProperties;

- (void)setParent:(id)arg1;
- (id)head;
- (int)penAlignment;
- (BOOL)isPenAlignmentOverridden;
- (BOOL)isJoinOverridden;
- (id)join;
- (void)setTail:(id)arg1;
- (void)setHead:(id)arg1;
- (id)initWithDefaults;
- (int)cap;
- (BOOL)isCapOverridden;
- (void)setStyleColor:(id)arg1;
- (void)setJoin:(id)arg1;
- (void)setDash:(id)arg1;
- (void)setPenAlignment:(int)arg1;
- (void)setCompoundType:(int)arg1;
- (void)setCap:(int)arg1;
- (id)tail;
- (void)setFill:(id)arg1;
- (int)compoundType;
- (BOOL)isCompoundTypeOverridden;
- (id)dash;
- (BOOL)isDashOverridden;
- (BOOL)isFillOverridden;
- (BOOL)isColorOverridden;
- (BOOL)isWidthOverridden;
- (void)setWidth:(float)arg1;
- (void)setColor:(id)arg1;
- (id)color;
- (float)width;
- (id)fill;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)init;

@end
