/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface ODIArrow : NSObject  {
}

+ (BOOL)mapIdentifier:(id)arg1 state:(id)arg2;
+ (unsigned int)nodeCountWithState:(id)arg1;
+ (void)mapWithState:(id)arg1 outward:(BOOL)arg2;


@end
