/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class CXNamespace, OAXDrawingState;

@interface ODXState : OCXReadState  {
    CXNamespace *mODXDiagramNamespace;
    OAXDrawingState *mOfficeArtState;
}

@property(retain) CXNamespace * ODXDiagramNamespace;


- (void)setODXDiagramNamespace:(id)arg1;
- (id)officeArtState;
- (id)ODXDiagramNamespace;
- (id)initWithOfficeArtState:(id)arg1;
- (void)setupNSForXMLFormat:(int)arg1;
- (void)dealloc;

@end
