/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString, PDAnimationTarget;

@interface PDSequentialTimeNode : PDTimeNode  {
}

@property(retain) PDAnimationTarget * target;
@property int presetClass;
@property int presetId;
@property int triggerType;
@property int iterateType;
@property double delay;
@property double direction;
@property(retain) NSString * groupId;

+ (id)newSequentialTimeNodeGroupForAnimationInfoWithClass:(Class)arg1;
+ (id)newSequentialTimeNodeGroupForAnimationInfo;
+ (id)newSequentialTimeNodeGroupForAnimationInfoWithClass:(Class)arg1 target:(id)arg2;
+ (id)timeNodeUnion:(id)arg1 initWithClass:(Class)arg2;
+ (unsigned int)buildPartsFromTarget:(id)arg1;

- (int)iterateType;
- (void)setIterateType:(int)arg1;
- (int)triggerType;
- (void)setTriggerType:(int)arg1;
- (int)presetClass;
- (void)setPresetClass:(int)arg1;
- (void)setLevel2ParallelAttribute:(id)arg1;
- (id)level3BehaviorAtNodeIndex:(unsigned int)arg1 level2NodeIndex:(unsigned int)arg2 level1NodeIndex:(unsigned int)arg3;
- (id)level2ParallelTimeNodeGroupAtNodeIndex:(unsigned int)arg1 level1NodeIndex:(unsigned int)arg2;
- (id)level1ParallelTimeNodeGroupAtNodeIndex:(unsigned int)arg1;
- (void)setPresetId:(int)arg1;
- (id)groupId;
- (int)presetId;
- (void)setGroupId:(id)arg1;
- (double)delay;
- (double)direction;
- (void)setDirection:(double)arg1;
- (id)target;
- (void)setTarget:(id)arg1;
- (void)setDelay:(double)arg1;

@end
