/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Photos.framework/Photos
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class CLLocation, NSArray, NSString, PHQuery, NSDate, NSURL;

@interface PHAssetCollection : PHCollection  {
    NSString *_localizedTitle;
    int _assetCollectionType;
    int _assetCollectionSubtype;
    NSDate *_startDate;
    NSDate *_endDate;
    CLLocation *_approximateLocation;
    NSArray *_localizedLocationNames;
    NSArray *_assets;
    PHQuery *_query;
    NSString *_transientIdentifier;
    BOOL _canShowCloudComments;
    BOOL _isPendingPhotoStreamAlbum;
    BOOL _shouldDeleteWhenEmpty;
    BOOL _isLibrary;
    BOOL _isCameraRoll;
    BOOL _isPanoramasCollection;
    BOOL _isWallpaperCollection;
    BOOL _isPhotoStreamCollection;
    BOOL _isCloudSharedAlbum;
    BOOL _isStandInCollection;
    BOOL _isOwnedCloudSharedAlbum;
    BOOL _isMultipleContributorCloudSharedAlbum;
    BOOL _isSmartCollection;
    BOOL _hasUnseenContentBoolValue;
    BOOL _canContributeToCloudSharedAlbum;
    NSString *_title;
    unsigned int _approximateCount;
    unsigned int _approximatePhotosCount;
    unsigned int _approximateVideosCount;
    NSURL *_groupURL;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _sortingComparator;

    NSString *_importSessionID;
    int _pendingItemsCount;
    int _pendingItemsType;
    int _plAlbumKind;
}

@property(readonly) int assetCollectionType;
@property(readonly) int assetCollectionSubtype;
@property(readonly) unsigned int estimatedAssetCount;
@property(readonly) unsigned int estimatedPhotosCount;
@property(readonly) unsigned int estimatedVideosCount;
@property(readonly) NSDate * startDate;
@property(readonly) NSDate * endDate;
@property(readonly) CLLocation * approximateLocation;
@property(readonly) NSArray * localizedLocationNames;
@property(readonly) NSString * title;
@property(readonly) BOOL isPendingPhotoStreamAlbum;
@property(readonly) BOOL shouldDeleteWhenEmpty;
@property(readonly) unsigned int approximateCount;
@property(readonly) unsigned int approximatePhotosCount;
@property(readonly) unsigned int approximateVideosCount;
@property(readonly) BOOL isLibrary;
@property(readonly) BOOL isCameraRoll;
@property(readonly) BOOL isPanoramasCollection;
@property(readonly) BOOL isWallpaperCollection;
@property(readonly) BOOL isPhotoStreamCollection;
@property(readonly) BOOL isCloudSharedAlbum;
@property(readonly) BOOL isStandInCollection;
@property(readonly) BOOL isOwnedCloudSharedAlbum;
@property(readonly) BOOL isMultipleContributorCloudSharedAlbum;
@property(readonly) BOOL isSmartCollection;
@property(readonly) NSURL * groupURL;
@property(copy,readonly) id sortingComparator;
@property(readonly) NSString * importSessionID;
@property(readonly) int pendingItemsCount;
@property(readonly) int pendingItemsType;
@property(readonly) BOOL hasUnseenContentBoolValue;
@property(readonly) BOOL canShowAvalancheStacks;
@property(readonly) BOOL canContributeToCloudSharedAlbum;
@property(readonly) BOOL canShowComments;
@property(readonly) NSString * transientIdentifier;
@property(readonly) int plAlbumKind;
@property(readonly) NSArray * assets;
@property(readonly) PHQuery * query;
@property(getter=_canShowCloudComments,setter=_setCanShowCloudComments:) BOOL _canShowCloudComments;

+ (id)fetchAssetCollectionsWithLocalIdentifiers:(id)arg1 options:(id)arg2;
+ (id)pl_PHAssetCollectionForAssetContainer:(id)arg1;
+ (id)fetchAssetCollectionsWithType:(int)arg1 subtype:(int)arg2 options:(id)arg3;
+ (id)posterImageForAssetCollection:(id)arg1;
+ (id)fetchMomentsWithOptions:(id)arg1;
+ (id)fetchMomentsInMomentList:(id)arg1 options:(id)arg2;
+ (id)transientAssetCollectionWithAssetFetchResult:(id)arg1 title:(id)arg2;
+ (id)transientAssetCollectionWithAssetFetchResult:(id)arg1 title:(id)arg2 identifier:(id)arg3;
+ (id)transientAssetCollectionWithAssets:(id)arg1 title:(id)arg2 identifier:(id)arg3;
+ (id)transientAssetCollectionWithAssets:(id)arg1 title:(id)arg2;
+ (id)fetchAssetCollectionsWithObjectIDs:(id)arg1 options:(id)arg2;
+ (id)fetchAssetCollectionsWithALAssetGroupURLs:(id)arg1 options:(id)arg2;
+ (id)fetchAssetCollectionsWithCloudIdentifiers:(id)arg1 options:(id)arg2;
+ (id)fetchAssetCollectionsContainingAsset:(id)arg1 withType:(int)arg2 options:(id)arg3;
+ (id)identifierCode;
+ (BOOL)managedObjectSupportsTrashedState;
+ (id)propertiesToFetchWithHint:(unsigned int)arg1;
+ (id)managedEntityName;

- (id)endDate;
- (id)startDate;
- (id)approximateLocation;
- (id)localizedLocationNames;
- (BOOL)canShowAvalancheStacks;
- (BOOL)canShowComments;
- (unsigned int)approximateCount;
- (id)assets;
- (BOOL)canPerformEditOperation:(unsigned int)arg1;
- (int)pendingItemsType;
- (int)pendingItemsCount;
- (id)sortingComparator;
- (id)groupURL;
- (id)importSessionID;
- (BOOL)shouldDeleteWhenEmpty;
- (BOOL)canContributeToCloudSharedAlbum;
- (BOOL)isMultipleContributorCloudSharedAlbum;
- (BOOL)isOwnedCloudSharedAlbum;
- (BOOL)isPendingPhotoStreamAlbum;
- (BOOL)isLibrary;
- (BOOL)hasUnseenContentBoolValue;
- (id)localizedSharedByLabelAllowsEmail:(BOOL)arg1;
- (BOOL)isCloudSharedAlbum;
- (BOOL)isCameraRoll;
- (id)localizedTitle;
- (void).cxx_destruct;
- (id)query;
- (id)title;
- (BOOL)isStandInCollection;
- (BOOL)canContainAssets;
- (BOOL)collectionCanBePinned;
- (BOOL)collectionHasFixedOrder;
- (id)transientIdentifier;
- (unsigned int)estimatedVideosCount;
- (unsigned int)estimatedPhotosCount;
- (int)assetCollectionType;
- (int)assetCollectionSubtype;
- (id)pl_assetContainer;
- (unsigned int)estimatedAssetCount;
- (BOOL)pl_isWallpaperAlbum;
- (BOOL)isSmartCollection;
- (BOOL)isPhotoStreamCollection;
- (BOOL)isWallpaperCollection;
- (BOOL)isPanoramasCollection;
- (unsigned int)approximateVideosCount;
- (unsigned int)approximatePhotosCount;
- (void)_setCanShowCloudComments:(BOOL)arg1;
- (id)initTransientWithAssets:(id)arg1 orQuery:(id)arg2 title:(id)arg3 identifier:(id)arg4;
- (id)initTransientWithAssets:(id)arg1 orQuery:(id)arg2 title:(id)arg3 identifier:(id)arg4 albumKind:(int)arg5;
- (BOOL)_canShowCloudComments;
- (int)plAlbumKind;
- (Class)changeRequestClass;
- (id)initWithFetchDictionary:(id)arg1 propertyHint:(unsigned int)arg2 photoLibrary:(id)arg3;
- (id)description;

@end
