/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PhysicsKit.framework/PhysicsKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@class <NSObject>, PKRegion;

@interface PKPhysicsField : NSObject  {

  /* Error parsing encoded ivar type info: ^{PKCField=^^?^{RegionHolder}{mat4=(?={float32x4x4_t=[4]}{?=[16f]})}{mat4=(?={float32x4x4_t=[4]}{?=[16f]})}fBffIBB} */
    struct PKCField { int (**x1)(); struct RegionHolder {} *x2; struct mat4 { union { struct float32x4x4_t { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x_1_3_1[4]; } x_1_2_1; } x_3_1_1; } x3; struct mat4 { union { struct float32x4x4_t { void*x_1_3_1[4]; } x_1_2_1; } x_4_1_1; } x4; float x5; boolx6; float x7; float x8; unsigned int x9; boolx10; boolx11; } *_field;

    PKRegion *_region;
    BOOL _inUse;

  /* Unexpected information at end of encoded ivar type: @12@0:4@?8 */
  /* Error parsing encoded ivar type info:  */
    /* Warning: Unrecognized filer type: '' using 'void*' */ void*_position;

    float _rotation;

  /* Unexpected information at end of encoded ivar type: @12@0:4@?8 */
  /* Error parsing encoded ivar type info:  */
    /* Warning: Unrecognized filer type: '' using 'void*' */ void*_scale;

    <NSObject> *_representedObject;
    BOOL _active;
    BOOL _override;
}

@property BOOL _inUse;
@property float strength;
@property float falloff;
@property(getter=isActive) BOOL active;
@property(getter=isOverride) BOOL override;
@property(retain) id region;
@property unsigned int categoryBitMask;
@property /* Warning: Unrecognized filer type: '' using 'void*' */ void* position;
@property float rotation;
@property void* scale;
@property float minimumRadius;
@property <NSObject> * representedObject;


- (void)setOverride:(BOOL)arg1;
- (void)setIsOverride:(BOOL)arg1;
- (BOOL)override;
- (void)set_field:(struct PKCField { int (**x1)(); struct RegionHolder {} *x2; struct mat4 { union { struct float32x4x4_t { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x_1_3_1[4]; } x_1_2_1; } x_3_1_1; } x3; struct mat4 { union { struct float32x4x4_t { void*x_1_3_1[4]; } x_1_2_1; } x_4_1_1; } x4; float x5; boolx6; float x7; float x8; unsigned int x9; boolx10; boolx11; }*)arg1;
     /* Encoded args for previous method: v12@0:4^{PKCField=^^?^{RegionHolder}{mat4=(?={float32x4x4_t=[4]}{?=[16f]})}{mat4=(?={float32x4x4_t=[4]}{?=[16f]})}fBffIBB}8 */

- (void)set_inUse:(BOOL)arg1;
- (struct PKCField { int (**x1)(); struct RegionHolder {} *x2; struct mat4 { union { struct float32x4x4_t { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x_1_3_1[4]; } x_1_2_1; } x_3_1_1; } x3; struct mat4 { union { struct float32x4x4_t { void*x_1_3_1[4]; } x_1_2_1; } x_4_1_1; } x4; float x5; boolx6; float x7; float x8; unsigned int x9; boolx10; boolx11; }*)_field;
     /* Encoded args for previous method: ^{PKCField=^^?^{RegionHolder}{mat4=(?={float32x4x4_t=[4]}{?=[16f]})}{mat4=(?={float32x4x4_t=[4]}{?=[16f]})}fBffIBB}8@0:4 */

- (BOOL)isOverride;
- (void)setCategoryBitMask:(unsigned int)arg1;
- (unsigned int)categoryBitMask;
- (void)setRepresentedObject:(id)arg1;
- (id)representedObject;
- (void)setStrength:(float)arg1;
- (float)strength;
- (id)region;
- (void)setRegion:(id)arg1;
- (void).cxx_destruct;
- (float)rotation;
- (void)setRotation:(float)arg1;
- (void)setActive:(BOOL)arg1;
- (void)setIsActive:(BOOL)arg1;
- (BOOL)active;
- (void)setScale:(/* Warning: Unrecognized filer type: '' using 'void*' */ void*)arg1;
     /* Encoded args for previous method: v24@0:48 */

- (/* Warning: Unrecognized filer type: '8' using 'void*' */ void*)scale;
     /* Encoded args for previous method: 8@0:4 */

- (BOOL)isActive;
- (BOOL)_inUse;
- (float)minimumRadius;
- (void)setMinimumRadius:(float)arg1;
- (void)setFalloff:(float)arg1;
- (float)falloff;
- (/* Warning: Unrecognized filer type: '8' using 'void*' */ void*)position;
     /* Encoded args for previous method: 8@0:4 */

- (void)setPosition:(/* Warning: Unrecognized filer type: '' using 'void*' */ void*)arg1;
     /* Encoded args for previous method: v24@0:48 */

- (void)dealloc;
- (id)init;

@end
