/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PowerlogLiteOperators.framework/PowerlogLiteOperators
 */

@class NSArray, NSString, NSDate, NSNumber, NSMutableDictionary;

@interface PLBBMavHwRf1xLogMsg : PLBasebandMessage  {
    unsigned char _inited;
    NSDate *_bbDate;
    double *_bbTimeCal;
    NSNumber *_bbSeqnum;
    NSString *_error;
    NSNumber *_logDuration;
    NSNumber *_dtxOn;
    NSNumber *_dtxOff;
    NSArray *_callTypeDur;
    NSMutableDictionary *_commonInfo;
    NSMutableDictionary *_kvPairs;
}

@property(retain) NSDate * bbDate;
@property double* bbTimeCal;
@property(retain) NSNumber * bbSeqnum;
@property(retain) NSString * error;
@property(retain) NSNumber * logDuration;
@property(retain) NSNumber * dtxOn;
@property(retain) NSNumber * dtxOff;
@property(retain) NSArray * callTypeDur;
@property unsigned char inited;
@property(retain) NSMutableDictionary * commonInfo;
@property(retain) NSMutableDictionary * kvPairs;

+ (id)entryEventBackwardDefinitionBBMavHwRf1x;

- (void)setInited:(unsigned char)arg1;
- (unsigned char)inited;
- (void)setCallTypeDur:(id)arg1;
- (void)setDtxOff:(id)arg1;
- (void)setDtxOn:(id)arg1;
- (void)setBbSeqnum:(id)arg1;
- (id)bbSeqnum;
- (void)setBbTimeCal:(double*)arg1;
- (double*)bbTimeCal;
- (id)logEventBackwardBBMavHwRf1x;
- (void)refreshRequest;
- (id)callTypeDur;
- (id)dtxOn;
- (id)dtxOff;
- (void)populateEntry:(id)arg1;
- (void)addPairWithKey:(id)arg1 andWithVal:(id)arg2;
- (void)setKvPairs:(id)arg1;
- (id)kvPairs;
- (void)setCommonInfo:(id)arg1;
- (id)commonInfo;
- (void)setBbDate:(id)arg1;
- (id)bbDate;
- (void)sendAndLogPLEntry:(id)arg1 withName:(id)arg2 withType:(id)arg3;
- (id)logDuration;
- (void)setHeaderWithSeqNum:(id)arg1 andDate:(id)arg2 andTimeCal:(double)arg3;
- (void)setLogDuration:(id)arg1;
- (id)error;
- (void)setError:(id)arg1;
- (void).cxx_destruct;
- (id)init;

@end
