/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSDictionary;

@interface PLCloudSharedUpdateAlbumMetadataJob : PLCloudSharingJob  {
    NSDictionary *_metadata;
}

@property(retain) NSDictionary * metadata;

+ (void)updateAlbumMetadata:(id)arg1;

- (id)_argumentsDictionaryFromXPCEvent:(id)arg1;
- (id)_argumentsDictionaryAsData:(id)arg1;
- (void)encodeToXPCObject:(id)arg1;
- (long long)daemonOperation;
- (void)runDaemonSide;
- (id)initFromXPCObject:(id)arg1 connection:(id)arg2;
- (id)metadata;
- (void)setMetadata:(id)arg1;
- (void)run;
- (id)description;
- (void)dealloc;

@end
