/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSArray, NSString, NSData, NSOrderedSet, NSFetchRequest;

@interface PLFetchingAlbum : _PLFetchingAlbum  {
    unsigned int _countForDisplay;
    unsigned int _photosCount;
    unsigned int _videosCount;
    int _emptyState;
    NSArray *_cachedKeyAssets;
}

@property(retain) NSFetchRequest * fetchRequest;
@property(retain) NSData * customQueryParameters;
@property(retain) NSString * customQueryType;
@property(readonly) BOOL hasAssetsCache;
@property(retain) NSOrderedSet * fetchedAssets;

+ (BOOL)contextShouldIgnoreChangesForFetchRequest;
+ (BOOL)contextShouldIgnoreChangesForFetchedAssetsSet;
+ (BOOL)contextShouldIgnoreChangesForFetchedAssets;
+ (id)sortDescriptorsForAlbumKind:(int)arg1;
+ (id)predicateForAlbumKind:(int)arg1;
+ (id)_panoramasAlbumPredicate;

- (BOOL)mayHaveAssetsInCommon:(id)arg1;
- (id)fastPointerAccessSetForAssets:(id)arg1;
- (BOOL)hasAssetsCache;
- (unsigned int)countForAssetsOfKind:(short)arg1;
- (void)setAssets:(id)arg1;
- (void)setFetchRequest:(id)arg1;
- (id)_cachedKeyAssets;
- (unsigned int)_fetchedCountForAssetsOfKind:(short)arg1;
- (id)fetchRequest;
- (void)setupFetchRequest;
- (unsigned int)batchSize;
- (void)updateSnapshotAndClearCaches:(id)arg1;
- (void)didTurnIntoFault;
- (void)awakeFromFetch;
- (id)primitiveAssets;
- (void)awakeFromInsert;
- (void)setTertiaryKeyAsset:(id)arg1;
- (id)tertiaryKeyAsset;
- (void)setSecondaryKeyAsset:(id)arg1;
- (id)secondaryKeyAsset;
- (void)setKeyAsset:(id)arg1;
- (id)keyAsset;
- (unsigned int)approximateCount;
- (id)assets;
- (BOOL)canPerformEditOperation:(unsigned int)arg1;
- (id)mutableAssets;
- (void)batchFetchAssets:(id)arg1;
- (BOOL)isEmpty;
- (unsigned int)count;
- (void)dealloc;

@end
