/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSMutableSet, NSOrderedSet, PLAssetContainerChangeNotification, PLInFlightAssetsAlbum;

@interface PLInFlightAssetsAlbumChangeNotification : PLAssetContainerChangeNotification  {
    PLInFlightAssetsAlbum *_album;
    PLAssetContainerChangeNotification *_backingNotification;
    NSOrderedSet *_oldOIDs;
    NSMutableSet *_uniquedOIDs;
    BOOL _keyAssetDidChange;
}

@property(retain,readonly) PLInFlightAssetsAlbum * album;
@property(retain,readonly) PLAssetContainerChangeNotification * backingNotification;
@property(retain,readonly) NSOrderedSet * oldOIDs;

+ (id)notificationForDerivedObject:(id)arg1 priorChangeState:(id)arg2 forBackingObjectNotification:(id)arg3;

- (id)oldOIDs;
- (id)backingNotification;
- (id)initWithInFlightAssetsAlbum:(id)arg1 priorChangeState:(id)arg2 albumChangeNotification:(id)arg3;
- (BOOL)keyAssetDidChange;
- (BOOL)titleDidChange;
- (id)_changedObjects;
- (BOOL)_getOldSet:(id*)arg1 newSet:(id*)arg2;
- (id)_diffDescription;
- (id)album;
- (id)object;
- (id)description;
- (void)dealloc;

@end
