/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSString, PLImageTableSegment, NSData;

@interface PLMappedImageData : NSMutableData  {
    PLImageTableSegment *_segment;
    void *_bytes;
    unsigned long _length;
    BOOL _freeBytes;
    NSData *_pl_data;
}

@property unsigned int imageWidth;
@property unsigned int imageHeight;
@property(copy) NSString * photoUUID;


- (BOOL)pl_writeToPath:(id)arg1;
- (unsigned int)pl_advisoryLength;
- (id)brokencopy;
- (id)initWithEntryLength:(unsigned int)arg1;
- (id)initWithThumbnailPath:(id)arg1;
- (struct PLImageTableEntryFooter_s { struct { unsigned char x_1_1_1; unsigned char x_1_1_2; unsigned char x_1_1_3; unsigned char x_1_1_4; unsigned char x_1_1_5; unsigned char x_1_1_6; unsigned char x_1_1_7; unsigned char x_1_1_8; unsigned char x_1_1_9; unsigned char x_1_1_10; unsigned char x_1_1_11; unsigned char x_1_1_12; unsigned char x_1_1_13; unsigned char x_1_1_14; unsigned char x_1_1_15; unsigned char x_1_1_16; } x1; unsigned int x2; unsigned int x3; int x4; }*)_footer;
- (BOOL)uuidIsEqual:(id)arg1;
- (unsigned int)imageHeight;
- (unsigned int)imageWidth;
- (void)setImageHeight:(unsigned int)arg1;
- (void)setImageWidth:(unsigned int)arg1;
- (id)photoUUID;
- (void)setPhotoUUID:(id)arg1;
- (unsigned int)lengthIncludingFooter;
- (id)initWithImageTableSegment:(id)arg1 bytes:(void*)arg2 length:(unsigned long)arg3;
- (void*)mutableBytes;
- (const void*)bytes;
- (unsigned int)length;
- (void)dealloc;

@end
