/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSMutableOrderedSet, NSURL, NSString, NSNumber, PLGenericAlbum;

@interface PLPersistedAlbumMetadata : NSObject  {
    BOOL _pinned;
    BOOL _inTrash;
    BOOL _customSortAscending;
    BOOL _allowsOverwite;
    BOOL _isFolder;
    NSString *_title;
    NSString *_uuid;
    NSNumber *_kind;
    int _customSortKey;
    NSString *_customKeyAssetUUID;
    NSMutableOrderedSet *_assetUUIDs;
    PLGenericAlbum *_genericAlbum;
    NSURL *_metadataURL;
}

@property(retain) NSString * title;
@property(retain) NSString * uuid;
@property(retain) NSNumber * kind;
@property(readonly) BOOL isFolder;
@property(getter=isPinned) BOOL pinned;
@property(getter=isInTrash) BOOL inTrash;
@property BOOL customSortAscending;
@property int customSortKey;
@property(retain) NSString * customKeyAssetUUID;
@property(retain) NSMutableOrderedSet * assetUUIDs;
@property BOOL allowsOverwite;
@property(retain) PLGenericAlbum * genericAlbum;
@property(retain) NSURL * metadataURL;

+ (BOOL)isValidPath:(id)arg1;

- (id)genericAlbum;
- (id)initWithTitle:(id)arg1 uuid:(id)arg2 kind:(id)arg3 assetUUIDs:(id)arg4;
- (BOOL)allowsOverwite;
- (void)setCustomKeyAssetUUID:(id)arg1;
- (id)metadataURL;
- (id)customKeyAssetUUID;
- (int)customSortKey;
- (BOOL)customSortAscending;
- (id)assetUUIDs;
- (void)setCustomSortKey:(int)arg1;
- (void)setCustomSortAscending:(BOOL)arg1;
- (void)_saveMetadata;
- (void)_readMetadata;
- (id)extensionForKind:(id)arg1;
- (void)setAllowsOverwite:(BOOL)arg1;
- (void)setMetadataURL:(id)arg1;
- (void)setGenericAlbum:(id)arg1;
- (void)setAssetUUIDs:(id)arg1;
- (void)setInTrash:(BOOL)arg1;
- (BOOL)isInTrash;
- (void)removePersistedAlbumData;
- (void)persistAlbumData;
- (id)initWithPLGenericAlbum:(id)arg1;
- (void)setKind:(id)arg1;
- (void)setUuid:(id)arg1;
- (void)updateChildrenOrderingInAlbum:(id)arg1 includePendingAssetChanges:(BOOL)arg2;
- (id)insertAlbumFromDataInManagedObjectContext:(id)arg1;
- (id)initWithPersistedDataAtPath:(id)arg1;
- (BOOL)isFolder;
- (id)uuid;
- (id)kind;
- (void)setPinned:(BOOL)arg1;
- (BOOL)isPinned;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)init;

@end
