/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSArray, NSString, NSDictionary;

@interface PLPhotoEditModel : NSObject <NSCopying> {
    NSString *_effectFilterName;
    BOOL _smartToneEnabled;
    float _smartToneLevel;
    float _brightnessLevelOffset;
    float _contrastLevelOffset;
    float _exposureLevelOffset;
    float _shadowsLevelOffset;
    float _highlightsLevelOffset;
    BOOL _smartColorEnabled;
    float _smartColorLevel;
    float _colorContrastLevelOffset;
    float _colorVibrancyLevelOffset;
    float _straightenAngle;
    struct CGRect { 
        struct CGPoint { 
            float x; 
            float y; 
        } origin; 
        struct CGSize { 
            float width; 
            float height; 
        } size; 
    } _normalizedCropRect;
    int _cropConstraintWidth;
    int _cropConstraintHeight;
    unsigned int _rotation;
    NSDictionary *_smartToneStatistics;
    NSDictionary *_smartColorStatistics;
    NSArray *_redEyeCorrections;
    NSArray *_autoRedEyeCorrections;
    NSArray *_autoEnhanceFilters;
    BOOL _autoEnhanceIsOn;
}

@property(copy,readonly) NSString * effectFilterName;
@property(getter=isSmartToneEnabled,readonly) BOOL smartToneEnabled;
@property(copy,readonly) NSDictionary * smartToneStatistics;
@property(readonly) float smartToneLevel;
@property(readonly) float brightnessLevelOffset;
@property(readonly) float contrastLevelOffset;
@property(readonly) float exposureLevelOffset;
@property(readonly) float highlightsLevelOffset;
@property(readonly) float shadowsLevelOffset;
@property(getter=isSmartColorEnabled,readonly) BOOL smartColorEnabled;
@property(copy,readonly) NSDictionary * smartColorStatistics;
@property(readonly) float smartColorLevel;
@property(readonly) float colorContrastLevelOffset;
@property(readonly) float colorVibrancyLevelOffset;
@property(readonly) unsigned int rotation;
@property(readonly) struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } normalizedCropRect;
@property(readonly) int cropConstraintWidth;
@property(readonly) int cropConstraintHeight;
@property(readonly) float straightenAngle;
@property(copy,readonly) NSArray * redEyeCorrections;
@property(copy,readonly) NSArray * autoRedEyeCorrections;
@property(copy,readonly) NSArray * autoEnhanceFilters;
@property(readonly) BOOL autoEnhanceIsOn;

+ (int)identityOrientation;
+ (void)_loadSubfilterReferenceLevelsIfNeeded;
+ (int)identityCropConstraint;
+ (float)referenceSmartColorLevelOfType:(int)arg1;
+ (float)referenceSmartToneLevelOfType:(int)arg1;
+ (float)referenceColorVibrancyLevelOfType:(int)arg1;
+ (float)referenceColorContrastLevelOfType:(int)arg1;
+ (float)referenceShadowsLevelOfType:(int)arg1;
+ (float)referenceHighlightsLevelOfType:(int)arg1;
+ (float)referenceExposureLevelOfType:(int)arg1;
+ (float)referenceContrastLevelOfType:(int)arg1;
+ (float)referenceBrightnessLevelOfType:(int)arg1;
+ (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })identityNormalizedCropRect;
+ (float)angleForRotation:(unsigned int)arg1;
+ (unsigned int)identityRotation;
+ (float)referenceStraightenAngleOfType:(int)arg1;

- (BOOL)isIdentityModel;
- (BOOL)isVisuallyEqualToPhotoEditModel:(id)arg1;
- (int)cropConstraintHeight;
- (int)cropConstraintWidth;
- (void)_copyDataFromModel:(id)arg1;
- (id)smartColorStatistics;
- (float)smartColorLevel;
- (id)smartToneStatistics;
- (float)smartToneLevel;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })normalizedCropRect;
- (float)straightenAngle;
- (id)effectFilterName;
- (float)colorVibrancyLevelOffset;
- (float)colorContrastLevelOffset;
- (BOOL)isSmartColorEnabled;
- (float)shadowsLevelOffset;
- (float)highlightsLevelOffset;
- (float)exposureLevelOffset;
- (float)contrastLevelOffset;
- (float)brightnessLevelOffset;
- (BOOL)isSmartToneEnabled;
- (id)autoEnhanceFilters;
- (id)autoRedEyeCorrections;
- (id)redEyeCorrections;
- (BOOL)autoEnhanceIsOn;
- (BOOL)isEqualToPhotoEditModel:(id)arg1;
- (id)dictionaryRepresentation;
- (unsigned int)rotation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)mutableCopy;
- (id)description;
- (void)dealloc;
- (id)init;

@end
