/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PowerlogLiteOperators.framework/PowerlogLiteOperators
 */

@class NSDictionary;

@interface PLProcessNetworkSource : NSObject  {
    NSDictionary *_descriptionDictionary;
    NSDictionary *_countsDictionary;
    struct __NStatSource { } *_source;
}

@property(copy) NSDictionary * descriptionDictionary;
@property(copy) NSDictionary * countsDictionary;
@property struct __NStatSource { }* source;


- (void)setCountsDictionary:(id)arg1;
- (id)countsDictionary;
- (void)setDescriptionDictionary:(id)arg1;
- (id)descriptionDictionary;
- (id)initWithSource:(struct __NStatSource { }*)arg1;
- (void).cxx_destruct;
- (void)setSource:(struct __NStatSource { }*)arg1;
- (struct __NStatSource { }*)source;

@end
