/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PowerlogCore.framework/PowerlogCore
 */

@interface PLService : PLOperator  {
}

+ (id)initServices;
+ (void)stopServices;
+ (void)startServices;
+ (void)load;


@end
