/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

@class UILabel, PPPoEConnectionUIViewController, UIView;

@interface PPPoEViewController : AssistantSubUIViewController <TableViewManagerDelegate, UINavigationControllerDelegate> {
    UIView *tableHeaderContainerView;
    UIView *justTextContainerView;
    UILabel *justTextLabel;
    PPPoEConnectionUIViewController *pppoeConnectionUIViewController;
    id previousNavDelegate;
}

@property(retain) UIView * tableHeaderContainerView;
@property(retain) UIView * justTextContainerView;
@property UILabel * justTextLabel;
@property(retain) PPPoEConnectionUIViewController * pppoeConnectionUIViewController;


- (id)pppoeConnectionUIViewController;
- (void)setPppoeConnectionUIViewController:(id)arg1;
- (void)setupInitialTableHeaderConfiguration;
- (id)tableHeaderContainerView;
- (void)setJustTextLabel:(id)arg1;
- (id)justTextContainerView;
- (id)valueForItemOfType:(id)arg1 atTypeIndex:(unsigned int)arg2 inCellWithTag:(int)arg3;
- (BOOL)shouldChangeTextField:(id)arg1 atIndexPath:(id)arg2 forTextIndex:(unsigned int)arg3 toString:(id)arg4;
- (void)touchInCellAtIndexPath:(id)arg1;
- (id)justTextLabel;
- (void)setTableHeaderContainerView:(id)arg1;
- (void)setJustTextContainerView:(id)arg1;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)loadView;
- (void)dealloc;

@end
