/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@class UIView;

@interface PSSliderTableCell : PSControlTableCell  {
    UIView *_disabledView;
}


- (id)controlValue;
- (id)newControl;
- (void)setCellEnabled:(BOOL)arg1;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (BOOL)canReload;
- (void)prepareForReuse;
- (id)titleLabel;
- (void)setValue:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;

@end
