/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSSystemPolicyManager : NSObject  {
}

+ (id)thirdPartyApplicationProxyForBundleID:(id)arg1;
+ (id)thirdPartyApplicationProxies;
+ (id)_sharedProcessAnalytics;
+ (id)_dataUsageWorkspaceInfo;
+ (BOOL)_notificationSettingsNeededForBundleID:(id)arg1;
+ (BOOL)_cellularDataSettingsNeededForBundleID:(id)arg1;
+ (BOOL)_backgroundAppRefreshSettingsNeededForProxy:(id)arg1;
+ (BOOL)_locationSettingsNeededForBundleID:(id)arg1;
+ (BOOL)_privacySettingsNeededForProxy:(id)arg1;
+ (BOOL)_systemSettingsNeededForProxy:(id)arg1;
+ (void)_populateBBSectionIDs;


@end
