/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PrototypeTools.framework/PrototypeTools
 */

@class UISlider;

@interface PTSSliderRowTableViewCell : PTSRowTableViewCell  {
    UISlider *_slider;
}

+ (float)cellHeightForRow:(id)arg1;

- (void)_valueChanged:(id)arg1;
- (void)updateDisplayedValue;
- (void)updateCellCharacteristics;
- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;

@end
