/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PrototypeTools.framework/PrototypeTools
 */

@class UIView, PTXParallaxController, PTXMotionWindow, PTXParallaxSettings;

@interface PTXParallaxView : UIView <_UISettingsKeyObserver, PTXParallaxObserver> {
    PTXParallaxController *_parallaxController;
    PTXParallaxSettings *_settings;
    float _viewAlpha;
    PTXMotionWindow *_slideWindowX;
    PTXMotionWindow *_slideWindowY;
    PTXMotionWindow *_tiltWindowX;
    PTXMotionWindow *_tiltWindowY;
    BOOL _stopped;
    BOOL _resizesView;
    UIView *_view;
}

@property(retain) UIView * view;
@property BOOL resizesView;


- (void)setResizesView:(BOOL)arg1;
- (BOOL)resizesView;
- (void)setViewAlpha:(float)arg1;
- (id)initWithView:(id)arg1 parallaxController:(id)arg2 settings:(id)arg3;
- (void)clearParallaxOffset;
- (void)handleParallaxOffset:(struct CGPoint { float x1; float x2; })arg1 lockStatus:(int)arg2 strength:(float)arg3;
- (void)_clearOffset;
- (struct CATransform3D { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; })_slideTransform:(struct CGPoint { float x1; float x2; })arg1;
- (struct CATransform3D { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; })_tiltTransform:(struct CGPoint { float x1; float x2; })arg1;
- (void)_updateSettings;
- (void).cxx_destruct;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)setView:(id)arg1;
- (id)view;
- (void)layoutSubviews;
- (void)start;
- (void)stop;
- (void)dealloc;

@end
