/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class UIButton, NSArray, UILabel, NSString, UIImage;

@interface PUAdjustmentsModePickerCell : UITableViewCell  {
    UIButton *_accessoryButton;
    UILabel *_displayValueLabel;
    NSArray *_accessoryButtonConstraints;
    NSArray *_displayValueLabelConstraints;
    BOOL _isSubMode;
    NSString *_localizedModeName;
    UIImage *_modeIcon;
    NSString *_currentDisplayValue;
    int _buttonType;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _buttonAction;

}

@property(copy) NSString * localizedModeName;
@property(retain) UIImage * modeIcon;
@property(copy) NSString * currentDisplayValue;
@property BOOL isSubMode;
@property int buttonType;
@property(copy) id buttonAction;

+ (void)configureModePickerCellLabel:(id)arg1;

- (id)buttonAction;
- (void)setButtonAction:(id)arg1;
- (void).cxx_destruct;
- (int)buttonType;
- (void)updateConstraints;
- (void)prepareForReuse;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (BOOL)isSubMode;
- (id)currentDisplayValue;
- (id)modeIcon;
- (id)localizedModeName;
- (void)setButtonType:(int)arg1;
- (void)setIsSubMode:(BOOL)arg1;
- (void)setCurrentDisplayValue:(id)arg1;
- (void)setModeIcon:(id)arg1;
- (void)setLocalizedModeName:(id)arg1;
- (void)_updateButton;
- (void)_updateDisplayValueLabel;
- (void)_handleAccessoryButton:(id)arg1;

@end
