/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class PUAirplayRouteTableViewDataSource, PUAirplayRoute;

@interface PUAirplayRoutePickerViewController : UITableViewController  {
    PUAirplayRouteTableViewDataSource *_dataSource;
    PUAirplayRoute *_markedRoute;
    BOOL _shouldShowDoneButton;
    BOOL _makeRouteCurrentBeforeReturning;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _completionHandler;

}

@property(copy) id completionHandler;
@property BOOL shouldShowDoneButton;
@property BOOL makeRouteCurrentBeforeReturning;


- (void)setCompletionHandler:(id)arg1;
- (void).cxx_destruct;
- (id)completionHandler;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)setMakeRouteCurrentBeforeReturning:(BOOL)arg1;
- (BOOL)makeRouteCurrentBeforeReturning;
- (BOOL)shouldShowDoneButton;
- (void)setMarkedRoute:(id)arg1;
- (void)setShouldShowDoneButton:(BOOL)arg1;
- (void)_userSelectedRoute:(id)arg1 fromTableView:(id)arg2 atIndexPath:(id)arg3;
- (void)_updateRoutes;
- (void)_doneAction:(id)arg1;
- (id)init;

@end
