/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@class NSArray;

@interface PUEditPluginManager : NSObject  {
    int _mediaType;
    NSArray *__plugins;
}

@property(readonly) int mediaType;
@property(setter=_setPlugins:,copy) NSArray * _plugins;

+ (id)sharedManagerForMediaType:(int)arg1;

- (int)mediaType;
- (void).cxx_destruct;
- (void)_setPlugins:(id)arg1;
- (id)_plugins;
- (id)_initWithMediaType:(int)arg1;
- (id)userDefaultsIdentifier;
- (id)pluginActivities;
- (BOOL)hasPlugins;
- (void)rediscoverAvailablePlugins;

@end
