/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUGridPinchGestureRecognizer : UIPinchGestureRecognizer  {
    struct CGPoint { 
        float x; 
        float y; 
    } _touch0InitialLocation;
    struct CGPoint { 
        float x; 
        float y; 
    } _touch1InitialLocation;
    float _lastTransitionProgress;
    unsigned int _transitionDirection;
}

@property(readonly) float transitionProgress;
@property(readonly) struct CGSize { float x1; float x2; } centerOffset;
@property(readonly) unsigned int transitionDirection;
@property(readonly) BOOL transitionShouldFinish;


- (struct CGSize { float x1; float x2; })centerOffset;
- (float)transitionProgress;
- (unsigned int)transitionDirection;
- (void)reset;
- (void)setState:(int)arg1;
- (void)_resetTransitionState;
- (BOOL)transitionShouldFinish;

@end
