/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotoEditPhotoBrowserTransition : PUNavigationTransition  {
    BOOL _editSessionDidSaveChanges;
}

@property BOOL editSessionDidSaveChanges;


- (BOOL)editSessionDidSaveChanges;
- (void)_prepareViewForTransitionIsPresenting:(BOOL)arg1;
- (void)setEditSessionDidSaveChanges:(BOOL)arg1;
- (void)animatePopTransition;
- (void)animatePushTransition;
- (id)init;

@end
