/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@class PUPhotoEditPrecisionLevelContentView;

@interface PUPhotoEditPrecisionLevelSlider : PUPhotoEditLevelSlider <PUPhotoEditPrecisionLevelContentViewDataSource> {
    PUPhotoEditPrecisionLevelContentView *_precisionSliderContentView;
}


- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (float)precisionLevelContentViewIdentityOffset:(id)arg1;
- (void)invalidateConversionFactors;
- (id)preferredSliderContentView;
- (void)setupWithLayoutOrientation:(int)arg1;

@end
