/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@class UIViewController, PLPublishingAgent;

@interface PUPublishingActivity : PUActivity  {
    UIViewController *_referenceViewController;
    PLPublishingAgent *_currentAgent;
    double _startTime;
    double _endTime;
}

+ (int)activityCategory;

- (BOOL)_dismissActivityFromViewController:(id)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (BOOL)_presentActivityOnViewController:(id)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (void)prepareWithActivityItems:(id)arg1;
- (id)activityViewController;
- (BOOL)canPerformWithActivityItems:(id)arg1;
- (id)_activityImage;
- (id)activityTitle;
- (void).cxx_destruct;
- (void)editVideoViewController:(id)arg1 didTrimVideoWithOptions:(id)arg2;
- (void)editVideoViewControllerDidCancel:(id)arg1;
- (id)activityType;
- (void)_cleanup;
- (id)currentPublishingAgent;
- (void)_publishOverReferenceViewController;
- (id)publishingBundle;
- (void)_showTrimViewController;
- (void)_showPublishingSheetInViewController:(id)arg1 remakeAfterPublish:(BOOL)arg2;
- (void)_showVideoTooLongAlert;
- (void)_publishingAgentDidCancel:(id)arg1;
- (void)_publishingAgentDidStartPublishing:(id)arg1;
- (void)dealloc;
- (id)init;

@end
