/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/RadarCompose.framework/RadarCompose
 */

@class NSNumber, NSString;

@interface RadarSharedReports : NUCModel <NSCoding> {
}

@property(retain) NSNumber * problemId;
@property(copy) NSString * whenOriginatedDate;
@property(copy) NSString * enhanceRequestInd;
@property(copy) NSString * fixOrderingCode;
@property(copy) NSString * reproducibilityCode;
@property(copy) NSString * priorityCode;
@property(copy) NSString * classification;
@property(copy) NSString * probStateCode;
@property(copy) NSString * problemResCode;
@property(copy) NSString * assignee;
@property(copy) NSString * delegator;
@property(copy) NSString * dri;
@property(copy) NSString * resolver;
@property(copy) NSString * originator;
@property(copy) NSString * componentID;
@property(copy) NSString * componentName;
@property(copy) NSString * compRevVers;
@property(copy) NSString * problemTitle;
@property(copy) NSString * probStateName;
@property(copy) NSString * priorityCodeName;
@property(copy) NSString * cpuHours;
@property(copy) NSString * personHours;
@property(copy) NSString * thirdPartyAppProblem;
@property(copy) NSString * readByAssignee;
@property(copy) NSString * readByAssigneeFlag;
@property(copy) NSString * isScreened;
@property(copy) NSString * howFoundCode;
@property(copy) NSString * lastModDate;
@property(copy) NSString * origFirstName;
@property(copy) NSString * origLastName;
@property(copy) NSString * assignFirstName;
@property(copy) NSString * assignLastName;
@property(copy) NSString * driFirstName;
@property(copy) NSString * driLastName;
@property(copy) NSString * resolver_FirstName;
@property(copy) NSString * resolver_LastName;
@property(copy) NSString * delegateFirstName;
@property(copy) NSString * delegateLastName;
@property(copy) NSString * assigneelastModDate;
@property(copy) NSString * componentNameAndVersion;
@property(copy) NSString * foundInBuildVersion;
@property(copy) NSString * fixedInBuildVersion;
@property(copy) NSString * verifiedInBuildVersion;
@property(copy) NSString * mustBeFixedInBuildVersion;
@property(copy) NSString * milestoneBuildVersion;
@property(copy) NSString * foundInBuildVersionLower;
@property(copy) NSString * fixedInBuildVersionLower;
@property(copy) NSString * verifiedInBuildVersionLower;
@property(copy) NSString * mustBeFixedInBuildVersionLower;
@property(copy) NSString * milestoneBuildVersionLower;

+ (id)radarSharedReportsFromDictionary:(id)arg1;

- (id)description;

@end
