/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Radio.framework/Radio
 */

@class SSURLConnectionRequest, NSObject<OS_dispatch_queue>;

@interface RadioGetFeaturedStationsRequest : RadioRequest  {
    NSObject<OS_dispatch_queue> *_artworkQueue;
    SSURLConnectionRequest *_request;
    unsigned int _stationCount;
    BOOL _disableArtworkLoading;
    BOOL _disableCachedResponses;
}

@property BOOL disableArtworkLoading;
@property BOOL disableCachedResponses;


- (void)setDisableCachedResponses:(BOOL)arg1;
- (BOOL)disableCachedResponses;
- (id)_stationDictionariesByApplyingResponse:(id)arg1 error:(id*)arg2;
- (void)startWithFeaturedStationsCompletionHandler:(id)arg1;
- (id)_importFeaturedStationWithDictionary:(id)arg1 inModel:(id)arg2 loadArtworkSynchronously:(BOOL)arg3;
- (id)initWithStationCount:(unsigned int)arg1;
- (BOOL)disableArtworkLoading;
- (void)setDisableArtworkLoading:(BOOL)arg1;
- (void)startWithCompletionHandler:(id)arg1;
- (void).cxx_destruct;
- (void)cancel;
- (id)init;

@end
