/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Radio.framework/Radio
 */

@class SSURLConnectionRequest, NSString, NSObject<OS_dispatch_queue>, NSDictionary;

@interface RadioSyncRequest : RadioRequest  {
    NSObject<OS_dispatch_queue> *_artworkQueue;
    unsigned long long _globalVersion;
    SSURLConnectionRequest *_request;
    NSDictionary *_responseDictionary;
    BOOL _disableArtworkLoading;
    BOOL _includeCleanTracksOnly;
    BOOL _isAutomaticUpdate;
    NSString *_referer;
    NSDictionary *_resultingOverrideBagDictionary;
}

@property BOOL disableArtworkLoading;
@property BOOL includeCleanTracksOnly;
@property BOOL isAutomaticUpdate;
@property(copy) NSString * referer;
@property(copy,readonly) NSDictionary * resultingOverrideBagDictionary;


- (void)setIsAutomaticUpdate:(BOOL)arg1;
- (id)resultingOverrideBagDictionary;
- (void)setReferer:(id)arg1;
- (id)referer;
- (BOOL)isAutomaticUpdate;
- (BOOL)includeCleanTracksOnly;
- (BOOL)disableArtworkLoading;
- (void)setDisableArtworkLoading:(BOOL)arg1;
- (id)_updateModel:(id)arg1 withChangeDictionary:(id)arg2 changeType:(int*)arg3 loadArtworkSynchronously:(BOOL)arg4;
- (id)_stationSortOrderForChanges:(id)arg1;
- (id)_sortedChangesByType:(id)arg1;
- (id)matchDictionary;
- (id)changeList;
- (id)initWithGlobalVersion:(unsigned long long)arg1;
- (id)responseDictionary;
- (void)startWithCompletionHandler:(id)arg1;
- (void).cxx_destruct;
- (void)cancel;
- (id)init;
- (void)setIncludeCleanTracksOnly:(BOOL)arg1;

@end
