/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Radio.framework/Radio
 */

@class SSURLConnectionRequest, NSArray;

@interface RadioStationMatchRequest : RadioRequest  {
    NSArray *_libraryTrackDictionaries;
    SSURLConnectionRequest *_request;
}


- (id)initWithLibraryTrackDictionaries:(id)arg1;
- (void)startWithCompletionHandler:(id)arg1;
- (void).cxx_destruct;
- (void)cancel;

@end
