/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

@class AVAssetWriter, AVCaptureAudioDataOutput, NSObject<OS_dispatch_queue>, NSUUID, AVCaptureSession, NSMutableArray, NSURL, NSDate, <RCCaptureOutputWriterDelegate>;

@interface RCCaptureOutputWriter : NSObject <AVCaptureAudioDataOutputSampleBufferDelegate> {
    BOOL _waitingForAVCaptureSessionDidStart;
    BOOL _handledAVCaptureSessionTerminatedAbnormally;
    BOOL _handledAVCaptureSessionFailedToStart;
    BOOL _isProcessingSamples;
    int _AVCaptureSessionStartupState;
    unsigned int _sampleBuffersWritten;
    NSMutableArray *_delegateBlocks;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    } _sampleBuffersWrittenDuration;
    BOOL _finalizedAssetEncounteredError;
    AVCaptureSession *_AVCaptureSession;
    int _writerState;
    <RCCaptureOutputWriterDelegate> *_captureOutputDelegate;
    NSURL *_finalizedAssetURL;
    NSObject<OS_dispatch_queue> *_queue;
    NSUUID *_recordingSessionID;
    NSURL *_activeOutputFileURL;
    NSDate *_recordingCreationDate;
    AVAssetWriter *_assetWriter;
    NSObject<OS_dispatch_queue> *_sampleBufferQueue;
    AVCaptureAudioDataOutput *_sampleBufferDataOutput;
    double _maxRecordedDuration;
    unsigned long long _maxRecordedFileSize;
    double _finalizedAssetDuration;
}

@property(readonly) AVCaptureSession * AVCaptureSession;
@property int writerState;
@property(readonly) double assetWritingCheckpointInterval;
@property unsigned long long maxRecordedFileSize;
@property double maxRecordedDuration;
@property <RCCaptureOutputWriterDelegate> * captureOutputDelegate;
@property(readonly) NSURL * finalizedAssetURL;
@property(readonly) double finalizedAssetDuration;
@property(readonly) BOOL finalizedAssetEncounteredError;
@property(retain) NSObject<OS_dispatch_queue> * queue;
@property(copy) NSUUID * recordingSessionID;
@property(retain) NSURL * activeOutputFileURL;
@property(retain) NSDate * recordingCreationDate;
@property(retain) AVAssetWriter * assetWriter;
@property(retain) NSObject<OS_dispatch_queue> * sampleBufferQueue;
@property(retain) AVCaptureAudioDataOutput * sampleBufferDataOutput;


- (void)setSampleBufferDataOutput:(id)arg1;
- (id)sampleBufferDataOutput;
- (void)setSampleBufferQueue:(id)arg1;
- (id)sampleBufferQueue;
- (void)setAssetWriter:(id)arg1;
- (id)assetWriter;
- (void)setRecordingCreationDate:(id)arg1;
- (id)recordingCreationDate;
- (void)setActiveOutputFileURL:(id)arg1;
- (id)activeOutputFileURL;
- (void)setRecordingSessionID:(id)arg1;
- (id)recordingSessionID;
- (id)finalizedAssetURL;
- (id)captureOutputDelegate;
- (void)setWriterState:(int)arg1;
- (id)AVCaptureSession;
- (void)_sessionErrored:(id)arg1;
- (void)_interruptionDidBegin:(id)arg1;
- (void)_sessionDidStopRunning:(id)arg1;
- (void)_sessionDidStartRunning:(id)arg1;
- (BOOL)_handleNotificationAsSessionStartFailure;
- (double)assetWritingCheckpointInterval;
- (BOOL)_setupAssetWriter:(id*)arg1 sampleBufferRef:(struct opaqueCMSampleBuffer { }*)arg2;
- (void)_finalizeAssetWriting;
- (void)_scheduleMainThreadDelegateBlock:(id)arg1;
- (void)_setWriterState:(int)arg1;
- (void)_checkIfRecordingSessionEverStarted:(id)arg1;
- (void)_prepareCaptureSessionOutputsIfNecessary;
- (int)_writerState;
- (void)_clearSampleDataOutput;
- (void)_unregisterForCatpureSessionNotifications;
- (void)_registerForCatpureSessionNotifications;
- (BOOL)startCaptureSession;
- (id)initWithAVCaptureSession:(id)arg1;
- (void)setCaptureOutputDelegate:(id)arg1;
- (void)stopCaptureSession;
- (BOOL)startWritingToOutputFileURL:(id)arg1 creationDate:(id)arg2 beginPaused:(BOOL)arg3 captureOutputDelegate:(id)arg4;
- (double)finalizedAssetDuration;
- (BOOL)finalizedAssetEncounteredError;
- (void)endWriting;
- (void)resumeWriting;
- (void)pauseWriting;
- (int)writerState;
- (void)setQueue:(id)arg1;
- (id)queue;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setMaxRecordedFileSize:(unsigned long long)arg1;
- (void)setMaxRecordedDuration:(double)arg1;
- (unsigned long long)maxRecordedFileSize;
- (double)maxRecordedDuration;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg2 fromConnection:(id)arg3;

@end
