/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
 */

@interface RCMutableWaveform : RCWaveform  {
}


- (void)removeSegment:(id)arg1;
- (void)addSegments:(id)arg1;
- (BOOL)clipToTimeRange:(struct { double x1; double x2; })arg1;
- (void)addSegment:(id)arg1;
- (void)removeAllSegments;
- (id)classForCoder;
- (void)setSegments:(id)arg1;
- (id)segments;

@end
