/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppLaunchStats.framework/AppLaunchStats
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString, NSObject<OS_dispatch_queue>, NSDate, NSObject<OS_dispatch_source>;

@interface ReservationStationObject : NSObject <DuetLoggerProtocol> {
    NSObject<OS_dispatch_queue> *rsDispatchQueue;
    long long lockTime;
    long long seqNum;
    int appType;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id forceEndHandler;

    NSDate *timeStamp;
    NSString *bundleID;
    NSObject<OS_dispatch_source> *theTimer;
}


- (void)setStationState:(id)arg1 seq:(long long)arg2 type:(int)arg3 didset:(bool*)arg4 release:(id)arg5;
- (void)setStation:(id)arg1 didSet:(bool*)arg2;
- (void)releaseStationWithAppID:(id)arg1 seqNum:(long long)arg2 withReleaseState:(bool*)arg3;
- (bool)isFree;
- (void)createTimer;
- (void)onTick;
- (void)logLight:(struct __asl_object_s { }*)arg1 withMsg:(struct __asl_object_s { }*)arg2 withLevel:(int)arg3;
- (void)logAll:(struct __asl_object_s { }*)arg1 withMsg:(struct __asl_object_s { }*)arg2 withLevel:(int)arg3;
- (void).cxx_destruct;
- (id)init:(id)arg1;

@end
