/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ResponseKit.framework/ResponseKit
 */

@interface RKSentenceClassifier_en_US : RKSentenceClassifier  {
}

+ (id)preProcessTextMessageForLinguisticTagger:(id)arg1;
+ (unsigned int)interrogativeToCategoryMapMaxKeyLength;
+ (id)interrogativeToCategoryMap;

- (id)classifySentence;
- (void)analyzeSentence;
- (id)addSentenceTerminatorQuestion:(id)arg1;

@end
