/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/RadioUI.framework/RadioUI
 */

@class <RUStationTreeViewControllerDelegate>, SSMetricsPageEvent, RUPreviewSession, UILabel, RUStationTreeDataSource, SKUICircleProgressIndicator, UIScrollView, UITableView, RadioStationTreeNode, RUProxyTableView, RUMetricsController, RUParallelScrollView, NSMutableArray;

@interface RUStationTreeViewController : UIViewController <RUAudioPreviewViewDelegate, RUPreviewSessionObserver, UITableViewDataSource, UITableViewDelegate> {
    SKUICircleProgressIndicator *_activityIndicator;
    RadioStationTreeNode *_addingTreeNode;
    RUParallelScrollView *_containerScrollView;
    RUStationTreeDataSource *_dataSource;
    BOOL _isLoadingParentTreeNode;
    BOOL _hasLoadedParentTreeNode;
    SSMetricsPageEvent *_lastPageEvent;
    UILabel *_loadingLabel;
    NSMutableArray *_loadingTreeNodes;
    RUMetricsController *_metricsController;
    int _navigationOperation;
    RadioStationTreeNode *_parentTreeNode;
    RadioStationTreeNode *_previewingTreeNode;
    RUPreviewSession *_previewSession;
    NSMutableArray *_queuedMetricsOperations;
    RUProxyTableView *_tableView;
    BOOL _wasLastNavigationOperationAnimated;
    <RUStationTreeViewControllerDelegate> *_delegate;
}

@property <RUStationTreeViewControllerDelegate> * delegate;
@property(readonly) UIScrollView * scrollView;
@property(readonly) UITableView * tableView;

+ (float)contentWidthForTraitCollection:(id)arg1;

- (void)audioPreviewViewDidCancel:(id)arg1 forReason:(int)arg2;
- (void)_addButtonAction:(id)arg1;
- (void)_loadAdditionalChildrenForSectionTreeNode:(id)arg1;
- (void)_applyPreviewingAttributesToCell:(id)arg1 forTreeNode:(id)arg2 animated:(BOOL)arg3;
- (id)_childTreeNodeAtIndexPath:(id)arg1;
- (id)_mediaEventForPreviewingItem:(id)arg1;
- (id)_currentPreviewTrackDescripton;
- (id)_indexPathForChildTreeNode:(id)arg1;
- (void)_updateWithParentNode:(id)arg1 metricsPageEvent:(id)arg2 metricsConfiguration:(id)arg3 canReloadTableView:(BOOL)arg4;
- (void)_layoutLoadingViews;
- (void)_updateViewForHorizontalSizeClassChange;
- (void)_endPreviewPlaybackWithOptions:(int)arg1 withFinalItem:(id)arg2 didFinalItemPlayToCompletion:(BOOL)arg3;
- (id)initWithParentNodeID:(long long)arg1;
- (id)_initWithDataSource:(id)arg1;
- (id)initForFeaturedStations;
- (void)removeAddingIndicator;
- (void)_addMetricsControllerOperationBlock:(id)arg1;
- (void)_contentSizeCategoryDidChangeNotification:(id)arg1;
- (void)previewSession:(id)arg1 didStopWithOptions:(int)arg2 withFinalItem:(id)arg3 didFinalItemPlayToCompletion:(BOOL)arg4;
- (void)previewSession:(id)arg1 didChangeFromItem:(id)arg2 toItem:(id)arg3;
- (void).cxx_destruct;
- (id)tableView;
- (id)scrollView;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)contentScrollView;
- (void)viewWillAppear:(BOOL)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)delegate;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(int)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (void)_applicationWillEnterForegroundNotification:(id)arg1;

@end
