/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSNumber, SAUIImageResource, NSArray;

@interface SAGKImageLinkedAnswer : SAGKLinkedAnswer  {
}

@property(copy) NSNumber * fileSize;
@property(retain) SAUIImageResource * imageResource;
@property(copy) NSArray * thumbnails;

+ (id)imageLinkedAnswerWithDictionary:(id)arg1 context:(id)arg2;
+ (id)imageLinkedAnswer;

- (void)setThumbnails:(id)arg1;
- (id)thumbnails;
- (void)setImageResource:(id)arg1;
- (id)imageResource;
- (id)encodedClassName;
- (void)setFileSize:(id)arg1;
- (id)fileSize;
- (id)groupIdentifier;

@end
