/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAMicroblogSinaWeiboCredential : SAMicroblogSocialCredential  {
}

+ (id)sinaWeiboCredentialWithDictionary:(id)arg1 context:(id)arg2;
+ (id)sinaWeiboCredential;

- (id)encodedClassName;
- (id)groupIdentifier;

@end
