/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SASettingSetFlashlight : SASettingSetBool  {
}

+ (id)setFlashlightWithDictionary:(id)arg1 context:(id)arg2;
+ (id)setFlashlight;

- (BOOL)requiresResponse;
- (id)encodedClassName;
- (id)groupIdentifier;

@end
