/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSString, NSArray;

@interface SASmsRecipientSearchCompleted : SABaseCommand <SAServerBoundCommand> {
}

@property(copy) NSArray * recipients;
@property(copy) NSString * aceId;
@property(copy) NSString * refId;

+ (id)recipientSearchCompletedWithDictionary:(id)arg1 context:(id)arg2;
+ (id)recipientSearchCompleted;

- (id)encodedClassName;
- (void)setRecipients:(id)arg1;
- (id)recipients;
- (id)groupIdentifier;

@end
