/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSArray;

@interface SASSpeechPartialResult : SABaseClientBoundCommand  {
}

@property(copy) NSArray * tokens;

+ (id)speechPartialResultWithDictionary:(id)arg1 context:(id)arg2;
+ (id)speechPartialResult;

- (void)setTokens:(id)arg1;
- (BOOL)requiresResponse;
- (id)encodedClassName;
- (id)tokens;
- (id)groupIdentifier;
- (id)af_bestTextInterpretation;
- (id)af_userUtteranceValue;
- (id)af_correctionContext;

@end
