/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSString;

@interface SAStartStructuredDictationRequest : SAStartRequest  {
}

@property(copy) NSString * structuredDictationType;

+ (id)startStructuredDictationRequestWithDictionary:(id)arg1 context:(id)arg2;
+ (id)startStructuredDictationRequest;

- (void)setStructuredDictationType:(id)arg1;
- (id)structuredDictationType;
- (id)encodedClassName;
- (id)groupIdentifier;

@end
