/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSDate, NSString;

@interface SAStockRequest : SADomainObject  {
}

@property(copy) NSDate * endDate;
@property(copy) NSString * requestType;
@property(copy) NSDate * startDate;

+ (id)requestWithDictionary:(id)arg1 context:(id)arg2;
+ (id)request;

- (id)endDate;
- (id)startDate;
- (void)updateUsingSet:(id)arg1 add:(id)arg2 remove:(id)arg3;
- (id)encodedClassName;
- (id)requestType;
- (void)setRequestType:(id)arg1;
- (void)setEndDate:(id)arg1;
- (void)setStartDate:(id)arg1;
- (id)groupIdentifier;

@end
