/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

@interface SBUIPluginAppearanceContext : NSObject  {
    unsigned int _uiEnvironment;
    BOOL _hideOtherWindowsDuringAppearance;
}

@property unsigned int uiEnvironment;
@property BOOL hideOtherWindowsDuringAppearance;


- (void)setHideOtherWindowsDuringAppearance:(BOOL)arg1;
- (BOOL)hideOtherWindowsDuringAppearance;
- (void)setUiEnvironment:(unsigned int)arg1;
- (unsigned int)uiEnvironment;

@end
