/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
 */

@class NSHashTable;

@interface SBUIKeyboardEnablementManager : NSObject  {
    NSHashTable *_disabledContexts;
    BOOL _disabled;
}

+ (id)sharedInstance;

- (void)enableAutomaticAppearanceForContext:(id)arg1;
- (void)disableAutomaticAppearanceForContext:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)init;

@end
