/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNActionRemove : SCNAction  {
    BOOL _hasFired;
}

+ (BOOL)supportsSecureCoding;
+ (id)removeFromParentNode;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)willStartWithTarget:(id)arg1 atTime:(double)arg2;
- (id)reversedAction;
- (void)updateWithTarget:(id)arg1 forTime:(double)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end
