/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNJSImage : UIImage  {
}

+ (id)imageWithPath:(id)arg1;
+ (id)imageWithURL:(id)arg1;
+ (id)SCNJSExportProtocol;


@end
