/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ScreenReaderCore.framework/ScreenReaderCore
 */

@interface SCRCStackQueue : NSObject  {
    struct _SCRCStackNode { id x1; void *x2; void *x3; } *_firstNode;
    struct _SCRCStackNode { id x1; void *x2; void *x3; } *_lastNode;
    unsigned int _count;
}


- (id)topObject;
- (void)pushArray:(id)arg1;
- (id)popObjectRetained;
- (id)dequeueObjectRetained;
- (id)popObject;
- (void)pushObject:(id)arg1;
- (id)dequeueObject;
- (void)enqueueObject:(id)arg1;
- (id)objectEnumerator;
- (BOOL)isEmpty;
- (void)removeAllObjects;
- (id)description;
- (unsigned int)count;
- (void)dealloc;

@end
