/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
 */

@class NSMutableArray;

@interface SFCollectionViewFlowLayout : UICollectionViewFlowLayout  {
    NSMutableArray *_insertedIndexPaths;
    NSMutableArray *_movedIndexPaths;
    NSMutableArray *_deletedIndexPaths;
    NSMutableArray *_handledIndexPaths;
}


- (void)_applyToLayoutAttributes:(id)arg1 toView:(id)arg2;
- (void)finalizeCollectionViewUpdates;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (id)_animationForReusableView:(id)arg1 toLayoutAttributes:(id)arg2 type:(unsigned int)arg3;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (void).cxx_destruct;
- (id)init;

@end
