/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@class NSString;

@interface SGLabeledValue : NSObject  {
    NSString *_label;
    NSString *_value;
}

@property(readonly) NSString * label;
@property(readonly) NSString * value;


- (id)initWithLabel:(id)arg1 value:(id)arg2;
- (BOOL)isEqualToLabeledValue:(id)arg1;
- (void).cxx_destruct;
- (id)label;
- (id)value;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end
