/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreSuggestions.framework/CoreSuggestions
 */

@class NSURL, NSArray, NSString, NSDate, SGSimpleNamedEmailAddress;

@interface SGOrigin : NSObject <NSCopying, NSSecureCoding> {
    unsigned int _type;
    NSString *_sourceKey;
    NSString *_externalKey;
    NSString *_contextSnippet;
    struct _NSRange { 
        unsigned int location; 
        unsigned int length; 
    } _contextSnippetRange;
    SGSimpleNamedEmailAddress *_from;
    NSArray *_to;
    NSArray *_cc;
    NSArray *_bcc;
    NSDate *_date;
    NSString *_title;
    BOOL _fromForwardedMessage;
}

@property(readonly) unsigned int type;
@property(readonly) NSString * sourceKey;
@property(readonly) NSString * externalKey;
@property(readonly) NSString * contextSnippet;
@property(readonly) struct _NSRange { unsigned int x1; unsigned int x2; } contextSnippetRange;
@property(readonly) SGSimpleNamedEmailAddress * from;
@property(readonly) NSArray * to;
@property(readonly) NSArray * cc;
@property(readonly) NSArray * bcc;
@property(readonly) NSDate * date;
@property(readonly) NSString * title;
@property(getter=isFromForwardedMessage,readonly) BOOL fromForwardedMessage;
@property(readonly) NSURL * url;

+ (id)originWithType:(unsigned int)arg1 sourceKey:(id)arg2 externalKey:(id)arg3 fromForwardedMessage:(BOOL)arg4;
+ (BOOL)supportsSecureCoding;
+ (id)originForDuplicateKey:(id)arg1 sourceKey:(id)arg2 store:(id)arg3;

- (id)to;
- (id)cc;
- (id)externalKey;
- (BOOL)isFromForwardedMessage;
- (id)bcc;
- (id)sourceKey;
- (struct _NSRange { unsigned int x1; unsigned int x2; })contextSnippetRange;
- (id)contextSnippet;
- (BOOL)isEqualToOrigin:(id)arg1;
- (id)initWithType:(unsigned int)arg1 sourceKey:(id)arg2 externalKey:(id)arg3 fromForwardedMessage:(BOOL)arg4;
- (id)from;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)date;
- (unsigned int)type;
- (id)title;
- (id)url;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)init;
- (void)addDetailsFromParticipantsOfEntity:(id)arg1 store:(id)arg2;
- (void)addDetailsFromOriginatingGenericEntity:(id)arg1;
- (void)addDetailsFromOriginatingCalendarEntity:(id)arg1 store:(id)arg2;
- (void)addDetailsFromOriginatingContactEntity:(id)arg1 store:(id)arg2;
- (void)addSnippetIfNotExistsFromContentOfEntity:(id)arg1;
- (void)addDetailsFromOriginatingEmailEntity:(id)arg1 store:(id)arg2;

@end
