/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SiriUI.framework/SiriUI
 */

@class NSArray, UIActionSheet, NSString, <SiriUIAudioRoutePickerControllerDelegate>, UIViewController;

@interface SiriUIAudioRoutePickerController : NSObject <UIActionSheetDelegate> {
    BOOL _hasRoutesToPick;
    <SiriUIAudioRoutePickerControllerDelegate> *_delegate;
    UIActionSheet *_pickerSheet;
    NSArray *_displayedRoutes;
    UIViewController *_pickerViewController;
    BOOL _shouldRedisplayPicker;
    NSString *_audioCategory;
}

@property <SiriUIAudioRoutePickerControllerDelegate> * delegate;


- (BOOL)pickerIsShowing;
- (void)stopUpdatingRoutes;
- (void)dismissPickerAnimated:(BOOL)arg1;
- (BOOL)_overrideIsPicked;
- (id)_pickerSheet;
- (void)_cleanupPickerSheet;
- (BOOL)_hasPickableRouteOtherThanBuiltIn;
- (void)_routeChanged:(id)arg1;
- (void)_pickableRoutesChanged:(id)arg1;
- (id)initWithCategory:(id)arg1;
- (BOOL)bluetoothIsPicked;
- (BOOL)hasRoutesToPick;
- (void)startUpdatingRoutes;
- (void)showPickerFromView:(id)arg1 orientation:(int)arg2 animated:(BOOL)arg3;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)actionSheet:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)willPresentActionSheet:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)delegate;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (id)_pickableRoutes;

@end
