/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SiriUI.framework/SiriUI
 */

@class UIView, UIImageView, SiriUIKeyline;

@interface SiriUIChevronButton : UIButton  {
    UIImageView *_chevronImageView;
    SiriUIKeyline *_keyline;
    BOOL _hasChevron;
    UIView *_subview;
    float _chevronRightInset;
    float _leftSubviewInset;
    int _keylineType;
}

@property(retain) UIView * subview;
@property float chevronRightInset;
@property float leftSubviewInset;
@property int keylineType;
@property BOOL hasChevron;


- (void)setLeftSubviewInset:(float)arg1;
- (void)setChevronRightInset:(float)arg1;
- (id)subview;
- (void)setSubview:(id)arg1;
- (float)leftSubviewInset;
- (float)chevronRightInset;
- (BOOL)hasChevron;
- (int)keylineType;
- (void)setHasChevron:(BOOL)arg1;
- (void)setKeylineType:(int)arg1;
- (void).cxx_destruct;
- (void)setHighlighted:(BOOL)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;

@end
