/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSNumber, NSString;

@interface SKUIGiftAmount : NSObject <NSCopying> {
    NSString *_displayLabel;
    NSString *_partNumber;
    NSNumber *_value;
}

@property(copy) NSString * displayLabel;
@property(copy) NSString * partNumber;
@property(copy) NSNumber * value;


- (void)setPartNumber:(id)arg1;
- (void)setDisplayLabel:(id)arg1;
- (id)initWithAmountDictionary:(id)arg1;
- (id)displayLabel;
- (id)HTTPBodyDictionary;
- (id)partNumber;
- (void).cxx_destruct;
- (id)value;
- (void)setValue:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
