/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUISearchBarController;

@interface SKUISearchBarPageSection : SKUIStorePageSection  {
    SKUISearchBarController *_searchBarController;
}


- (id)_searchBarController;
- (id)backgroundColorForIndexPath:(id)arg1;
- (int)numberOfCells;
- (id)cellForIndexPath:(id)arg1;
- (struct CGSize { float x1; float x2; })cellSizeForIndexPath:(id)arg1;
- (void)willAppearInContext:(id)arg1;
- (void).cxx_destruct;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })sectionContentInset;

@end
