/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class UIViewController, NSArray;

@interface SKUIIPadChartsColumnView : UIView  {
    struct UIEdgeInsets { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _contentInset;
    NSArray *_contentViewControllers;
    int _selectedViewControllerIndex;
}

@property struct UIEdgeInsets { float x1; float x2; float x3; float x4; } contentInset;
@property(copy) NSArray * contentViewControllers;
@property(readonly) UIViewController * selectedViewController;


- (id)contentViewControllers;
- (void)_addSelectedViewController;
- (void)setContentViewControllers:(id)arg1;
- (void)setSelectedViewControllerIndex:(int)arg1;
- (void).cxx_destruct;
- (id)selectedViewController;
- (void)setContentInset:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })contentInset;
- (void)layoutSubviews;

@end
