/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSMutableArray, NSArray;

@interface SKUIGridComponent : SKUIPageComponent  {
    NSMutableArray *_children;
    struct SKUIEditorialStyle { 
        int alignment; 
        int bodyFontWeight; 
        float bodyFontSize; 
        float linkSpacing; 
        int titleFontWeight; 
        float titleFontSize; 
        float titleSpacing; 
    } _editorialStyle;
    int _gridType;
    struct SKUILockupStyle { 
        int artworkSize; 
        int layoutStyle; 
        unsigned int visibleFields; 
    } _lockupStyle;
    int _missingItemCount;
    BOOL _showsIndexNumbers;
}

@property(readonly) int gridType;
@property(readonly) NSArray * children;
@property(readonly) struct SKUIEditorialStyle { int x1; int x2; float x3; float x4; int x5; float x6; float x7; } editorialStyle;
@property(readonly) struct SKUILockupStyle { int x1; int x2; unsigned int x3; } lockupStyle;
@property(readonly) BOOL showsIndexNumbers;


- (id)children;
- (struct SKUIEditorialStyle { int x1; int x2; float x3; float x4; int x5; float x6; float x7; })editorialStyle;
- (BOOL)showsIndexNumbers;
- (id)_updateWithMissingItems:(id)arg1;
- (id)_updateWithInvalidItemIdentifiers:(id)arg1;
- (id)initWithLockups:(id)arg1;
- (id)initWithGridItems:(id)arg1;
- (struct SKUILockupStyle { int x1; int x2; unsigned int x3; })lockupStyle;
- (id)_newLockupComponentWithItem:(id)arg1 defaultStyle:(struct SKUILockupStyle { int x1; int x2; unsigned int x3; })arg2;
- (void)_setChildrenWithFeaturedContextContext:(id)arg1;
- (void)_reloadMissingItemCount;
- (id)initWithRoomContext:(id)arg1 gridType:(int)arg2;
- (id)initWithBrickItems:(id)arg1;
- (int)gridType;
- (id)metricsElementName;
- (BOOL)isMissingItemData;
- (void)enumerateMissingItemIdentifiersFromIndex:(int)arg1 usingBlock:(id)arg2;
- (id)initWithFeaturedContentContext:(id)arg1 kind:(int)arg2;
- (int)componentType;
- (id)initWithViewElement:(id)arg1;
- (id)initWithCustomPageContext:(id)arg1;
- (void).cxx_destruct;
- (id)description;

@end
