/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSString, NSMutableDictionary;

@interface SKUIReview : NSObject <SKUICacheCoding> {
    NSString *_body;
    NSString *_dateString;
    float _rating;
    NSString *_reviewer;
    NSString *_title;
}

@property(readonly) NSString * body;
@property(readonly) NSString * dateString;
@property(readonly) float rating;
@property(readonly) NSString * reviewer;
@property(readonly) NSString * title;
@property(readonly) NSMutableDictionary * cacheRepresentation;


- (id)formattedBylineWithClientContext:(id)arg1;
- (id)dateString;
- (id)cacheRepresentation;
- (id)initWithCacheRepresentation:(id)arg1;
- (id)initWithReviewDictionary:(id)arg1;
- (id)reviewer;
- (void).cxx_destruct;
- (id)body;
- (id)title;
- (float)rating;

@end
