/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUIITunesPassConfiguration, NSString, SKUIClientContext, SKUIRedeemITunesPassLockup, UIView, UIButton, <SKUIRedeemCameraViewDelegate>, SKUIRedeemCameraLandingView, UIImage, SKUIRedeemTextField;

@interface SKUIRedeemCameraView : UIView <UITextFieldDelegate> {
    SKUIClientContext *_clientContext;
    <SKUIRedeemCameraViewDelegate> *_delegate;
    SKUIRedeemTextField *_inputAccessoryTextField;
    SKUIITunesPassConfiguration *_iTunesPassConfiguration;
    SKUIRedeemITunesPassLockup *_iTunesPassLockup;
    SKUIRedeemCameraLandingView *_landingView;
    UIView *_overlay;
    UIView *_redeemerView;
    UIButton *_termsButton;
    SKUIRedeemTextField *_textField;
}

@property <SKUIRedeemCameraViewDelegate> * delegate;
@property(getter=isEnabled) BOOL enabled;
@property(retain) UIImage * image;
@property(retain) SKUIITunesPassConfiguration * ITunesPassConfiguration;
@property(copy) NSString * text;


- (void)_resumeRedeemer;
- (void)_hideKeyboard;
- (void)_showRedeemer:(BOOL)arg1;
- (void)_pauseRedeemer;
- (BOOL)_isShowingRedeemer;
- (void)_iTunesPassLearnMoreAction:(id)arg1;
- (void)textFieldTextDidChange:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)_tapGestureAction:(id)arg1;
- (id)_newTextFieldWithClientContext:(id)arg1 placeholderColor:(id)arg2;
- (void)_landingButtonAction:(id)arg1;
- (void)setITunesPassConfiguration:(id)arg1;
- (id)ITunesPassConfiguration;
- (void)_termsButtonAction:(id)arg1;
- (id)initWithClientContext:(id)arg1;
- (void).cxx_destruct;
- (void)showKeyboard;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;
- (id)image;
- (void)setText:(id)arg1;
- (id)text;
- (id)delegate;
- (void)layoutSubviews;
- (void)setImage:(id)arg1;
- (void)start;
- (void)dealloc;
- (void)setDelegate:(id)arg1;

@end
