/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSString, UILabel;

@interface SKUIGiftTableSectionHeaderView : UIView  {
    struct UIEdgeInsets { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _contentInsets;
    UILabel *_label;
}

@property struct UIEdgeInsets { float x1; float x2; float x3; float x4; } contentInsets;
@property(copy) NSString * label;


- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })contentInsets;
- (void)setContentInsets:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (void).cxx_destruct;
- (void)setLabel:(id)arg1;
- (id)label;
- (struct CGSize { float x1; float x2; })sizeThatFits:(struct CGSize { float x1; float x2; })arg1;
- (void)layoutSubviews;
- (void)setBackgroundColor:(id)arg1;

@end
