/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUIMediaQueryViewElement, SKUIViewElementLayoutContext, JSValue, JSContext, MPMediaQuery, IKViewElementFactory, NSMutableDictionary;

@interface SKUIMediaQueryPageSection : SKUIStorePageSection <SKUIArtworkRequestDelegate> {
    JSValue *_cellFactoryMethod;
    SKUIViewElementLayoutContext *_cellLayoutContext;
    JSContext *_cellScriptContext;
    MPMediaQuery *_query;
    int _queryStyle;
    id _styleFactory;
    SKUIMediaQueryViewElement *_viewElement;
    IKViewElementFactory *_viewElementFactory;
    NSMutableDictionary *_viewElements;
}


- (void)_enumerateVisibleViewElementsUsingBlock:(id)arg1;
- (id)_viewElementWithIndexPath:(id)arg1;
- (void)artworkRequest:(id)arg1 didLoadImage:(id)arg2;
- (Class)_cellClassForViewElement:(id)arg1;
- (int)numberOfCells;
- (id)cellForIndexPath:(id)arg1;
- (struct CGSize { float x1; float x2; })cellSizeForIndexPath:(id)arg1;
- (void)willAppearInContext:(id)arg1;
- (id)initWithPageComponent:(id)arg1;
- (void).cxx_destruct;

@end
