/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIOfferViewElement : SKUIViewElement  {
}

@property(getter=isSimpleOffer,readonly) BOOL simpleOffer;


- (int)pageComponentType;
- (BOOL)isSimpleOffer;
- (void)enumerateChildrenUsingBlock:(id)arg1;

@end
