/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUIViewElement, NSString;

@interface SKUIPageComponent : NSObject <SSMetricsEventFieldProvider> {
    int _metricsLocationPosition;
    SKUIViewElement *_viewElement;
}

@property(readonly) SKUIViewElement * viewElement;
@property(readonly) int componentType;
@property(getter=isMissingItemData,readonly) BOOL missingItemData;
@property(readonly) NSString * metricsElementName;
@property int metricsLocationPosition;


- (id)viewElement;
- (void)_setMetricsLocationPosition:(int)arg1;
- (int)metricsLocationPosition;
- (void)_enumerateMissingItemIdentifiersFromLockups:(id)arg1 startIndex:(int)arg2 usingBlock:(id)arg3;
- (void)_enumerateMissingItemIdentifiersFromLinks:(id)arg1 startIndex:(int)arg2 usingBlock:(id)arg3;
- (void)_enumerateMissingItemIdentifiersFromBricks:(id)arg1 startIndex:(int)arg2 usingBlock:(id)arg3;
- (id)metricsElementName;
- (BOOL)isMissingItemData;
- (void)enumerateMissingItemIdentifiersFromIndex:(int)arg1 usingBlock:(id)arg2;
- (id)initWithFeaturedContentContext:(id)arg1 kind:(int)arg2;
- (id)valueForMetricsField:(id)arg1;
- (int)componentType;
- (id)initWithViewElement:(id)arg1;
- (id)initWithCustomPageContext:(id)arg1;
- (void).cxx_destruct;

@end
