/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Social.framework/Social
 */

@interface SLSheetBevelledImageView : SLSheetImagePreviewView  {
}


- (struct CGSize { float x1; float x2; })intrinsicContentSize;
- (id)init;

@end
