/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Social.framework/Social
 */

@interface SLVideoAttachment : SLAttachment  {
}


- (id)initWithVideoData:(id)arg1 preview:(id)arg2;
- (id)initWithAsset:(id)arg1 preview:(id)arg2;

@end
