/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@class NSURL, NSString;

@interface SPApp : SPProxyObject <PRSApp> {
}

@property(retain) NSString * name;
@property(retain) NSString * bundle_id;
@property(retain) NSURL * install_url;
@property(retain) NSURL * punchout_uri;



@end
