/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Stocks.framework/Stocks
 */

@class NSArray, GraphRenderOperation, StockChartDisplayMode, NSMutableArray, StockChartData, VolumeGraphView, UIView<StockGraphViewContainer>, LineGraphView;

@interface StockGraphView : UIView <GraphRenderOperationDelegate> {
    LineGraphView *_lineView;
    VolumeGraphView *_volumeView;
    UIView<StockGraphViewContainer> *_chartViewDelegate;
    StockChartData *_chartData;
    int _valueIndex;
    int _valueCount;
    struct CGPoint { float x1; float x2; } *_points;
    struct CGPoint { float x1; float x2; } *_values;
    NSMutableArray *_linePointCounts;
    NSArray *_dottedLinePositions;
    NSArray *_dottedLinePositionsForStyleOnly;
    unsigned int _dataSize;
    unsigned int _dataCount;
    struct { float x1; unsigned long long x2; } *_volumeBars;
    unsigned int _volumeSize;
    unsigned int _volumeCount;
    float _volumeBarWidth;
    unsigned long long _maxVolume;
    GraphRenderOperation *_renderOperation;
    BOOL _isRendered;
    StockChartDisplayMode *_displayMode;
    struct UIEdgeInsets { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _graphInsets;
}

@property UIView<StockGraphViewContainer> * chartViewDelegate;
@property(readonly) BOOL isRendered;
@property(readonly) BOOL isRendering;
@property struct UIEdgeInsets { float x1; float x2; float x3; float x4; } graphInsets;
@property(retain) StockChartDisplayMode * displayMode;


- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })graphInsets;
- (BOOL)isRendered;
- (void)setChartViewDelegate:(id)arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })volumeBarRectNearestToPoint:(struct CGPoint { float x1; float x2; })arg1;
- (struct { double x1; double x2; unsigned long long x3; })plottedPointNearestToPoint:(struct CGPoint { float x1; float x2; }*)arg1;
- (struct CGPoint { float x1; float x2; })rightmostPlottedPoint;
- (void)loadStockChartData:(id)arg1;
- (void)recomputePathsAndRenderIfNeededForSize:(struct CGSize { float x1; float x2; })arg1;
- (BOOL)isRendering;
- (void)setEvenlySpacedDottedLinePositionsWithCount:(unsigned int)arg1;
- (void)setDottedLinePositionsWithLabelInfo:(id)arg1;
- (void)setShowingSelectedVolumeRegion:(BOOL)arg1;
- (void)graphRenderOperationDidFinish:(id)arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_trueGraphPointsRegion;
- (void)clearData;
- (void)resizeSelectedVolumeClipViewWithLeftX:(float)arg1 rightX:(float)arg2;
- (void)resizeSelectedLineClipViewWithLeftX:(float)arg1 rightX:(float)arg2;
- (void)setGraphInsets:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (void)readyForDisplayFromChartData;
- (void)_processGraphDataForWidth:(float)arg1;
- (void)cancelRenderOperation;
- (id)chartViewDelegate;
- (unsigned long long)_normalizedAccumulatedVolumeInDataRange:(struct CGPoint { float x1; float x2; })arg1;
- (double)_timeAtPosition:(double)arg1;
- (float)_priceAtTime:(double)arg1 dataPosition:(double*)arg2;
- (void)_finishCurrentLine;
- (void)clearPaths;
- (void)setShowingSelectedLine:(BOOL)arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_volumeViewFrameForBoundsSize:(struct CGSize { float x1; float x2; })arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_lineViewFrameForBoundsSize:(struct CGSize { float x1; float x2; })arg1;
- (void)_layoutSubviews;
- (void)setDisplayMode:(id)arg1;
- (void).cxx_destruct;
- (id)displayMode;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)dealloc;

@end
