/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@class UILabel;

@interface SubtitleCellWithAdditionalDetail : UITableViewCell  {
    UILabel *_additionalDetailLabel;
}

@property(retain,readonly) UILabel * additionalDetailLabel;


- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)additionalDetailLabel;

@end
