/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@class NSNumber;

@interface SUScriptReportAProblemViewController : SUScriptViewController  {
}

@property(readonly) NSNumber * adamID;

+ (id)webScriptNameForKeyName:(id)arg1;
+ (void)initialize;

- (void)setAdamID:(id)arg1;
- (id)initWithAdamID:(id)arg1 clientInterface:(id)arg2;
- (id)newNativeViewController;
- (id)adamID;
- (id)attributeKeys;
- (id)_className;
- (id)scriptAttributeKeys;
- (id)init;

@end
