/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@interface SUScriptStoreSheetViewController : SUScriptViewController  {
}

@property int productPageStyle;
@property(readonly) int productPageStyleAutomatic;
@property(readonly) int productPageStylePad;
@property(readonly) int productPageStylePhone;

+ (id)webScriptNameForKeyName:(id)arg1;
+ (id)webScriptNameForSelector:(SEL)arg1;
+ (void)initialize;

- (void)loadWithProductURL:(id)arg1;
- (id)newNativeViewController;
- (id)attributeKeys;
- (int)productPageStylePhone;
- (int)productPageStylePad;
- (int)productPageStyleAutomatic;
- (id)_className;
- (id)scriptAttributeKeys;
- (void)loadWithProductParameters:(id)arg1;
- (void)setProductPageStyle:(int)arg1;
- (int)productPageStyle;

@end
