/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface TCBundleResourceDebugEntry : NSObject  {
    unsigned int mCacheCount;
    unsigned int mUncachedCount;
}

+ (void)dumpUsage;
+ (void)addEntry:(id)arg1 ofType:(id)arg2 inPackage:(id)arg3 cacheResult:(BOOL)arg4;


@end
