/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@class CoreThemeDocument, NSThread;

@interface TDThreadMOCOrganizer : NSObject  {
    NSThread *mainThread;
    CoreThemeDocument *document;
}


- (void)setThreadMOC:(id)arg1;
- (id)mainMOC;
- (id)threadMOC;
- (id)initWithDocument:(id)arg1 mainThread:(id)arg2;
- (id)document;
- (id)init;
- (id)mainThread;

@end
