/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TIKeyboardBehaviorState : NSObject  {
    BOOL hasInput;
    BOOL hasCandidates;
    BOOL hasCandidateSelected;
    BOOL hasNextPage;
    BOOL showsExtendedList;
    BOOL followsZhuyin;
    BOOL spaceConfirmation;
    BOOL _hasAutocorrection;
    BOOL _showsCandidatesInLayout;
}

@property BOOL hasInput;
@property BOOL hasAutocorrection;
@property BOOL hasCandidates;
@property BOOL hasCandidateSelected;
@property BOOL hasNextPage;
@property BOOL showsExtendedList;
@property BOOL followsZhuyin;
@property BOOL spaceConfirmation;
@property BOOL showsCandidatesInLayout;


- (BOOL)showsCandidatesInLayout;
- (BOOL)spaceConfirmation;
- (BOOL)followsZhuyin;
- (BOOL)showsExtendedList;
- (void)setSpaceConfirmation:(BOOL)arg1;
- (void)setFollowsZhuyin:(BOOL)arg1;
- (void)setShowsCandidatesInLayout:(BOOL)arg1;
- (void)setShowsExtendedList:(BOOL)arg1;
- (void)setHasNextPage:(BOOL)arg1;
- (void)setHasCandidateSelected:(BOOL)arg1;
- (void)setHasCandidates:(BOOL)arg1;
- (void)setHasAutocorrection:(BOOL)arg1;
- (void)setHasInput:(BOOL)arg1;
- (BOOL)hasAutocorrection;
- (BOOL)hasCandidateSelected;
- (BOOL)hasInput;
- (BOOL)hasNextPage;
- (BOOL)hasCandidates;

@end
