/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/RTCReporting.framework/RTCReporting
 */

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface TimingCollection : NSObject  {
    NSMutableDictionary *timings;
    NSObject<OS_dispatch_queue> *queue;
}


- (void)resetTotalTimeForKey:(id)arg1;
- (void)removeTimingForKey:(id)arg1;
- (float)totalTimeForKey:(id)arg1;
- (float)timingForKey:(id)arg1;
- (BOOL)hasKey:(id)arg1;
- (void)stopTimingForKey:(id)arg1;
- (void)startTimingForKey:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)init;

@end
