/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TNPrintProperties : NSObject  {
    float _headerInset;
    float _footerInset;
    struct CGSize { 
        float width; 
        float height; 
    } _unscaledPageSize;
    struct UIEdgeInsets { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _printMargins;
}

@property struct CGSize { float x1; float x2; } unscaledPageSize;
@property(readonly) float pageHeight;
@property(readonly) float pageWidth;
@property struct UIEdgeInsets { float x1; float x2; float x3; float x4; } printMargins;
@property float headerInset;
@property float footerInset;

+ (id)legacyExportPrintProperties;
+ (id)letterSizeLandscapeFormPrintProperties;
+ (id)letterSizePortraitFormPrintProperties;
+ (id)a4SizePrintProperties;
+ (id)letterSizePrintProperties;

- (float)pageHeight;
- (float)pageWidth;
- (struct CGAffineTransform { float x1; float x2; float x3; float x4; float x5; float x6; })p_transformForContentScale:(float)arg1 portraitOrientation:(BOOL)arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })p_unscaledContentRectForOrientation:(BOOL)arg1 headerHeight:(float)arg2 footerHeight:(float)arg3;
- (float)footerInset;
- (float)headerInset;
- (id)initWithPageSize:(struct CGSize { float x1; float x2; })arg1 contentRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg2;
- (void)setFooterInset:(float)arg1;
- (void)setHeaderInset:(float)arg1;
- (void)setUnscaledPageSize:(struct CGSize { float x1; float x2; })arg1;
- (float)contentScaleForIntegralWidthWithContentScale:(float)arg1 portraitOrientation:(BOOL)arg2;
- (id)initWithPageSize:(struct CGSize { float x1; float x2; })arg1 printMargins:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg2;
- (struct CGSize { float x1; float x2; })pageSizeWithGutterForContentScale:(float)arg1 portraitOrientation:(BOOL)arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })contentRectForContentScale:(float)arg1 portraitOrientation:(BOOL)arg2 headerHeight:(float)arg3 footerHeight:(float)arg4;
- (struct CGSize { float x1; float x2; })pageSizeForContentScale:(float)arg1 portraitOrientation:(BOOL)arg2;
- (id)initWithPageSize:(struct CGSize { float x1; float x2; })arg1 printMargins:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg2 headerInset:(float)arg3 footerInset:(float)arg4;
- (void)setPrintMargins:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })printMargins;
- (struct CGSize { float x1; float x2; })unscaledPageSize;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })unscaledPageRectForDisplayForPortraitOrientation:(BOOL)arg1 atPageCoordinate:(struct { unsigned short x1; unsigned char x2; unsigned char x3; })arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })pageHeaderFooterRectForContentScale:(float)arg1 portraitOrientation:(BOOL)arg2 footer:(BOOL)arg3 textHeight:(float)arg4;

@end
