/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

@interface TPNumberPadDarkStyleButton : TPNumberPadButton  {
}

+ (float)unhighlightCrossfadeHighlightFadeDuration;
+ (float)unhighlightCrossfadeNormalFadeDuration;
+ (float)unhighlightCrossfadeHighlightBeginTime;
+ (float)unhighlightCrossfadeNormalBeginTime;
+ (float)highlightCrossfadeHighlightFadeDuration;
+ (float)highlightCrossfadeNormalFadeDuration;
+ (float)highlightCrossfadeHighlightBeginTime;
+ (float)highlightCrossfadeNormalBeginTime;
+ (id)imageForCharacter:(unsigned int)arg1 highlighted:(BOOL)arg2;
+ (id)imageForCharacter:(unsigned int)arg1;

- (id)defaultColor;

@end
