/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSString;

@interface TSCH3DPerElementAlphaBlendShaderEffect : TSCH3DShaderEffect  {
    NSString *mFunctionName;
}

@property(readonly) NSString * functionName;

+ (id)variablePerElementAlphaBlendValue;
+ (id)variablePerElementAlphaBlendInterpolationRange;
+ (void)setInterpolationRange:(struct box<glm::detail::tvec1<float> > { struct tvec1<float> { union { float x_1_2_1; float x_1_2_2; float x_1_2_3; } x_1_1_1; } x1; struct tvec1<float> { union { float x_1_2_1; float x_1_2_2; float x_1_2_3; } x_2_1_1; } x2; })arg1 effectsStates:(id)arg2;
+ (id)effectWithInterpolationFunctionName:(id)arg1;

- (id)functionName;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)variablePerElementAlphaBlendValue;
- (id)variablePerElementAlphaBlendInterpolationRange;
- (id)initWithInterpolationFunctionName:(id)arg1;
- (void)uploadData:(id)arg1 effectsStates:(id)arg2;
- (void)inject:(id)arg1;
- (void)addVariables:(id)arg1;

@end
