/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartTypeMultiDataBar : TSCHMultiDataChartType  {
}


- (id)init;
- (Class)presetImagerClass;
- (id)userInterfaceName;
- (id)defaultSeriesType:(unsigned int)arg1;
- (Class)repClass;
- (id)genericToSpecificPropertyMap;

@end
