/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class <TSCH3DSharegroupDelayCheckerParent>;

@interface TSCH3DSharegroupDelayChecker : NSObject <TSCHUnretainedParent> {
    BOOL mCondition;
    <TSCH3DSharegroupDelayCheckerParent> *mParent;
}

@property BOOL condition;


- (id)initWithParent:(id)arg1;
- (void)setCondition:(BOOL)arg1;
- (BOOL)condition;
- (void)dealloc;
- (void)invalidateCondition;
- (void)scheduleCheckCondition;
- (void)clearParent;
- (void)p_cancelCheckCondition;
- (void)p_scheduleCheckConditionOnMainThread;
- (void)p_checkCondition;

@end
