/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class <TSCH3DSharegroupDelegate>, TSCH3DResourceCache, NSThread, NSMutableSet, TSCH3DSharegroupToken, TSCH3DShaderCache;

@interface TSCH3DSharegroup : NSObject <TSUFlushable> {
    NSThread *mOwningThread;
    TSCH3DResourceCache *mResourceCache;
    TSCH3DShaderCache *mShaderCache;
    NSMutableSet *mPurgeableResourceSet;
    int mPerformance;
    BOOL mDidReceiveFlush;
    <TSCH3DSharegroupDelegate> *mDelegate;
    TSCH3DSharegroupToken *mToken;
}

@property int performance;
@property <TSCH3DSharegroupDelegate> * delegate;
@property(readonly) TSCH3DResourceCache * resourceCache;
@property(readonly) TSCH3DShaderCache * shaderCache;
@property(readonly) TSCH3DSharegroupToken * token;

+ (id)uniqueSharegroupWithOwningThread:(id)arg1 token:(id)arg2;

- (void)setOwningThread:(id)arg1;
- (void)flushIfNecessary;
- (id)resourceCache;
- (id)token;
- (id)delegate;
- (id)description;
- (void)flush;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (id)init;
- (id)shaderCache;
- (int)performance;
- (void)flushInTargetThread;
- (void)setIfIsMoreDemandingPerformance:(int)arg1;
- (void)forceFlushResourceSet:(id)arg1;
- (void)flushResourceSet:(id)arg1;
- (void)flushMemoryForResourceSet:(id)arg1;
- (BOOL)isCurrentThreadOwner;
- (BOOL)owningThreadIsNil;
- (void)p_flushInTargetThread;
- (struct FlushResult { BOOL x1; BOOL x2; })p_flushCacheIfNecessary;
- (BOOL)mustRunOnMainThread;
- (BOOL)isOneShot;
- (id)initWithOwningThread:(id)arg1 token:(id)arg2;
- (void)setPerformance:(int)arg1;
- (void)nonThreadOwnedFlushCache;

@end
