/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSArray, TSCH3DSceneRenderPipeline;

@interface TSCH3DTileImageSceneRenderPipeline : TSCH3DTileSceneRenderPipeline  {
    unsigned int mTileSize;
    TSCH3DSceneRenderPipeline *mTargetPipeline;
    BOOL mSingleOutputImage;
    NSArray *mImages;
    unsigned int mTileSamples;
    unsigned int mTileOverlap;
    BOOL mFlipImages;
}

@property BOOL singleOutputImage;
@property BOOL flipImages;
@property unsigned int tileSize;
@property unsigned int tileSamples;
@property unsigned int tileOverlap;
@property(retain) TSCH3DSceneRenderPipeline * targetPipeline;
@property(readonly) NSArray * images;


- (unsigned int)tileSize;
- (BOOL)run;
- (void)setTileSize:(unsigned int)arg1;
- (id)images;
- (void)dealloc;
- (id)init;
- (void)setTargetPipeline:(id)arg1;
- (id)targetPipeline;
- (void)setTileOverlap:(unsigned int)arg1;
- (unsigned int)tileOverlap;
- (void)setFlipImages:(BOOL)arg1;
- (void)setSingleOutputImage:(BOOL)arg1;
- (BOOL)singleOutputImage;
- (BOOL)processTile:(id)arg1 generator:(id)arg2;
- (BOOL)flipImages;
- (id)cloneTargetPipeline:(id)arg1;
- (void)setTileSamples:(unsigned int)arg1;
- (unsigned int)tileSamples;

@end
