/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHCallbackAnimationDelegate : NSObject  {
    id target;
    SEL selector;
}

@property(retain) id target;
@property SEL selector;


- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (SEL)selector;
- (id)target;
- (void)setSelector:(SEL)arg1;
- (void)setTarget:(id)arg1;
- (void)dealloc;

@end
