/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartSeriesTypeMixedArea : TSCHChartSeriesTypeArea  {
}


- (id)g_genericToSpecificPropertyMapMixedArea;
- (BOOL)supportsSymbolFillForSymbolType:(int)arg1;
- (BOOL)supportsSymbolDrawing;
- (id)genericToSpecificPropertyMap;

@end
