/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSMutableDictionary;

@interface TSCH3DDictionaryOfSet : NSObject <NSFastEnumeration> {
    NSMutableDictionary *mSets;
}

+ (id)dictionary;
+ (id)dictionaryWithMutableDictionaryClass:(Class)arg1;

- (void)removeObject:(id)arg1 forKey:(id)arg2;
- (id)objectsForKey:(id)arg1;
- (id)allKeys;
- (unsigned int)countByEnumeratingWithState:(struct { unsigned long x1; id *x2; unsigned long *x3; unsigned long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned int)arg3;
- (id)description;
- (unsigned int)count;
- (void)dealloc;
- (id)init;
- (void)addObject:(id)arg1 forKey:(id)arg2;
- (id)initWithMutableDictionaryClass:(Class)arg1;

@end
