/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartFeatureTwoAxis : TSCHChartFeatureCategory  {
}


- (void)p_initializeAxisIDs;
- (BOOL)supportsIndividualShadowRendering;
- (void)updateTitlesForExportingModel:(id)arg1 info:(id)arg2;
- (BOOL)supportsConnectingLines;
- (BOOL)supportsSymbolOverhang;
- (BOOL)supportsEditing;
- (BOOL)supportsGroupedShadows;
- (id)supportedSeriesTypes;
- (Class)presetImagerClass;
- (id)userInterfaceName;
- (id)defaultDataFileName;
- (BOOL)requiresYAxisOrdinal;
- (BOOL)supportsMultipleSeriesTypes;
- (Class)valueAxisClassForID:(id)arg1 scale:(int)arg2;
- (unsigned int)styleIndexForAxisID:(id)arg1;
- (id)supportedAxisScales;
- (id)genericToSpecificPropertyMap;

@end
