/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class TSCH3DUniformArrayShaderVariables;

@interface TSCH3DLightUniformArrayShaderVariables : NSObject  {
    TSCH3DUniformArrayShaderVariables *mVariables;
}


- (void)dealloc;
- (void)initializePrefix:(id)arg1;
- (void)initializeArrayVariables;
- (void)addUniformsToShaderProgram:(id)arg1 size:(unsigned int)arg2;
- (unsigned int)arraySize;
- (id)variableAtIndex:(unsigned int)arg1 name:(id)arg2;

@end
