/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DTSDGLLayerContext : NSObject <TSDGLLayerContext> {
}

+ (id)layerContext;

- (void)teardown;
- (BOOL)isValid;
- (BOOL)makeCurrentContext;
- (void)dealloc;
- (void)presentRenderbuffer;
- (BOOL)createFramebufferFromLayer:(id)arg1;

@end
