/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSMutableArray, NSArray;

@interface TSCH3DGeometryVertexFormat : NSObject  {
    NSMutableArray *mElements;
    unsigned int mStride;
    unsigned int mTotalComponents;
    int mVertexCount;
    BOOL mCompiled;
}

@property(readonly) BOOL compiled;
@property(readonly) unsigned int stride;
@property(readonly) unsigned int totalComponents;
@property(readonly) NSArray * elements;


- (void)enumerateElementsUsingBlock:(id)arg1;
- (id)elements;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)init;
- (unsigned int)stride;
- (BOOL)compiled;
- (void)compile;
- (id)elementForName:(id)arg1 bufferInfo:(const struct DataBufferInfo { int x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; }*)arg2;
- (unsigned int)totalComponents;

@end
