/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@class TSUColor;

@interface TSDGradientStop : NSObject <TSDMixing, NSCopying, NSMutableCopying> {
    TSUColor *mColor;
    float mFraction;
    float mInflection;
}

@property(copy,readonly) TSUColor * color;
@property(readonly) float fraction;
@property(readonly) float inflection;

+ (id)gradientStopWithColor:(id)arg1 fraction:(float)arg2 inflection:(float)arg3;
+ (id)gradientStopWithColor:(id)arg1 fraction:(float)arg2;

- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)color;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)gradientStopWithInflection:(float)arg1;
- (id)initWithColor:(id)arg1 fraction:(float)arg2;
- (void)p_setInflection:(float)arg1;
- (void)p_setColor:(id)arg1;
- (id)initWithColor:(id)arg1 fraction:(float)arg2 inflection:(float)arg3;
- (void)p_setFraction:(float)arg1;
- (id)initWithGradientStop:(id)arg1;
- (id)gradientStopWithColor:(id)arg1;
- (float)inflection;
- (id)mixedObjectWithFraction:(float)arg1 ofObject:(id)arg2;
- (int)mixingTypeWithObject:(id)arg1;
- (id)initWithArchive:(const struct GradientArchive_GradientStop { int (**x1)(); struct UnknownFieldSet { struct vector<google::protobuf::UnknownField, std::__1::allocator<google::protobuf::UnknownField> > {} *x_2_1_1; } x2; struct Color {} *x3; float x4; float x5; int x6; unsigned int x7[1]; }*)arg1 unarchiver:(id)arg2;
- (void)saveToArchive:(struct GradientArchive_GradientStop { int (**x1)(); struct UnknownFieldSet { struct vector<google::protobuf::UnknownField, std::__1::allocator<google::protobuf::UnknownField> > {} *x_2_1_1; } x2; struct Color {} *x3; float x4; float x5; int x6; unsigned int x7[1]; }*)arg1 archiver:(id)arg2;
- (float)fraction;

@end
