/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class TSDInfoGeometry;

@interface TSDMovieLayout : TSDMediaLayout  {
    TSDInfoGeometry *mDynamicInfoGeometry;
}


- (id)movieInfo;
- (void)dealloc;
- (id)initWithInfo:(id)arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })fullReflectionBoundsForRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })fullReflectionFrame;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })computeAlignmentFrameInRoot:(BOOL)arg1;
- (void)p_destroyDynamicCopies;
- (void)p_createDynamicCopies;
- (id)i_computeWrapPath;
- (void)takeRotationFromTracker:(id)arg1;
- (BOOL)supportsRotation;
- (void)processChangedProperty:(int)arg1;
- (id)computeLayoutGeometry;
- (id)layoutGeometryFromInfo;
- (void)endResize;
- (void)endDynamicOperation;
- (void)beginDynamicOperation;
- (void)takeSizeFromTracker:(id)arg1;

@end
