/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSObject<TSSPreset>;

@interface TSDMediaApplyPresetCommand : TSDStyledInfoSetStyleCommand  {
    NSObject<TSSPreset> *mPreset;
}

@property(readonly) NSObject<TSSPreset> * preset;


- (id)preset;
- (void)dealloc;
- (id)initWithMediaInfo:(id)arg1 presetKind:(id)arg2 index:(unsigned int)arg3;
- (id)initWithMediaInfo:(id)arg1 preset:(id)arg2;
- (void)computeStyle;
- (void)saveToArchiver:(id)arg1;
- (id)initFromUnarchiver:(id)arg1;

@end
