/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSKCommandSelectionBehavior : TSPObject  {
}

@property(readonly) BOOL modifiesUndoRedoState;


- (BOOL)modifiesUndoRedoState;
- (void)registerSelectionChangesForRedo;
- (void)registerSelectionChangesForUndo;
- (void)registerSelectionChangesForCommit;

@end
