/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@class NSError, <TSPPackage>, SFUCryptoKey, NSObject<OS_dispatch_queue>, <TSPComponentWriteChannel>, TSPBundle, TSUZipFileWriter, NSURL;

@interface TSPBundleWriter : NSObject <TSPPackageWriter> {
    NSURL *_URL;
    SFUCryptoKey *_encryptionKey;
    <TSPPackage> *_originalDocumentPackage;
    <TSPPackage> *_originalSupportPackage;
    TSUZipFileWriter *_objectArchiveWriter;
    <TSPComponentWriteChannel> *_componentWriteChannel;
    NSObject<OS_dispatch_queue> *_errorQueue;
    NSError *_error;
    TSPBundle *_writtenBundle;
    BOOL _isClosed;
    BOOL _obscureAssetFilenames;
    NSURL *_documentTargetURL;
    NSURL *_relativeURLForExternalData;
}

@property BOOL obscureAssetFilenames;
@property(readonly) NSURL * documentTargetURL;
@property(readonly) NSURL * relativeURLForExternalData;


- (void).cxx_destruct;
- (void)dealloc;
- (void)setObscureAssetFilenames:(BOOL)arg1;
- (id)linkOrCopyData:(id)arg1 fromURL:(id)arg2 decryptionKey:(id)arg3 preferredFilename:(id)arg4;
- (id)documentTargetURL;
- (BOOL)addData:(id)arg1 infoMessage:(struct DataInfo { int (**x1)(); struct UnknownFieldSet { struct vector<google::protobuf::UnknownField, std::__1::allocator<google::protobuf::UnknownField> > {} *x_2_1_1; } x2; unsigned long long x3; struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > {} *x4; struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > {} *x5; struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > {} *x6; struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > {} *x7; struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > {} *x8; struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > {} *x9; int x10; unsigned int x11[1]; }*)arg2 saveOperationState:(id)arg3;
- (void)copyComponent:(id)arg1 locator:(id)arg2 completion:(id)arg3;
- (id)newComponentWriteChannelWithPackageLocator:(id)arg1 storeOutsideObjectArchive:(BOOL)arg2;
- (BOOL)obscureAssetFilenames;
- (id)filenameForData:(id)arg1 preferredFilename:(id)arg2;
- (BOOL)createDirectoryAtURL:(id)arg1 withIntermediateDirectories:(BOOL)arg2;
- (id)writtenPackageWithURL:(id)arg1;
- (BOOL)writeData:(id)arg1 toPath:(id)arg2 error:(id*)arg3;
- (id)initWithURL:(id)arg1 documentTargetURL:(id)arg2 relativeURLForExternalData:(id)arg3 packageIdentifier:(unsigned char)arg4 documentProperties:(id)arg5 fileFormatVersion:(unsigned long long)arg6 encryptionKey:(id)arg7 originalDocumentPackage:(id)arg8 originalSuppportPackage:(id)arg9 fileCoordinatorDelegate:(id)arg10 error:(id*)arg11;
- (id)relativeURLForExternalData;
- (void)closeWithQueue:(id)arg1 completion:(id)arg2;

@end
