/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class <TSPProxyObjectManager>;

@interface TSPPasteboardArchiver : TSPArchiver  {
    <TSPProxyObjectManager> *_proxyManager;
}

@property <TSPProxyObjectManager> * proxyManager;


- (void).cxx_destruct;
- (void)setProxyManager:(id)arg1;
- (id)proxyManager;
- (void)setWeakLazyReference:(id)arg1 message:(struct Reference { }*)arg2;
- (BOOL)forPasteboard;
- (void)setStrongLazyReference:(id)arg1 message:(struct Reference { }*)arg2;
- (void)setWeakReference:(id)arg1 message:(struct Reference { }*)arg2;
- (void)setStrongReference:(id)arg1 message:(struct Reference { }*)arg2;

@end
