/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSMutableArray, TSTMasterLayout;

@interface TSTLayoutTask : NSObject <NSCopying> {
    TSTMasterLayout *mMasterLayout;
    NSMutableArray *mCellStatesToLayout;
}

@property(readonly) unsigned int numberOfCellStates;


- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)clear;
- (void)dealloc;
- (id)initWithLayoutTask:(id)arg1;
- (void)writeToMasterLayoutCaches;
- (void)enumerateCellStatesUsingBlock:(id)arg1;
- (unsigned int)numberOfCellStates;
- (void)addCellState:(id)arg1;
- (id)initWithMasterLayout:(id)arg1;

@end
