/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class TSUBasicProgressStorage;

@interface TSUBasicProgress : TSUProgress  {
    TSUBasicProgressStorage *mStorage;
}

@property double value;
@property(getter=isIndeterminate) BOOL indeterminate;


- (id)initWithMaxValue:(double)arg1;
- (void)setIndeterminate:(BOOL)arg1;
- (BOOL)isIndeterminate;
- (double)value;
- (void)setValue:(double)arg1;
- (double)maxValue;
- (void)dealloc;
- (id)init;

@end
