/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSMutableDictionary, NSMutableArray;

@interface TSUHTMLTable : NSObject  {
    NSMutableDictionary *_columnAttributes;
    NSMutableDictionary *_rowClasses;
    NSMutableDictionary *_cellAttributes;
    NSMutableArray *_columnHeaders;
    NSMutableArray *_rows;
    unsigned int _rowClassStride;
}

@property(readonly) unsigned int lastRowIndex;
@property(readonly) unsigned int count;
@property unsigned int rowClassStride;

+ (id)htmlTable;
+ (id)_attributesStringFromAttributes:(id)arg1;
+ (id)_keyForCell:(unsigned int)arg1 :(unsigned int)arg2;

- (void)setRowClassStride:(unsigned int)arg1;
- (unsigned int)rowClassStride;
- (void)deleteColumnWithTitle:(id)arg1;
- (void)enumerateRowsUsingBlock:(id)arg1;
- (void)setCellAttributes:(id)arg1 rowIndex:(unsigned int)arg2 columnIndex:(unsigned int)arg3;
- (void)setCellMarkup:(id)arg1 atRowIndex:(unsigned int)arg2 columnIndex:(unsigned int)arg3;
- (void)setColumnHeaders:(id)arg1;
- (void)setRowClass:(id)arg1 atRowIndex:(unsigned int)arg2;
- (void)setColumnClasses:(id)arg1;
- (void)addRowWithCellText:(id)arg1;
- (id)markup;
- (unsigned int)lastRowIndex;
- (unsigned int)indexOfColumnWithTitle:(id)arg1;
- (void)setClass:(id)arg1 ofColumnIndex:(unsigned int)arg2;
- (void)addRowWithCellMarkup:(id)arg1;
- (unsigned int)count;
- (void)dealloc;
- (id)init;

@end
