/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class TSUProgressStage, NSDate;

@interface TSUProgressContext : NSObject  {
    TSUProgressStage *m_currentStage;
    NSDate *m_lastReportTime;
    double m_lastProgressReport;
    double m_lastOverallProgress;
}


- (void)addProgressObserver:(id)arg1 selector:(SEL)arg2;
- (double)overallProgress;
- (void)removeProgressObserver:(id)arg1;
- (void)reportProgress:(double)arg1 overallProgress:(double)arg2;
- (void)setPercentageProgressFromTCProgressContext:(double)arg1;
- (void)endStage;
- (void)nextSubStageWillTakeThisManyOfMySteps:(double)arg1;
- (void)createStageWithSteps:(double)arg1;
- (id)addProgressObserverBlock:(id)arg1;
- (double)currentPosition;
- (void)advanceProgress:(double)arg1;
- (id)currentStage;
- (void)createStageWithSteps:(double)arg1 takingSteps:(double)arg2;
- (void)reset;
- (void)setMessage:(id)arg1;
- (void)setProgress:(double)arg1;
- (void)dealloc;
- (id)init;

@end
