/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSWPCharacterStyler : TSWPStorageStyler  {
}


- (void)applyStyle:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2 undoTransaction:(struct TSWPStorageTransaction { }*)arg3;
- (void)performStylingInRange:(struct _NSRange { unsigned int x1; unsigned int x2; })arg1 undoTransaction:(struct TSWPStorageTransaction { }*)arg2;
- (id)initWithStorage:(id)arg1;

@end
