/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSString;

@interface TSWPFontCacheKey : NSObject  {
    NSString *_fontName;
    float _fontSize;
    unsigned int _hash;
}

@property(readonly) NSString * fontName;
@property(readonly) float fontSize;

+ (id)cacheKeyWithFontName:(id)arg1 size:(float)arg2;

- (float)fontSize;
- (id)fontName;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithFontName:(id)arg1 size:(float)arg2;

@end
