/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@class TSSStyle<TSSPreset>;

@interface TSWPStyleUpdateCommand : TSWPStyleBaseCommand  {
    TSSStyle<TSSPreset> *_originalStyle;
    TSSStyle<TSSPreset> *_updatedStyle;
}

@property(retain,readonly) TSSStyle<TSSPreset> * originalStyle;
@property(retain) TSSStyle<TSSPreset> * updatedStyle;


- (id)actionString;
- (void)redo;
- (void)undo;
- (void)commit;
- (void)dealloc;
- (void)setUpdatedStyle:(id)arg1;
- (id)initWithTheme:(id)arg1 style:(id)arg2 updatedStyle:(id)arg3;
- (id)updatedStyle;
- (id)originalStyle;
- (void)p_invalidateStorages;
- (void)p_CommitAndRedo;
- (void)loadFromMessage:(const struct StyleUpdateCommandArchive { int (**x1)(); struct UnknownFieldSet { struct vector<google::protobuf::UnknownField, std::__1::allocator<google::protobuf::UnknownField> > {} *x_2_1_1; } x2; struct StyleBaseCommandArchive {} *x3; struct Reference {} *x4; struct Reference {} *x5; int x6; unsigned int x7[1]; }*)arg1 unarchiver:(id)arg2;
- (void)saveToMessage:(struct StyleUpdateCommandArchive { int (**x1)(); struct UnknownFieldSet { struct vector<google::protobuf::UnknownField, std::__1::allocator<google::protobuf::UnknownField> > {} *x_2_1_1; } x2; struct StyleBaseCommandArchive {} *x3; struct Reference {} *x4; struct Reference {} *x5; int x6; unsigned int x7[1]; }*)arg1 archiver:(id)arg2;
- (void)saveToArchiver:(id)arg1;
- (id)initFromUnarchiver:(id)arg1;

@end
