/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class TSDFloatingCommentDeleteKnob, CALayer, TSDFloatingCommentControlKnob;

@interface TSWPCommentRep : TSWPShapeRep  {
    BOOL _shouldShowNavigationKnobs;
    TSDFloatingCommentControlKnob *_previousKnob;
    TSDFloatingCommentControlKnob *_nextKnob;
    TSDFloatingCommentDeleteKnob *_deleteKnob;
    BOOL _didNavigate;
    CALayer *_headerLayer;
    CALayer *_dateLayer;
    CALayer *_authorLayer;
    BOOL _needsAuthorOrDateUpdate;
}


- (struct CGColor { }*)selectionHighlightColor;
- (void)drawInContext:(struct CGContext { }*)arg1;
- (void)dealloc;
- (id)p_imageForString:(id)arg1 ofSize:(struct CGSize { float x1; float x2; })arg2 baselineOffsetFromBottom:(float)arg3 foregroundColor:(struct CGColor { }*)arg4;
- (void)p_nextAnnotation;
- (void)p_previousAnnotation;
- (void)p_deleteComment;
- (BOOL)p_shouldDraw;
- (float)p_effectiveBorderStrokeWidthInPoints;
- (BOOL)canBeUsedForImageMask;
- (BOOL)canMakePathEditable;
- (BOOL)shouldShowSmartShapeKnobs;
- (BOOL)shouldHideSelectionHighlightDueToRectangularPath;
- (BOOL)handleSingleTapAtPoint:(struct CGPoint { float x1; float x2; })arg1 onKnob:(id)arg2;
- (BOOL)exclusivelyProvidesGuidesWhileAligning;
- (BOOL)providesGuidesWhileAligning;
- (void)dynamicOperationDidBegin;
- (BOOL)forcesPlacementOnTop;
- (BOOL)canUseSpecializedHitRegionForKnob:(id)arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })boundsForHighlightLayer;
- (float)selectionHighlightWidth;
- (unsigned long long)enabledKnobMask;
- (void)recursivelyDrawChildrenInContext:(struct CGContext { }*)arg1;
- (id)additionalLayersOverLayer;
- (void)screenScaleDidChange;
- (void)invalidateAnnotationColor;
- (void)invalidateComments;
- (void)willEndEditingContainedRep;
- (void)willBeginEditingContainedRep;
- (BOOL)directlyManagesVisibilityOfKnob:(id)arg1;
- (id)newCommandToApplyGeometry:(id)arg1 toInfo:(id)arg2;
- (void)addKnobsToArray:(id)arg1;
- (id)newTrackerForKnob:(id)arg1;
- (void)updatePositionsOfKnobs:(id)arg1;
- (void)viewScaleDidChange;
- (void)didEndZooming;
- (void)dynamicDragDidEnd;
- (BOOL)shouldShowKnobs;
- (void)didUpdateLayer:(id)arg1;
- (id)initWithLayout:(id)arg1 canvas:(id)arg2;

@end
