/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

@class <TUCallModelDelegate>;

@interface TUCallModel : NSObject  {
    BOOL _ambiguous;
    BOOL _swappable;
    BOOL _mergeable;
    BOOL _holdAllowed;
    BOOL _addCallAllowed;
    BOOL _takingCallsPrivateAllowed;
    BOOL _hardPauseAvailable;
    BOOL _endAndAnswerAllowed;
    BOOL _holdAndAnswerAllowed;
    BOOL _sendToVoicemailAllowed;
    <TUCallModelDelegate> *_delegate;
    int _ambiguityState;
}

@property <TUCallModelDelegate> * delegate;
@property(getter=isAmbiguous,readonly) BOOL ambiguous;
@property(readonly) int ambiguityState;
@property(getter=isSwappable,readonly) BOOL swappable;
@property(getter=isMergeable,readonly) BOOL mergeable;
@property(getter=isHoldAllowed,readonly) BOOL holdAllowed;
@property(getter=isAddCallAllowed,readonly) BOOL addCallAllowed;
@property(getter=isTakingCallsPrivateAllowed,readonly) BOOL takingCallsPrivateAllowed;
@property(getter=isHardPauseAvailable,readonly) BOOL hardPauseAvailable;
@property(getter=isEndAndAnswerAllowed,readonly) BOOL endAndAnswerAllowed;
@property(getter=isHoldAndAnswerAllowed,readonly) BOOL holdAndAnswerAllowed;
@property(getter=isSendToVoicemailAllowed,readonly) BOOL sendToVoicemailAllowed;


- (BOOL)isSendToVoicemailAllowed;
- (BOOL)isHoldAndAnswerAllowed;
- (BOOL)isEndAndAnswerAllowed;
- (BOOL)isHardPauseAvailable;
- (BOOL)isTakingCallsPrivateAllowed;
- (int)ambiguityState;
- (BOOL)isAddCallAllowed;
- (BOOL)isHoldAllowed;
- (BOOL)isMergeable;
- (BOOL)isSwappable;
- (BOOL)isAmbiguous;
- (id)delegate;
- (id)description;
- (void)setDelegate:(id)arg1;

@end
