/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class _UIUserDefaultsActivity, UILongPressGestureRecognizer, NSIndexPath, UIView, NSDictionary, _UIActivityUserDefaults, <UIActivityGroupViewControllerDelegate>, NSArray;

@interface UIActivityGroupViewController : UICollectionViewController <_UIActivityGroupViewDelegateFlowLayout, UIGestureRecognizerDelegate> {
    BOOL _darkStyleOnLegacyApp;
    BOOL _embedded;
    BOOL _picker;
    BOOL _hasActivities;
    BOOL _activityIndexDidChangeWhileDragging;
    <UIActivityGroupViewControllerDelegate> *_delegate;
    int _activityCategory;
    NSDictionary *_customActivityTitles;
    NSArray *_activities;
    NSArray *_visibleActivities;
    _UIActivityUserDefaults *_userDefaults;
    _UIUserDefaultsActivity *_userDefaultsActivity;
    UILongPressGestureRecognizer *_editingGestureRecognizer;
    UIView *_draggingView;
    NSIndexPath *_indexPathForMenuActivity;
    struct CGPoint { 
        float x; 
        float y; 
    } _initialDraggingLocation;
}

@property <UIActivityGroupViewControllerDelegate> * delegate;
@property int activityCategory;
@property(copy) NSDictionary * customActivityTitles;
@property(copy) NSArray * activities;
@property BOOL darkStyleOnLegacyApp;
@property(getter=isEmbedded) BOOL embedded;
@property(getter=isPicker) BOOL picker;
@property BOOL hasActivities;
@property(copy) NSArray * visibleActivities;
@property(retain) _UIActivityUserDefaults * userDefaults;
@property(retain) _UIUserDefaultsActivity * userDefaultsActivity;
@property(retain) UILongPressGestureRecognizer * editingGestureRecognizer;
@property struct CGPoint { float x1; float x2; } initialDraggingLocation;
@property(retain) UIView * draggingView;
@property BOOL activityIndexDidChangeWhileDragging;
@property(copy) NSIndexPath * indexPathForMenuActivity;


- (void)setDraggingView:(id)arg1;
- (id)draggingView;
- (void)setInitialDraggingLocation:(struct CGPoint { float x1; float x2; })arg1;
- (struct CGPoint { float x1; float x2; })initialDraggingLocation;
- (void)setVisibleActivities:(id)arg1;
- (id)visibleActivities;
- (void)setHasActivities:(BOOL)arg1;
- (BOOL)hasActivities;
- (void)setEmbedded:(BOOL)arg1;
- (void)setCustomActivityTitles:(id)arg1;
- (id)customActivityTitles;
- (int)activityCategory;
- (void)renameActivity:(id)arg1;
- (void)setActivities:(id)arg1;
- (id)initWithActivityCategory:(int)arg1;
- (BOOL)collectionView:(id)arg1 layout:(id)arg2 moveItemAtIndexPath:(id)arg3 toIndexPath:(id)arg4;
- (void)activityUserDefaultsDidChange:(id)arg1;
- (void)ignoreUserDefaultsChangesWhileUsingBlock:(id)arg1;
- (BOOL)canMoveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (BOOL)activityIndexDidChangeWhileDragging;
- (void)setActivityIndexDidChangeWhileDragging:(BOOL)arg1;
- (void)setIndexPathForMenuActivity:(id)arg1;
- (id)editingGestureRecognizer;
- (BOOL)isPicker;
- (BOOL)isEmbedded;
- (void)setDarkStyleOnLegacyApp:(BOOL)arg1;
- (BOOL)darkStyleOnLegacyApp;
- (id)activityForItemAtIndexPath:(id)arg1;
- (void)hideItemAtIndexPath:(id)arg1;
- (id)indexPathForMenuActivity;
- (void)_setVisibleActivities:(id)arg1 animated:(BOOL)arg2;
- (id)activities;
- (void)_updateVisibleActivitiesAnimated:(BOOL)arg1;
- (void)_setActivities:(id)arg1 animated:(BOOL)arg2;
- (id)userDefaultsActivity;
- (void)setActivities:(id)arg1 animated:(BOOL)arg2;
- (void)hideActivity:(id)arg1;
- (void)registerForActivityUserDefaultsChanges;
- (void)setEditingGestureRecognizer:(id)arg1;
- (id)activityGroupViewLayout;
- (void)handleEditingGesture:(id)arg1;
- (void)unregisterForActivityUserDefaultsChanges;
- (struct CGSize { float x1; float x2; })_preferredCellSize;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })_preferredSectionInset;
- (void)setUserDefaultsActivity:(id)arg1;
- (id)userDefaults;
- (void)setUserDefaults:(id)arg1;
- (void)setActivityCategory:(int)arg1;
- (void)setPicker:(BOOL)arg1;
- (id)initWithActivityCategory:(int)arg1 userDefaults:(id)arg2 userDefaultsIdentifier:(id)arg3;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(int)arg3;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidLoad;
- (struct CGSize { float x1; float x2; })collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)canBecomeFirstResponder;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (void)setDelegate:(id)arg1;

@end
