/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSMutableDictionary, NSArray;

@interface UIPushBehavior : UIDynamicBehavior  {
    float _angle;
    float _magnitude;
    BOOL _active;
    int _mode;
    struct CGVector { 
        float dx; 
        float dy; 
    } _forceVector;
    double _timeInterval;
    NSMutableDictionary *_targetPoints;
    int _i;
}

@property(copy,readonly) NSArray * items;
@property(readonly) int mode;
@property BOOL active;
@property float angle;
@property float magnitude;
@property struct CGVector { float x1; float x2; } pushDirection;


- (struct CGVector { float x1; float x2; })pushDirection;
- (void)setTargetOffsetFromCenter:(struct UIOffset { float x1; float x2; })arg1 forItem:(id)arg2;
- (struct UIOffset { float x1; float x2; })targetOffsetFromCenterForItem:(id)arg1;
- (void)setTargetPoint:(struct CGPoint { float x1; float x2; })arg1 forItem:(id)arg2;
- (struct CGPoint { float x1; float x2; })targetPointForItem:(id)arg1;
- (void)setYComponent:(float)arg1;
- (void)setXComponent:(float)arg1;
- (void)setMagnitude:(float)arg1;
- (float)xComponent;
- (float)yComponent;
- (void)setAngle:(float)arg1 magnitude:(float)arg2;
- (float)magnitude;
- (void)setXComponent:(float)arg1 yComponent:(float)arg2;
- (void)_step;
- (float)angle;
- (void)setAngle:(float)arg1;
- (void)removeItem:(id)arg1;
- (void)addItem:(id)arg1;
- (void)setActive:(BOOL)arg1;
- (void)setPushDirection:(struct CGVector { float x1; float x2; })arg1;
- (id)initWithItems:(id)arg1 mode:(int)arg2;
- (void)_dissociate;
- (void)_associate;
- (int)mode;
- (id)initWithItems:(id)arg1;
- (BOOL)active;
- (id)items;
- (void)_commonInit;
- (id)description;
- (void)dealloc;
- (id)init;

@end
