/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@class NSObject<OS_dispatch_source>;

@interface VKMemoryObserver : NSObject  {
    id _target;
    SEL _selector;
    NSObject<OS_dispatch_source> *_memoryNotificationEventSource;
}


- (id)initWithTarget:(id)arg1 selector:(SEL)arg2;
- (void)_receivedMemoryNotification;
- (void)dealloc;

@end
