/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

@class NSArray, NSString, NSDictionary, NSMutableArray, NSDate;

@interface VMUProcessDescription : NSObject  {
    unsigned int _task;
    int _pid;
    struct _CSTypeRef { 
        unsigned int _opaque_1; 
        unsigned int _opaque_2; 
    } _symbolicator;
    NSString *_processName;
    BOOL _processNameNeedsCorrection;
    NSString *_executablePath;
    BOOL _executablePathNeedsCorrection;
    unsigned long long _executableLoadAddress;
    int _cpuType;
    BOOL _is64Bit;
    NSDictionary *_lsApplicationInformation;
    NSMutableArray *_binaryImages;
    NSArray *_sortedBinaryImages;
    NSDictionary *_binaryImageHints;
    NSArray *_unreadableBinaryImagePaths;
    BOOL _binaryImagePostProcessingComplete;
    NSDictionary *_buildVersionDictionary;
    NSDictionary *_osVersionDictionary;
    NSString *_parentProcessName;
    NSString *_parentExecutablePath;
    int _ppid;
    NSDate *_date;
}

+ (id)parseBinaryImagesDescription:(id)arg1;

- (id)binaryImagesDescriptionForBacktraces:(id)arg1;
- (id)binaryImageDictionaryForAddress:(unsigned long long)arg1;
- (BOOL)isAppleApplication;
- (id)dateAndVersionDescription;
- (id)processDescriptionHeader;
- (id)_systemVersionDescription;
- (id)parentProcessName;
- (id)_cpuTypeDescription;
- (id)processVersion;
- (id)_buildInfoDescription;
- (id)_osVersionDictionary;
- (id)_buildVersionDictionary;
- (id)_binaryImagesDescriptionForRanges:(id)arg1;
- (id)_rangesOfBinaryImages:(id)arg1 forBacktraces:(id)arg2;
- (void)clearCrashReporterInfo;
- (id)_bundleLock;
- (void)setCrashReporterInfo;
- (id)_sanitizeVersion:(id)arg1;
- (id)processVersionDictionary;
- (id)binaryImages;
- (id)_extractInfoPlistFromSymbolOwner:(struct _CSTypeRef { unsigned int x1; unsigned int x2; })arg1 withMemory:(struct mapped_memory_t { }*)arg2;
- (double)_extractDyldInfoFromSymbolOwner:(struct _CSTypeRef { unsigned int x1; unsigned int x2; })arg1 withMemory:(struct mapped_memory_t { }*)arg2;
- (id)_readDataFromMemory:(struct mapped_memory_t { }*)arg1 atAddress:(unsigned long long)arg2 size:(unsigned long)arg3;
- (void)_extractBinaryImageInfoFromSymbolOwner:(struct _CSTypeRef { unsigned int x1; unsigned int x2; })arg1;
- (id)binaryImagesDescription;
- (id)initWithPid:(int)arg1 orTask:(unsigned int)arg2;
- (int)cpuType;
- (int)pid;
- (unsigned int)task;
- (id)processIdentifier;
- (id)displayName;
- (id)processName;
- (id)executablePath;
- (id)date;
- (id)bundleIdentifier;
- (id)description;
- (void)dealloc;

@end
